const nehemiaChapters = [

{
book: 'Nehemia',
chapter: '1',
content: [

"	1 DIE geskiedenis van NegemJaH, die seun van HagalJaH. En in die maand Kislew van die twintigste jaar toe ek in die vesting Susan was,	",
"	2 het Hanáni, een van my broers, gekom, hy en manne uit JeHûWdah; en ek het hulle gevra na die manne van JeHûWdah, die vrygeraaktes wat oorgebly het uit die gevangenskap, en na Jerusalem.	",
"	3 En hulle het vir my gesê: Die oorgeblewenes wat vrygekom het uit die gevangenskap daar in die provinsie, verkeer in groot besoedeling en in smaad, en die muur van Jerusalem lê stukkend en haar Poorte is met vuur verbrand.	",
"	4 En toe ek hierdie woorde hoor, het ek gesit en ween, en ek het dae lank getreur; en ek het gevas en gebid voor die Aangesig van die Elohey van die Hemele	",
"	5 en gesê: Ag, JaHWeH, Elohey van die Hemele, grote en gedugte El, wat die Verbond hou en Medelye het met die wat U liefhet en U Gebooie onderhou -	",
"	6 laat U Oor tog opmerksaam en U Oë oop wees, om te luister na die gebed van U kneg wat ek vandag voor U Aangesig bid, dag en nag, vir die kinders van JisraEl, U knegte, terwyl ek die oortredinge van die kinders van JisraEl bely wat ons teen U gedoen het; ook ek en my familie het oortree.	",
"	7 Ons het baie verkeerd gehandel teenoor U, en ons het die Gebooie en Insettinge en Regsprake wat U aan Moshè, U kneg, beveel het, nie gehou nie.	",
"	8 Dink tog aan die Woord wat U aan Moshè, U kneg, beveel het, naamlik: As julle ontrou is, sal Ek julle onder die volke verstrooi;	",
"	9 maar as julle jul tot My bekeer en My Gebooie onderhou en haar doen - al was julle verjaagdes aan die einde van die Hemele, dan sal Ek hulle daarvandaan versamel en hulle bring na die plek wat Ek verkies het om My Naam daar te laat woon.	",
"	10 Hulle is tog U knegte en U volk wat U verlos het deur U grote Krag en deur U Sterke Hand.	",
"	11 Ag, my Meester, laat U oor tog opmerksaam wees op die gebed van U kneg en op die gebed van U knegte wat verlang om U Naam te vrees; en laat dit tog vandag U kneg toegereken word, en verleen hom barmhartigheid voor die oë van hierdie man. Ek was naamlik skinker van die koning.	",

]
},
{
book: 'Nehemia',
chapter: '2',
content: [
		
"	1 EN in die maand Nisan van die twintigste jaar van koning Artasásta toe daar wyn voor hom was, het ek die wyn opgehef en aan die koning gegee; en omdat ek nooit voor hom bedroef was nie,	",
"	2 het die koning my gevra: Waarom is jou aangesig so bedroef; jy is tog nie siek nie? Dit is niks anders as hartseer nie. En ek het baie bevrees geword	",
"	3 en aan die koning gesê: Mag die koning ewig lewe! Waarom sou my aangesig nie bedroef wees nie, terwyl tog die Stad waar my vaders begrawe is, woes lê en haar Poorte deur vuur verteer is?	",
"	4 Daarop vra die koning my: Wat is dan jou begeerte? En ek het tot die Elohey van die Hemele gebid	",
"	5 en aan die koning gesê: As die koning dit goedvind en as u dienaar welgevallig is in u oë, stuur my dan na JeHûWdah, na die Stad waar my vaders begrawe lê, dat ek haar kan opbou.	",
"	6 Toe vra die koning my, terwyl die koningin langs hom sit: Hoe lank sal jou reis duur, en wanneer sal jy terugkom? En die koning het dit goedgevind om my te stuur. En ek het hom ’n bepaalde tyd aangegee	",
"	7 en aan die koning gesê: As die koning dit goedvind, kan hulle vir my briewe saamgee aan die goewerneurs wes van die Eufraat, dat hulle my laat deurtrek totdat ek in JeHûWdah kom;	",
"	8 en ’n brief aan Asaf, opsigter van die park van die koning, dat hy aan my hout lewer om die Poorte van die vesting wat by die Tempel behoort, met balke uit te lê, en vir die muur van die Stad en vir die huis waar ek sal intrek. En die koning het my dit toegestaan volgens die suiwer Hand van my Elohey oor my.	",
"	9 En ek het by die goewerneurs gekom wes van die Eufraat en die briewe van die koning aan hulle gegee. Ook leërowerstes en perderuiters het die koning met my saamgestuur.	",
"	10 Maar toe Sanbállat, die Horoniet, en TobiJaH, die Ammonitiese kneg, hoor dat ‘n adamiet gekom het om vir die kinders van JisraEl iets goeds te soek, was hulle daaroor erg ontstemd.	",
"	11 En toe ek in Jerusalem kom en daar drie dae was,	",
"	12 het ek my in die nag gereedgemaak, ek en enkele manne saam met my; maar ek het aan geen adamiet meegedeel wat my Elohey in my hart gegee het om vir Jerusalem te doen nie; daar was ook geen dier by my nie, behalwe die dier waar ek op gery het.	",
"	13 En ek het in die nag deur die Dalpoort uitgery en na die kant van die Fontein van die Draak en na die poort van vullis toe; en ek het die mure van Jerusalem besigtig wat stukkend lê, en haar Poorte wat deur vuur verteer was.	",
"	14 En ek het verder gegaan na die Fonteinpoort en na die Koningsvywer. Maar daar was geen plek vir die dier om onder my verder te gaan nie.	",
"	15 Daarna het ek in die nag in die dal opgeklim en die muur besigtig. Toe het ek weer deur die Dalpoort ingekom en teruggegaan.	",
"	16 Maar die leiers het nie geweet waar ek heengegaan het en wat ek doen nie; want ek het tot nog toe die manne van JeHûWdah en die priesters en die edeles en die leiers en die ander wat die werk moes doen, niks te kenne gegee nie.	",
"	17 Daarop sê ek vir hulle: Julle sien die besoedeling waar ons in is, dat Jerusalem woes lê en haar Poorte met vuur verbrand is; kom, laat ons die muur van Jerusalem opbou, dat ons nie langer ’n voorwerp van smaad kan wees nie.	",
"	18 En ek vertel hulle van die Hand van my Elohey wat goed was oor my, en ook van die woorde van die koning wat hy my gesê het. En hulle sê: Ons sal ons klaarmaak en bou! En hulle het hulle hande sterk gemaak vir die goeie [werk].	",
"	19 Maar toe Sanbállat, die Horoniet, en TobiJaH, die Ammonitiese kneg, en Gesem, die Arabier, dit hoor, het hulle ons bespot en ons verag en gesê: Wat is dit vir ’n ding wat julle doen? Wil julle teen die koning rebelleer?	",
"	20 Toe antwoord ek hulle en sê vir hulle: Die Elohey van die Hemele, Hy sal ons dit laat slaag, en ons, Sy knegte, sal ons klaarmaak en bou; maar julle het geen deel of Geregtigheid of herinnering in Jerusalem nie.	",

]
},
{
book: 'Nehemia',
chapter: '3',
content: [
		
"	1 EN El-Jashib, die hoëpriester, het hom klaargemaak met sy broers, die priesters, en hulle het die Skaapspoort gebou; hulle het hom aangewys en sy deure ingesit; verder tot by die toring Hamméa wat hulle afgemeet het, tot by die toring GanánEl.	",
"	2 En naas hom het die manne van Jérigo gebou; en daarnaas het Sakkur, die seun van Imri, gebou.	",
"	3 En die Vispoort het die seuns van Sénaä gebou; hulle het hom met balke uitgelê en sy deure, sy sluitbalke en sy grendels ingesit.	",
"	4 En naas hulle het Méremot, die seun van UriJaH, die seun van Hakkos, herstel; en naas hulle het Mesúllam, die seun van BerekJaH, die seun van MeshezabEl, herstel; en naas hulle het Sadok, die seun van Baäna, herstel.	",
"	5 En naas hulle het die Tekoïete herstel; maar hulle vername manne het hulle nek nie gebuig onder die diens van hulle meesters nie.	",
"	6 En die Ou Poort het JôWjada, die seun van Paséag, en Mesúllam, die seun van BesodJaH, herstel; hulle het hom met balke uitgelê en sy deure en sy sluitbalke en sy grendels ingesit.	",
"	7 En naas hulle het MelátJaH, die Gibeoniet, en Jadon, die Meronotiet, die manne van Gíbeon en Mispa, herstel by die setel van die goewerneur van die gebied wes van die Eufraat.	",
"	8 Naas hom het UzziEl, die seun van HarhaJaH, [van] die goudsmede, herstel; en naas hom het HananJaH, ’n lid van die salfmengers, herstel; en hulle het Jerusalem onaangeroerd gelaat tot by die breë muur.	",
"	9 En naas hulle het RafaJaH, die seun van Hur, owerste van die halwe distrik Jerusalem, herstel.	",
"	10 En naas hulle het JedaJaH, die seun van Harúmaf, herstel - teenoor sy huis; en naas hom het Gattush, die seun van HasabneJaH, herstel.	",
"	11 ’n Tweede stuk het MalkiJaH, die seun van Harim, en Hassub, die seun van Pahat-Moab, herstel, ook die Bakoondtoring.	",
"	12 En naas hom het Sallum, die seun van Hallóhes, owerste van die halwe distrik Jerusalem, herstel, hy met sy dogters.	",
"	13 Die Dalpoort het Hanun en die inwoners van Sanóag herstel; hulle het hom opgebou en sy deure, sy sluitbalke en sy grendels ingesit, ook duisend voorarm aan die muur tot by die Aspoort.	",
"	14 En die Aspoort het MalkiJaH, die seun van Regab, owerste van die distrik Bet-Hakkerem, herstel; hy het hom opgebou en sy deure, sy sluitbalke en sy grendels ingesit.	",
"	15 En die Fonteinpoort het Shilóag, die seun van Kol-Hosé, owerste van die distrik Mispa, herstel; hy het hom opgebou en hom oordek, en hy het sy deure, sy sluitbalke en sy grendels ingesit, ook die muur van die dam van die waterleiding by die koning se tuin, en tot by die trappe wat van die Stad van Dawid afloop.	",
"	16 Ná hom het NegemJaH, die seun van Asbuk, owerste van die halwe distrik Bet-Sur, tot teenoor die Dawidsgrafte herstel en tot by die kunstig aangelegde dam en tot by die huis van die dapperes.	",
"	17 Ná hom het die Leviete - Rehum, die seun van Bani, herstel; naas hom het GashabJaH, die owerste van die halwe distrik Kehíla, vir sy distrik herstel.	",
"	18 Ná hom het hulle broers, Báwai, die seun van Hénadad, die owerste van die [ander] halwe distrik Kehíla, herstel.	",
"	19 En naas hom het Eser, die seun van Jehshua, die owerste van Mispa, ’n tweede stuk herstel teenoor die opgang na die wapenhuis, die Winkelhaak.	",
"	20 Ná hom het Barug, die seun van Sábbai, ’n tweede stuk ywerig herstel; van die Winkelhaak af tot by die huisdeur van die hoëpriester El-Jashib.	",
"	21 Ná hom het Méremot, die seun van UriJaH, die seun van Hakkos, ’n tweede stuk herstel, van die huisdeur van El-Jashib af tot by die end van El-Jashib se huis.	",
"	22 En ná hom het die priesters, die manne van die [Jordaan]streek, herstel.	",
"	23 Ná hom het Benjamin en Hassub teenoor hulle huis herstel; ná hom het AzarJaH, die seun van MaàseiJâH, die seun van AnanJaH, langs sy huis herstel.	",
"	24 Ná hom het Bínnuï, die seun van Hénadad, ’n tweede stuk herstel; van die huis van AzarJaH af tot by die Winkelhaak en tot by die Hoek.	",
"	25 Palal, die seun van Usai, teenoor die Winkelhaak en die boonste toring wat uit die huis van die koning uitsteek, by die voorhof van bewaking; ná hom PedahJaH, die seun van Párhos.	",
"	26 En die tempeldienaars het gewoon op die Heuwel tot teenoor die Waterpoort, teen die ooste, en die Toring wat uitsteek.	",
"	27 Ná hom het die Tekoïete ’n tweede stuk herstel, van teenoor die groot Toring af wat uitsteek, tot by die Heuwel-muur.	",
"	28 Bokant die Perdepoort het die priesters herstel, elkeen teenoor sy huis.	",
"	29 Daarnaas het Sadok, die seun van Immer, teenoor sy huis herstel; en ná hom het ShemaJaH, die seun van ShekanJaH, die bewaker van die Oospoort, herstel.	",
"	30 Ná hom het HananJaH, die seun van ShelemJaH, en Hanun, die sesde seun van Salaf, ’n tweede stuk herstel; daarnaas het Mesúllam, die seun van BerekJaH, teenoor sy kamer herstel.	",
"	31 Ná hom het MalkiJaH, lid van die goudsmede, herstel tot by die huis van die tempeldienaars en die koopmans, teenoor die Wagpoort en tot by die bo-kamer op die Hoek.	",
"	32 En tussen die bo-kamer op die Hoek en die Skaapspoort het die goudsmede en die koopmans herstel.	",

]
},
{
book: 'Nehemia',
chapter: '4',
content: [
		
"	1 MAAR toe Sanbállat hoor dat ons die muur bou, het hy kwaad geword en hom baie geërg, en hy het met die manne van JeHûWdah gespot	",
"	2 en voor sy broers en die leër van Samaría gespreek en gesê: Wat maak die magtelose manne van JeHûWdah? Sal ’n mens hulle laat begaan? Sal hulle slag? Sal hulle haar vandag nog voltooi? Sal hulle die klippe uit die grondhope lewendig maak, al is hulle deur brand verniel?	",
"	3 En TobiJaH, die Ammoniet, het langs hom gestaan en gesê: Wat hulle ook al bou - as ’n jakkals teen haar opspring, sal hy hulle klipmuur omgooi!	",
"	4 Hoor, onse Elohey, dat ons ’n veragting geword het; en bring hulle smaad op hulle hoof terug en gee hulle oor aan plundering in die Aarde van gevangenskap.	",
"	5 En dek hulle ongeregtigheid nie toe nie, en laat hulle oortredinge nie uitgedelg word voor U Aangesig nie; want hulle het U getart teenoor die bouers.	",
"	6 Maar ons het die muur opgebou, en die hele muur is tot op haar helfte herstel; en die volk was met hulle hart in die werk.	",
"	7 Maar toe Sanbállat en TobiJaH en die Arabiere en die Ammoniete en die Asdodiete hoor dat die verbetering aan die mure van Jerusalem vorder, dat die skeure begin toeraak, het hulle baie kwaad geword.	",
"	8 En hulle het almal met mekaar ’n sameswering gesmee om teen Jerusalem te gaan veg en daar verwarring te stig.	",
"	9 Maar ons het tot onse Elohey gebid en om hulle ontwil ’n wag teen hulle uitgesit, dag en nag.	",
"	10 Maar JeHûWdah het gesê: Die krag van die lasdraers beswyk, en die puinhoop is groot, sodat ons nie aan die muur kan bou nie.	",
"	11 En ons teëstanders het gesê: Hulle mag niks weet en sien nie totdat ons tussen hulle inkom en hulle doodslaan en ’n einde maak aan die werk.	",
"	12 En toe die manne van JeHûWdah wat by hulle gewoon het, inkom en wel tien maal, uit al die plekke, aan ons sê: Julle moet na ons toe terugkom -	",
"	13 het ek op die laagste plekke agter die muur, op die kaal plekke, [manskappe] opgestel - ek het die volk opgestel volgens hulle families met hul swaarde, hul spiese en hul boë.	",
"	14 En ek het dit gesien en my opgerig en aan die edeles en die leiers en die ander mense gesê: Julle moet nie bang wees vir hulle nie; onthou my Meester, die Grote en die Gedugte, en veg vir julle broers, julle seuns en julle dogters, julle vroue en julle huise.	",
"	15 En toe ons vyande hoor dat dit aan ons bekend geword het, en die Elohim hulle plan verydel het, het ons almal teruggegaan na die muur, elkeen na sy werk.	",
"	16 En van dié dag af was die helfte van my mense besig met die werk, en die ander helfte het die spiese en die skilde en die boë en die pantsers gehou, terwyl die owerstes agter die hele huis van JeHûWdah gestaan het.	",
"	17 Van die bouers aan die muur het die lasdraers hulle werk so gedoen dat hulle met die een hand die werk verrig het, terwyl die ander hand die werpspies vashou,	",
"	18 en die bouers het elkeen sy swaard aan sy heupe gegord en gebou, terwyl die ramshoringblaser by my gestaan het.	",
"	19 En ek het aan die edeles en die leiers en die ander mense gesê: Die werk is groot en uitgestrek, en ons is uitmekaar op die muur, die een ver van die ander af.	",
"	20 Op die plek waar julle die geluid van die ramshoring hoor, daar moet julle by ons bymekaarkom; onse Elohey sal vir ons stry.	",
"	21 En ons het die werk gedoen, terwyl die helfte van hulle die spiese vashou vandat die rooidag uitkom totdat die Sterre verskyn.	",
"	22 Ook het ek in dié tyd aan die volk gesê: Elkeen moet met sy kneg binnekant Jerusalem vernag, sodat hulle vir ons in die nag ’n wag kan wees en oordag ’n werkkrag.	",
"	23 Maar ek self en my broers en my mense en die manne van die wag wat my gevolg het, het nooit ons klere uitgetrek nie - elkeen met sy wapen en water.	",

]
},
{
book: 'Nehemia',
chapter: '5',
content: [
		
"	1 EN daar het ’n groot geroep van die volk en van hulle vroue ontstaan teen hulle broers, die manne van JeHûWdah;	",
"	2 en sommige het gesê: Ons seuns en ons dogters, ons is baie; ons wil koring hê, dat ons kan eet en lewe!	",
"	3 En ander het gesê: Ons landerye en ons wingerde en ons huise moes ons verpand, sodat ons koring kon koop in die hongersnood!	",
"	4 En ander weer het gesê: Ons het op ons landerye en ons wingerde silwer geleen vir die belasting aan die koning.	",
"	5 En nou, ons vlees is soos die vlees van ons broers en ons kinders soos hulle kinders, en tog moet ons nou ons seuns en ons dogters tot slawe verneder, en van ons dogters is al verneder sonder dat ons daar iets aan kan doen, en ons  landerye en ons wingerde behoort aan ander.	",
"	6 En ek was baie verontwaardig toe ek hulle geroep en hierdie woorde hoor.	",
"	7 En ek het by myself beraadslaag en met die edeles en die leiers getwis en aan hulle gesê: Julle leen uit op woeker, elkeen aan sy broer! En ek het ’n groot vergadering teen hulle belê	",
"	8 en aan hulle gesê: Ons het ons broers uit JeHûWdah wat aan die nasies verkoop was, na ons vermoë losgekoop; en tog verkoop julle jul broers, sodat hulle hul aan ons moet verkoop. En hulle het geswyg en geen antwoord gevind nie.	",
"	9 Verder het ek gesê: Dit is nie suiwer wat julle doen nie. Moet julle nie in die Vrees van onse Elohey wandel ter wille van die skande van die nasies, ons vyande, nie?	",
"	10 Ek self, my broers en my mense het ook aan hulle silwer en koring geleen; laat ons tog hierdie lening kwytskeld.	",
"	11 Gee dan vandag nog hulle landerye, hulle wingerde, hulle olyfbome en hulle huise aan hulle terug, en die honderdste deel van die silwer en die koring, die druiwesap en die olie wat julle aan hulle geleen het.	",
"	12 Daarop sê hulle: Ons sal dit teruggee en niks van hulle vorder nie; ons sal net so handel soos u gesê het. En ek het die priesters geroep en hulle laat sweer om volgens hierdie woord te handel.	",
"	13 Ook het ek my boesem uitgeskud en gesê: Mag die Elohim so elke man uitskud wat hierdie woord nie bevestig nie, uit sy huis en uit sy besitting; en mag hy so uitgeskud en leeg wees! Toe sê die hele vergadering: Amein! en hulle het JaHWeH geprys. En die volk het volgens hierdie woord gehandel.	",
"	14 Ook van die dag af dat ek aangestel is om hulle goewerneur te wees in die Aarde van JeHûWdah, van die twintigste jaar af tot die twee-en-dertigste jaar van koning Artasásta, twaalf jaar lank, het ek en my broers die brood van goewerneurs nie geëet nie;	",
"	15 terwyl die vorige goewerneurs wat voor my was, die volk swaar belas het en van hulle brood en wyn geneem het, daarna veertig sikkels silwer. Hulle mense het ook heerskappy gevoer oor die volk; maar so het ek uit vrees vir Elohim nie gedoen nie.	",
"	16 En ook by die werk aan hierdie muur het ek volhard sonder dat ons  landerye aangeskaf het, terwyl tog al my mense daar by die werk versamel was.	",
"	17 En die manne van JeHûWdah, die leiers, honderd-en-vyftig man, sowel as die wat uit die nasies rondom ons na ons toe gekom het, was aan my tafel.	",
"	18 En wat vir elke dag berei is - een bees, ses uitgesoekte stuks kleinvee en voëls - is berei op my koste, en elke tien dae allerhande soorte wyn in oorvloed; en daarby het ek tog die brood van goewerneurs nie begeer nie, omdat die diens swaar was op hierdie volk.	",
"	19 Dink, my Elohey, aan my suiwerheid, aan alles wat ek aan hierdie volk gedoen het!	",

]
},
{
book: 'Nehemia',
chapter: '6',
content: [
		
"	1 EN toe Sanbállat en TobiJaH en Gesem, die Arabier, en ons ander vyande verneem dat ek die muur gebou het en dat daar geen skeur in oorgebly het nie, alhoewel ek tot dié tyd toe geen deure in die Poorte gesit het nie,	",
"	2 laat Sanbállat en Gesem my weet: Kom laat ons bymekaarkom in [een van] die dorpe, in die laagte van Ono; maar hulle het gemeen om my kwaad aan te doen.	",
"	3 Toe stuur ek boodskappers na hulle om te sê: Ek doen ’n groot werk, sodat ek nie kan afkom nie. Waarom moet die werk ophou sodra ek dit verlaat om na julle af te kom?	",
"	4 Nog vier keer het hulle op dieselfde manier na my gestuur, en ek hulle op dieselfde manier geantwoord.	",
"	5 Daarop stuur Sanbállat op dieselfde manier vir die vyfde keer sy dienaar na my met ’n ope brief in sy hand.	",
"	6 In haar was geskrywe: Die gerug gaan rond onder die nasies, en Gasmu sê: Jy en die manne van JeHûWdah is van plan om te rebelleer; daarom bou jy die muur, en jy sal hulle koning word - dergelike dinge.	",
"	7 Ook het jy profete aangestel om van jou in Jerusalem uit te roep en te sê: Koning in JeHûWdah! En nou, sulke dinge sal deur die koning gehoor word; kom dan nou en laat ons saam beraadslaag!	",
"	8 Maar ek het hom laat weet: Daar het nie sulke dinge gebeur as dié waar jy van spreek nie, maar jy het dit self versin.	",
"	9 Want hulle almal wou ons bang maak en het gedink: Hulle hande sal die werk laat lê, sodat dit nie gedoen word nie. Versterk dan nou my hande!	",
"	10 En toe ek in die huis van ShemaJaH, die seun van DeláJaH, die seun van MehetabEl kom, terwyl hy verhinder was, sê hy: Laat ons saamkom in die huis van die Elohim, binne-in die Tempel, en laat ons die deure van die Tempel toesluit; want hulle kom om u dood te maak, ja, hulle sal in die nag kom om u dood te maak.	",
"	11 Maar ek het gesê: Sal ’n man soos ek vlug? En hoe durf een soos ek die Tempel ingaan en in die lewe bly? Ek sal nie ingaan nie.	",
"	12 Want ek het duidelik gemerk dat Elohim hom nie gestuur het nie, maar dat hy die profesie oor my gespreek het, omdat TobiJaH en Sanbállat hom gehuur het.	",
"	13 Daarvoor was hy gehuur, dat ek bang sou word en so sou maak en oortree, sodat dit hulle as besoedelde gerug kon dien om my smaadheid aan te doen.	",
"	14 Dink, my Elohey, aan TobiJaH en aan Sanbállat volgens hierdie werke van hom, en ook aan NoadJaH, die profetes, en die ander profete wat my wou bang maak.	",
"	15 En die muur is voltooi op die vyf-en-twintigste van Elul, in twee-en-vyftig dae.	",
"	16 En toe al ons vyande dit hoor, het al die nasies rondom ons bevrees geword en neerslagtig gevoel, en hulle het erken dat hierdie werk deur onse Elohey gedoen is.	",
"	17 Ook het in dié dae die edeles van JeHûWdah baie briewe geskrywe wat na TobiJaH gegaan het, en dié van TobiJaH het na hulle gekom.	",
"	18 Want baie in JeHûWdah was deur ’n eed aan hom verbonde, omdat hy die skoonseun was van ShekanJaH, die seun van Arag, en sy seun JeHôWganan die dogter van Mesúllam, die seun van BerekJaH, getrou het.	",
"	19 Ook het hulle voor my sy goeie bedoelings verhaal en my woorde na hom uitgebring. TobiJaH het briewe gestuur om my bang te maak.	",

]
},
{
book: 'Nehemia',
chapter: '7',
content: [
		
"	1 EN toe die muur gebou was, het ek die deure ingesit en die poortwagters en die sangers en die Leviete is aangestel.	",
"	2 En ek het my broer Hanáni en HananJaH, die owerste van die vesting, oor Jerusalem aangestel - want hy was ’n man van Waarheid en het die Elohim gevrees bo baie -	",
"	3 en ek het vir hulle gesê: Die Poorte van Jerusalem mag nie oopgemaak word voordat die son warm is nie; en terwyl hulle nog [op wag] staan, moet die deure toegesluit word, en julle moet dit dig grendel; en julle moet van die inwoners van Jerusalem wagte uitsit, elkeen op sy pos en elkeen teenoor sy huis.	",
"	4 En die Stad was wyd uitgestrek en groot, maar die mense in haar midde was min, en die huise was nie opgebou nie.	",
"	5 Toe het my Elohey in my hart gegee dat ek die edeles en die leiers en die volk bymekaar laat kom het om ’n geslagslys aan te lê; en ek het die geslagslys gekry van die wat eerste opgetrek het, en daarin geskrywe gevind:	",
"	6 Dit is die inwoners van die provinsie wat opgetrek het uit die gevangenskap van die ballinge, wat Nebukadnésar, die koning van Babel, weggevoer het, en teruggekom het na Jerusalem en JeHûWdah, elkeen na sy stad;	",
"	7 wat saam met Serubbábel, Jehshua, NegemJaH, AzarJaH, RaamJaH, Nahamáni, Mórdegai, Bilsan, Mispéret, Bigwai, Nehum, Baäna gekom het; die getal manne van die volk van JisraEl was:	",
"	8 die kinders van Párhos, tweeduisend-eenhonderd-twee-en-sewentig;	",
"	9 die kinders van ShafátJaH, driehonderd-twee-en-sewentig;	",
"	10 die kinders van Arag, seshonderd-twee-en-vyftig;	",
"	11 die kinders van Pahat-Moab, van die kinders van Jehshua en JôWab, tweeduisend-agthonderd-en-agttien;	",
"	12 die kinders van Elam, duisend-tweehonderd-vier-en-vyftig;	",
"	13 die kinders van Sattu, agthonderd-vyf-en-veertig;	",
"	14 die kinders van Sakkai, sewehonderd-en-sestig;	",
"	15 die kinders van Bínnuï, seshonderd-agt-en-veertig;	",
"	16 die kinders van Bébai, seshonderd-agt-en-twintig;	",
"	17 die kinders van Asgad, tweeduisend-driehonderd-twee-en-twintig;	",
"	18 die kinders van Adoníkam, seshonderd-sewe-en-sestig;	",
"	19 die kinders van Bigwai, tweeduisend-sewe-en-sestig;	",
"	20 die kinders van Adin, seshonderd-vyf-en-vyftig;	",
"	21 die kinders van Ater, van GizkiJaH, agt-en-negentig;	",
"	22 die kinders van Hasum, driehonderd-agt-en-twintig;	",
"	23 die kinders van Bésai, driehonderd-vier-en-twintig;	",
"	24 die kinders van Harif, honderd-en-twaalf;	",
"	25 die kinders van Gíbeon, vyf-en-negentig;	",
"	26 die manne van Betlehem en Netófa, honderd-agt-en-tagtig;	",
"	27 die manne van Anatot, honderd-agt-en-twintig;	",
"	28 die manne van Bet-Asmáwet, twee-en-veertig;	",
"	29 die manne van Kirjat-Jeárim, Kefíra en Béërot, sewehonderd-drie-en-veertig;	",
"	30 die manne van Rama en Geba, seshonderd-een-en-twintig;	",
"	31 die manne van Migmas, honderd-twee-en-twintig;	",
"	32 die manne van BetEl en Ai, honderd-drie-en-twintig;	",
"	33 die manne van die ander Nebo, twee-en-vyftig;	",
"	34 die kinders van die ander Elam, duisend-tweehonderd-vier-en-vyftig;	",
"	35 die kinders van Harim, driehonderd-en-twintig;	",
"	36 die kinders van Jérigo, driehonderd-vyf-en-veertig;	",
"	37 die kinders van Lod, Hadid en Ono, sewehonderd-een-en-twintig;	",
"	38 die kinders van Sénaä, drieduisend-negehonderd-en-dertig.	",
"	39 Die priesters: die kinders van JedaJaH, van die huis van Jehshua, negehonderd-drie-en-sewentig-	",
"	40 die kinders van Immer, duisend-twee-en-vyftig;	",
"	41 die kinders van Pasgur, duisend-tweehonderd-sewe-en-veertig	",
"	42 die kinders van Harim, duisend-en-sewentien.	",
"	43 Die Leviete: die kinders van Jehshua, van KadmiEl, van die kinders van HodWaH, vier-en-sewentig.	",
"	44 Die sangers: die kinders van Asaf, honderd-agt-en-veertig.	",
"	45 Die poortwagters: die kinders van Sallum, die kinders van Ater, die kinders van Talmon, die kinders van Akkub, die kinders van Hatíta, die kinders van Sobai, honderd-agt-en-dertig.	",
"	46 Die tempeldienaars: die kinders van Síha, die kinders van Hasúfa, die kinders van Tábbaot;	",
"	47 die kinders van Keros, die kinders van Sia, die kinders van Padon;	",
"	48 die kinders van Lebána, die kinders van Hágaba, die kinders van Salmai;	",
"	49 die kinders van Hanan, die kinders van Giddel, die kinders van Gahar;	",
"	50 die kinders van ReáJaH, die kinders van Resin, die kinders van Nekóda;	",
"	51 die kinders van Gassam, die kinders van Ussa, die kinders van Paséag;	",
"	52 die kinders van Bésai, die kinders van die Meüniete, die kinders van die Nefisiete;	",
"	53 die kinders van Bakbuk, die kinders van Hakúfa, die kinders van Harhur;	",
"	54 die kinders van Baslut, die kinders van Mehída, die kinders van Harsa;	",
"	55 die kinders van Barkos, die kinders van Sísera, die kinders van Temag;	",
"	56 die kinders van Nesíag, die kinders van Hatífa.	",
"	57 Die kinders van die dienaars van Salomo: die kinders van Sotai, die kinders van Soféret, die kinders van Perída;	",
"	58 die kinders van Jáäla, die kinders van Darkon, die kinders van Giddel;	",
"	59 die kinders van ShafátJaH, die kinders van Hattil, die kinders van Pogéret-Hassebáim, die kinders van Amon	",
"	60 al die tempeldienaars en die kinders van die dienaars van Salomo: driehonderd-twee-en-negentig.	",
"	61 En dit is hulle wat opgetrek het uit Tel-Melag, Tel-Harsa, Kerub, Addon en Immer, maar wat nie hul familie en hul saad kon aanwys, of hulle uit JisraEl afkomstig was nie -	",
"	62 die kinders van DeláJaH, die kinders van TobiJaH, die kinders van Nekóda: seshonderd-twee-en-veertig.	",
"	63 En van die priesters: die kinders van KabáJaH, die kinders van Hakkos, die kinders van Barsíllai, wat uit die dogters van Barsíllai, die Gileadiet, ’n vrou geneem het en na hulle naam genoem is.	",
"	64 Hulle het hul stamboom gesoek onder die wat in die register opgeneem is, maar dit was nie te vinde nie; daarom is hulle gekleurd verklaar, onbevoeg vir die priesterskap.	",
"	65 En die goewerneur het aan hulle gesê dat hulle nie mag eet van die Apartheid van die Aparthede nie, totdat die priester sou optree met Urim en Tummim.	",
"	66 Die hele vergadering saam was twee-en-veertigduisend-driehonderd-en-sestig;	",
"	67 behalwe hulle slawe en hulle slavinne; dié was seweduisend-driehonderd-sewe-en-dertig. En hulle het tweehonderd-vyf-en-veertig sangers en sangeresse gehad.	",
"	68 Hulle perde was sewehonderd-ses-en-dertig; hulle muile tweehonderd-vyf-en-veertig;	",
"	69 kamele, vierhonderd-vyf-en-dertig; esels, sesduisend-sewehonderd-en-twintig.	",
"	70 En ’n deel van die hoofde van die vaders het bygedra vir die werk; die goewerneur se bydrae tot die fonds was: in goud duisend dragmes, vyftig sprinkelflesse, vyfhonderd-en-dertig priesterrokke.	",
"	71 En van die hoofde van die vaders het gegee vir die boufonds: in goud twintigduisend dragmes, en in silwer tweeduisend-tweehonderd mines.	",
"	72 En wat die res van die volk gegee het, was: in goud twintigduisend dragmes, en in silwer tweeduisend mines, en sewe-en-sestig priesterrokke.	",
"	73 So het dan die priesters en die Leviete en die poortwagters en die sangers en van die volk en die tempeldienaars en die hele JisraEl in hulle stede gaan woon en toe die sewende maand aankom, terwyl die kinders van JisraEl in hulle stede was,	",

]
},
{
book: 'Nehemia',
chapter: '8',
content: [
		
"	1 EN toe die sewende maand aankom, terwyl die kinders van JissraEl in hulle stede was,	",
"	2 het die hele volk soos een man op die plein voor die Waterpoort bymekaargekom en aan Ezra, die skrifgeleerde, gesê om die Boekrol van die Wet van Moshè, wat JaHWeH JisraEl beveel het, te bring.	",
"	3 En Ezra, die priester, het die Wet voor die vergadering gebring, manne sowel as vroue en almal wat met verstand kon luister, op die eerste dag vanaf die sewende maand.	",
"	4 En hy het uit haar voorgelees voor die plein wat voor die Waterpoort was, vandat dit lig geword het tot die middag, in teenwoordigheid van die manne en die vroue en die wat kon verstaan; en die ore van die hele volk was op die Boekrol van die Wet gerig.	",
"	5 En Ezra, die skrifgeleerde, het op ’n houtverhoog gestaan wat hulle vir die geleentheid gemaak het, en langs hom het aan sy regterhand gestaan: MattithJaH en Sema en AnaJaH en UriJaH en GielkiJaH en MaàseiJâH; en aan sy linkerhand: PedahJaH en MisahaEl en MalkiJaH en Hasum en Hasbaddána, ZekarJaH, Mesúllam.	",
"	6 En Ezra het die Boekrol oopgemaak voor die oë van die hele volk, want hy het bokant die hele volk gestaan; en toe hy hom oopmaak, het die hele volk opgestaan.	",
"	7 En Ezra het JaHWeH, die Elohim die Grote, geloof, en die hele volk het geantwoord: Amein, amein! met opheffing van hulle hande; en hulle het hul gebuig en tot JaHWeH neergebuig met die gesig na die Aarde toe.	",
"	8 En Jehshua en Bani en SerébJaH, Jamin, Akkub, Sábbetai, HodiJaH, MaàseiJâH, Kelíta, AzarJaH, JôWzabad, Hanan, PelaJaH en die Leviete het die volk in die Wet onderrig onderwyl die volk op hulle plek bly staan.	",
"	9 En hulle het uit die Boekrol van die Wet van die Elohim, duidelik voorgelees en haar verklaar, sodat hulle verstaan het wat voorgelees is.	",
"	10 Daarop het NegemJaH - hy was die goewerneur - en Ezra, die priester, die skrifgeleerde, en die Leviete wat die volk onderrig, aan die hele volk gesê: Die dag - apart gestel is sy aan JaHWeH julle Elohey; treur nie en ween nie! Want die hele volk het geween toe hulle die Woorde van die Wet hoor.	",
"	11 Verder het hy vir hulle gesê: Gaan, eet lekker spys en drink soet dranke en stuur porsies aan hulle vir wie niks berei is nie; want hierdie dag is apart gestel aan onse Meester. Wees dan nie bedroef nie, want die Blydskap in JaHWeH - sy is julle beskutting.	",
"	12 En die Leviete het die hele volk tot bedaring gebring en gesê: Wees stil! want hierdie dag is apart gestel; wees dus nie bedroef nie.	",
"	13 Toe het die hele volk weggegaan om te eet en te drink en porsies te stuur en groot vreugde te bedrywe; want hulle het ag gegee op die Woorde wat aan hulle bekend gemaak is.	",
"	14 En op die tweede dag het die hoofde van die vaders van die hele volk, die priesters en die Leviete by Ezra, die skrifgeleerde, vergader om naamlik die woorde van die Wet te ondersoek.	",
"	15 Toe vind hulle uit dat in die Wet wat JaHWeH deur die diens van Moshè beveel het, geskrywe was dat die kinders van JisraEl op die Fees in die sewende maand in ‘n takskuiling moes woon,	",
"	16 en dat hulle moes afkondig en rondstuur deur al hulle stede en in Jerusalem om te sê: Trek uit op die gebergte en bring olyftakke en oliewenhouttakke en mirtetakke en palmtakke en takke van digte bome om takskuilings te maak soos geskrywe is.	",
"	17 En die volk het uitgetrek en dit gebring en vir hulle takskuilings gemaak, elkeen op sy dak en op hulle erwe en in die voorhowe van die Huis van die Elohim en op die plein van die Waterpoort en op die plein van die Efraimspoort.	",
"	18 En die hele vergadering wat uit die gevangenskap teruggekom het, het takskuilings gemaak en in die takskuilings gewoon; want van die dae van JeHôWshua af, die seun van Nun, tot op daardie dag het die kinders van JisraEl nie só gedoen nie; en daar was baie groot blydskap.	",
"	19 En hy het dag vir dag, van die eerste dag af tot die laaste dag toe, voorgelees uit die Boekrol van die Wet van die Elohim; en hulle het sewe dae lank Fees gehou en op die agtste dag ’n Feestyd volgens Verordening.	",
"	[Vgl:  1 Ezra 9:38-56]	",
		

]
},
{
book: 'Nehemia',
chapter: '9',
content: [
		
"	1 EN op die vier-en-twintigste dag vanaf hierdie maand het die kinders van JisraEl vergader en gevas in rouklere en met Adamah[adamiet se Aarde] op hulle hoof.	",
"	2 En die saad van JisraEl het hulle geskei van al die seuns van die uitlanders, en hulle het gaan staan en belydenis gedoen van hulle oortredinge en die skandelikheid van hulle vaders.	",
"	3 En hulle het van hulle plek opgestaan, en gedurende ’n vierde deel van die dag gelees uit die Boekrol van die Wet van JaHWeH hulle Elohey, en gedurende ’n vierde deel belydenis gedoen en neergebuig tot JaHWeH hulle Elohey.	",
"	4 En op die verhoog van die Leviete het Jehshua en Bani, KadmiEl, SebanJaH, Bunni, SerébJaH, Bani, Kenáni opgestaan en met ’n groot stem JaHWeH hulle Elohey aangeroep.	",
"	5 En die Leviete Jehshua en KadmiEl, Bani, HasabneJaH, SerébJaH, HodiJaH, SebanJaH, PetagJaH het gesê: Staan op, loof JaHWeH julle Elohey van ewigheid tot in ewigheid! En laat hulle U Glansryke Naam loof wat bo alle lof en prys verhewe is!	",
"	6 U is alleen JaHWeH, U het die Hemele, die hoogste Hemele en al sy leërmagte, gemaak, die Aarde en alles wat op haar is, die seë en alles wat in hom is, en U hou dit alles in die lewe, en die leërmagte van die Hemele buig hulle voor U neer.	",
"	7 Hy [is] JaHWeH, die Elohim van julle, wat Abram uitverkies het en hom uit Ur van die Chaldeërs uitgelei het en sy naam tot Abraham gemaak het.	",
"	8 En U het sy hart getrou bevind voor U Aangesig, en U het met hom die Verbond gesluit om die Aarde te gee van die Kanaäniete, Hetiete, Amoriete en Feresiete en Jebusiete en Girgasiete, om haar aan sy saad te gee; en U het U Woorde vervul, want U is regverdig.	",
"	9 En U het die ellende van ons vaders in Egipte aangesien en hulle geroep by die Skelfsee gehoor,	",
"	10 en U het tekens en wonders gedoen aan Farao en aan al sy dienaars en aan die hele volk van sy Aarde; want U het geweet dat hulle vermetel teen hulle gehandel het, en U het vir U ’n Naam gemaak soos Hy vandag is.	",
"	11 En die see het U voor hulle geklowe, sodat hulle op droë grond dwarsdeur die see getrek het; maar hulle vervolgers het U in die kolke gewerp soos ’n klip in sterk waters.	",
"	12 En U het hulle gelei met die Wolkkolom bedags en met die Vuurkolom snags om die pad vir hulle te verlig waar hulle in haar moes trek.	",
"	13 En op die berg Sinai het U neergedaal en met hulle gespreek uit die Hemele, en U het aan hulle suiwer Reg en Wette van Waarheid, suiwer Insettinge en Gebooie gegee.	",
"	14 En die Sabbat van U Apartheid het U aan hulle bekend gemaak, en Gebooie en Insettinge en ’n Wet deur die diens van U kneg Moshè hulle beveel.	",
"	15 En U het hulle Brood gegee uit die Hemele vir hulle honger en water vir hulle uit die rots laat uitkom vir hulle dors, en aan hulle gesê om die Aarde in besit te gaan neem waaromtrent U U hand opgehef het om hulle haar te gee.	",
"	16 Maar hulle, naamlik ons vaders, het vermetel gehandel en hulle nek verhard en nie na U Gebooie geluister nie;	",
"	17 ja, hulle het geweier om te luister en nie gedink aan U wonders wat U by hulle gedoen het nie; maar hulle het hul nek verhard en in hul wederstrewigheid ’n hoof aangestel om terug te gaan na hulle slawerny. Maar U is ’n Eloah van vergewing, welwillend en barmhartig, stadig om kwaad te word en groot van Medelye, en U het hulle nie verlaat nie.	",
"	18 Selfs toe hulle ’n gegote kalf vir hulle gemaak en gesê het: Dit is jou gode wat jou uit Egipte laat optrek het! - en hulle groot, afskuwelike dinge gedoen het,	",
"	19 het U in U grote Barmhartigheid hulle tog nie verlaat in die wildernis nie; die Wolkkolom het nie bedags van hulle gewyk om hulle op die pad te lei nie, en die Vuurkolom ook nie snags om vlr hulle die pad te verlig waar hulle in haar moes trek nie.	",
"	20 En U Gees van Suiwerheid het U gegee om hulle te onderrig, en U manna het U nie van hulle mond teruggehou nie en aan hulle water gegee vir hulle dors.	",
"	21 En veertig jaar lank het U hulle onderhou in die wildernis; hulle het nie gebrek gehad nie; hulle klere het nie verslyt en hulle voete nie geswel nie.	",
"	22 En U het aan hulle koninkryke en volke gegee en dié volgens [bepaalde] grense verdeel; en hulle het die Aarde van Sihon, ja, die Aarde van die koning van Hesbon, en die Aarde van Og, die koning van Basan, in besit geneem.	",
"	23 En U het hulle kinders vermenigvuldig soos die Sterre aan die Hemele en hulle in die Aarde ingebring waarvan U aan hulle vaders gesê het dat hulle sou ingaan om haar in besit te neem.	",
"	24 En die kinders het ingegaan en die Aarde in besit geneem, en U het die inwoners van die Aarde, die Kanaäniete, voor hulle onderwerp en dié in hulle hand gegee, hulle konings sowel as die volke van die Aarde, om met hulle te handel soos hulle dit goedvind.	",
"	25 En hulle het versterkte stede en vet Adamah[adamiet se Aarde] ingeneem, en huise in besit geneem vol allerhande goeie dinge, uitgekapte putte, Wingerde en Olyfbome en vrugtebome in menigte, en hulle het geëet en versadig en vet geword en weelderig gelewe deur U voortreflike Suiwerheid.	",
"	26 Maar hulle het wederstrewig en rebels geword teen U en U Wet agter hulle rug gewerp; en U profete wat hulle gewaarsku het, om hulle na U terug te bring, het hulle gedood en groot, afskuwelike dinge gedoen.	",
"	27 Daarom het U hulle oorgegee in die hand van hulle teëstanders, dat dié hulle in benoudheid sou bring. Maar wanneer hulle in die tyd van hulle benoudheid U aangeroep het, het U uit die Hemele gehoor en na U grote Barmhartigheid aan hulle verlossers gegee, dat dié hulle uit die hand van hul teëstanders kon verlos.	",
"	28 Maar sodra hulle rus gehad het, het hulle weer besoedel gehandel voor U Aangesig, en U het hulle oorgelewer in die hand van hul vyande, dat dié oor hulle sou heers; as hulle U dan weer aanroep, het U uit die Hemele gehoor en hulle na U Barmhartigheid baie keer gered.	",
"	29 En U het hulle gewaarsku om hulle na U Wet terug te bring, maar hulle het vermetel gehandel en nie geluister na U Gebooie nie, en teen U Regsprake, teen haar het hulle oortree, waarvan geld dat ’n adamiet haar moet doen, dat hy deur haar kan lewe; en hulle het ’n wederstrewige skouer gegee en hulle nek verhard en nie geluister nie.	",
"	30 En U was baie jare lankmoedig oor hulle, en U het hulle gewaarsku deur U Gees, deur middel van U profete; maar hulle het geen gehoor gegee nie. Daarom het U hulle oorgegee in die hand van die volke van die Aarde.	",
"	31 Maar in U grote Barmhartigheid het U hulle nie volkome vernietig en hulle nie verlaat nie, want U is ’n innemende en barmhartige El.	",
"	32 Onse Elohey, groot, dapper en gedugte El, wat die Verbond hou en Medelye het met ons, laat dan nou al die moeilikheid nie gering wees voor U Aangesig nie wat ons, ons konings, ons owerstes en ons priesters en ons profete en ons vaders en U hele volk oorgekom het van die dae van die konings van Assur af tot vandag toe.	",
"	33 Maar U is regverdig in alles wat oor ons gekom het; want U het in Waarheid gehandel, maar ons het besoedeld gehandel;	",
"	34 en ons konings, ons owerstes, ons priesters en ons vaders het U Wet nie volbring en na U Gebooie en U Getuienisse waarmee U hulle gewaarsku het, nie geluister nie.	",
"	35 En hulle het in hul koninkryk en by U groot seën wat U hulle geskenk het, en in die wye en vet Aarde wat U aan hulle oorgegee het, U nie gedien nie en hulle nie van hul besoedelde handelinge bekeer nie.	",
"	36 Ons is vandag slawe, en die Aarde wat U aan ons vaders gegee het om haar vrug en die suiwere van haar te geniet - op haar is ons slawe.	",
"	37 En sy vermeerder haar opbrengs vir die konings wat U oor ons gestel het om ons oortredinge ontwil, en hulle heers oor ons liggame en oor ons vee na hulle vreugde, en ons is in ’n groot benoudheid.	",
		
		
"	38 MAAR op grond van dit alles sluit ons ’n vaste Verbond en beskryf haar; en op die verseëlde stuk het ons owerstes, ons Leviete, ons priesters geteken.	",

]
},
{
book: 'Nehemia',
chapter: '10',
content: [
		
"	1 EN op die verseëlde stukke het geteken: NegemJaH, die goewerneur, die seun van HagalJaH, en SedekiJaH,	",
"	2 SeráJaH, AzarJaH, JirmeJaH,	",
"	3 Pasgur, AmarJaH, MalkiJaH,	",
"	4 Gattush, SebanJaH, Mallug,	",
"	5 Harim, Méremot, ObadJaH,	",
"	6 DaniEl, Ginneton, Barug,	",
"	7 Mesúllam, AbiJaH, Míjamin,	",
"	8 MaäzJaH, Bílgai, ShemaJaH; dit was die priesters.	",
"	9 En die Leviete: Jehshua, die seun van AzanJaH, Bínnuï van die seuns van Henádad, KadmiEl,	",
"	10 en hulle broers: SebanJaH, HodiJaH, Kelíta, PelaJaH, Hanan,	",
"	11 Mika, Rehob, GashabJaH,	",
"	12 Sakkur, SerébJaH, SebanJaH,	",
"	13 HodiJaH, Baní, Beninu.	",
"	14 Die hoofde van die volk: Párhos, Pahat-Moab, Elam, Sattu, Bani,	",
"	15 Bunni, Asgad, Bébai,	",
"	16 Adónia, Bigwai, Adin,	",
"	17 Ater, GizkiJaH, Assur,	",
"	18 HodiJaH, Hasum, Bésai,	",
"	19 Harif, Anatot, Nobai,	",
"	20 Magpías, Mesúllam, Hesir,	",
"	21 MeshezabEl, Sadok, Jáddua,	",
"	22 PelatJaH, Hanan, AnaJaH,	",
"	23 Hoséa, HananJaH, Hassub,	",
"	24 Hallóhes, Pilha, Sobek,	",
"	25 Rehum, Hasábna, MaàseiJâH,	",
"	26 en AgiJaH, Hanan, Anan,	",
"	27 Mallug, Harim, Baäna.	",
"	28 En die res van die volk, die priesters, die Leviete, die poortwagters, die sangers, die tempeldienaars en almal wat hulle afgesonder het van die volke van die Aarde tot die Wet van die Elohim, hulle vroue, hulle seuns en hulle dogters, almal wat enigsins kon verstaan,	",
"	29 het by hulle broers, die vername manne onder hulle, aangesluit, en hulle het onder eed en met beswering hulleself verplig om te wandel in die Wet van die Elohim, wat deur die diens van Moshè, die kneg van die Elohim, gegee is, en om te hou en te doen al die Gebooie van JaHWeH onse Meester, en Sy Regsprake en Sy Insettinge;	",
"	30 verder dat ons ons dogters nie sou gee aan die volke van die Aarde, en hulle dogters nie sou neem vir ons seuns nie;	",
"	31 en as die volke van die Aarde koopware en allerhande soorte koring bring om op die Sabbatdag te verkoop, dat ons niks van hulle sou neem op die Sabbat of op ’n dag van Apartheid nie; en dat ons in die sewende jaar sal los die las van elke hand.	",
"	32 En ons het vir ons die verpligting aangegaan om ons ’n derde van ’n sikkel in die jaar op te lê vir die diens van die Huis van onse Elohey,	",
"	33 vir die toonbrode en die voortdurende spysbydrae en die voortdurende brandoffer, van die Sabbatte, van die vernuwings, vir die Feestye en vir die Aparthede en vir oortreding om vir JisraEl versoening te doen, en vir enige dienswerk in die Huis van onse Elohey.	",
"	34 En ons, die priesters, die Leviete en die volk het die lot gewerp oor die bydrae van die hout, om dit volgens ons families op vasgestelde tye jaar vir jaar te bring na die Huis van onse Elohey om vuur te maak op die altaar van JaHWeH onse Elohey soos geskrywe staan in die Wet;	",
"	35 en om die eerstelinge van ons Adamah [die adamiet se Aarde] en die eerstelinge van allerhande vrugtebome jaar vir jaar in die Huis van JaHWeH te bring;	",
"	36 en om die eersgeborenes van ons seuns en ons vee, soos geskrywe staan in die Wet, en die eersgeborenes van ons grootvee en ons kleinvee te bring in die Huis van onse Elohey vir die priesters wat diens doen in die Huis van onse Elohey;	",
"	37 en dat ons die eerstelinge van ons growwe meel en van ons bydraes en van die vrugte van allerhande bome, van druiwesap en olie, sou bring vir die priesters in die kamers van die Huis van onse Elohey en die tiendes van ons  Adamah [die adamiet se Aarde] vir die Leviete, terwyl hulle, die Leviete, die tiendes sou invorder in al ons landboustede.	",
"	38 En die priester, die seun van Aäron, moet by die Leviete wees as die Leviete die tiendes invorder, en die Leviete moet ’n tiende van die tiendes na die Huis van onse Elohey bring, in die kamers van die skathuis.	",
"	39 Want in die kamers moet die kinders van JisraEl en die kinders van Levi die bydrae van koring, druiwesap en olie bring, omdat die gereedskap van die Apartheidsplek en die diensdoenende priesters en die poortwagters en die sangers daar is; want ons wou die Huis van onse Elohey nie verwaarloos nie.	",

]
},
{
book: 'Nehemia',
chapter: '11',
content: [
		
"	1 EN die owerstes van die volk het in Jerusalem gewoon, maar die res van die volk het die lot gewerp om een uit tien daartoe te bring om in Jerusalem; Stad van die Apartheid te woon, en nege dele in die stede.	",
"	2 En die volk het al die manne geseën wat hulle vrywillig aangebied het om in Jerusalem te woon.	",
"	3 En dit is die hoofde van die provinsie wat in Jerusalem gewoon het. In die stede van JeHûWdah het hulle elkeen in sy besitting in hulle stede gewoon: JisraEliete, die priesters en die Leviete en die tempeldienaars en die kinders van die dienaars van Salomo.	",
"	4 En in Jerusalem het van die kinders van JeHûWdah en van die kinders van Benjamin gewoon. Van die kinders van JeHûWdah: AtaJaH, die seun van UzziJaH, die seun van ZekarJaH, die seun van AmarJaH, die seun van ShafátJaH, die seun van MahalalEl, van die seuns van Peres;	",
"	5 en MaàseiJaH, die seun van Barug, die seun van Kolhóse, die seun van HazaJaH, die seun van AdáJaH, die seun van JôWjarib, die seun van ZekarJaH, die Selaniet.	",
"	6 Al die seuns van Peres wat in Jerusalem gewoon het, was vierhonderd-agt-en-sestig, krygs-manne.	",
"	7 En dit is die kinders van Benjamin: Sallu, die seun van Mesúllam, die seun van JôWed, die seun van PedahJaH, die seun van KoláJaH, die seun van MaàseiJaH, die seun van IthiEl, die seun van JeshaJaH;	",
"	8 en ná hom Gábbai-Sállai, negehonderd-agt-en-twintig.	",
"	9 En JôWEl, die seun van Sigri, was opsigter oor hulle; en JeHûWdah, die seun van Hassénua, was tweede in rang oor die Stad.	",
"	10 Van die priesters: JedaJaH, die seun van JôWjarib, Jagin,	",
"	11 SeráJaH, die seun van GielkiJaH, die seun van Mesúllam, die seun van Sadok, die seun van Mérajot, die seun van Ahítub, die vors van die Huis van die Elohim.	",
"	12 En hulle broers wat die werk verrig het in die Tempel, was agthonderd-twee-en-twintig; en AdáJaH, die seun van Jeróham, die seun van PalalJaH, die seun van Amsi, die seun van ZekarJaH, die seun van Pasgur, die seun van MalkiJaH,	",
"	13 en sy broers, hoofde van die vaders, was tweehonderd-twee-en-veertig; en Amásai, die seun van AzarEl, die seun van Agsai, die seun van Mesíllemot, die seun van Immer,	",
"	14 en hulle broers, dapper dapperes, was honderd-agt-en-twintig, en opsigter oor hulle was ZabdiEl, die seun van Haggedólim.	",
"	15 En van die Leviete: ShemaJaH, die seun van Hassub, die seun van Asríkam, die seun van GashabJaH, die seun van Bunni,	",
"	16 en Sábbetai en JôWzabad, van die hoofde van die Leviete, was oor die buitewerk van die Huis van die Elohim.	",
"	17 En MattánJaH, die seun van Mika, die seun van Sabdi, die seun van Asaf, leier van die lofsang, wat die Loof [Hom] aanhef by die gebed; en BakbukJaH, die tweede in rang onder sy broers; en Abda, die seun van Sámmua, die seun van Galal, die seun van Jedútun.	",
"	18 Al die Leviete in die Stad van die Apartheid was tweehonderd-vier-en tagtig.	",
"	19 En die poortwagters: Akkub, Talmon, en hulle broers wat wag gehou het by die poorte, was honderd-twee-en-sewentig.	",
"	20 En die ander JisraEliete, priesters en Leviete, was in al die stede van JeHûWdah, elkeen in sy erfdeel.	",
"	21 En die tempeldienaars het gewoon op die Heuwel; en Siha en Gispa was oor die tempeldienaars.	",
"	22 En opsigter van die Leviete in Jerusalem was Ussi, die seun van Bani, die seun van GashabJaH, die seun van MattánJaH, die seun van Mika, van die seuns van Asaf, die sangers, vir die werk in die Huis van die Elohim;	",
"	23 want daar was ’n bevel van die koning aangaande hulle: ’n vaste ordening vir die sangers, na die eis van elke dag.	",
"	24 En PetagJaH, die seun van MeshezabEl, van die seuns van Serag, die seun van JeHûWdah, was verteenwoordiger van die koning in enige saak van die volk.	",
"	25 En wat die dorpe in hulle buiteveld betref, van die kinders van JeHûWdah het gewoon in Kirjat-Arba en sy onderhorige plekke, en in Dibon en sy onderhorige plekke, en in JekabtzeEl en sy dorpe,	",
"	26 en in Jehshua en in Moláda en in Bet-Pelet	",
"	27 en in Hasar-Sual en in Berséba en sy onderhorige plekke,	",
"	28 en in Siklag en in Megóna en sy onderhorige plekke,	",
"	29 en in En-Rimmon en in Sorea en in Jarmut,	",
"	30 Sanóag, Adúllam en hulle dorpe, Lagis en sy buiteveld, Aséka en sy onderhorige plekke; en hulle het in laers gestaan van Berséba af tot by die Vallei van Verbranding.	",
"	31 En die kinders van Benjamin: van Geba af in Migmas en Aja en BetEl en sy onderhorige plekke,	",
"	32 Anatot, Nob, AnanJaH,	",
"	33 Hasor, Rama, Gíttaim,	",
"	34 Hadid, Sebóim, Nebállat,	",
"	35 Lod en Ono, die Handwerkersdal.	",
"	36 En van die Leviete het afdelings van JeHûWdah by Benjamin behoort.	",

]
},
{
book: 'Nehemia',
chapter: '12',
content: [
		
"	1 EN dit is die priesters en die Leviete wat saam met Serubbábel, die seun van ShealtiEl, en Jehshua opgetrek het: SeráJaH, JirmeJaH, Ezra,	",
"	2 AmarJaH, Mallug, Gattush,	",
"	3 ShekanJaH, Rehum, Méremot,	",
"	4 Iddo, Gínnetoi, AbiJaH,	",
"	5 Míjamin, MaadJaH, Bilga,	",
"	6 ShemaJaH en JôWjarib, JedaJaH,	",
"	7 Sallu, Amok, GielkiJaH, JedaJaH; dit was die hoofde van die priesters en van hulle broers in die dae van Jehshua.	",
"	8 En die Leviete was: Jehshua, Bínnuï, KadmiEl, SerébJaH, JeHûWdah, MattánJaH wat met sy broers die leiding by die kore gehad het.	",
"	9 En BakbukJaH en Unni, hulle broers, het by die dienste teenoor hulle gestaan.	",
"	10 En Jehshua was die vader van JôWjakim; en JôWjakim was die vader van Éliasib, en El-Jashib die vader van JôWjada,	",
"	11 en JôWjada die vader van JôWnathan, en JôWnathan die vader van Jaddúa.	",
"	12 En in die dae van JôWjakim was die priesters, die hoofde van die vaders: van SeráJaH, Merája; van JirmeJaH, HananJaH;	",
"	13 van Ezra, Mesúllam; van AmarJaH, JeHôWganan;	",
"	14 van Mallugi, JôWnathan; van SebanJaH, JôWsef;	",
"	15 van Harim, Adna; van Mérajot, Hélkai;	",
"	16 van Iddo, ZekarJaH; van Gínneton, Mesúllam;	",
"	17 van AbiJaH, Sigri; van Mínjamin, van MowadJaH, Píltai;	",
"	18 van Bilga, Sámmua; van ShemaJaH, JeHôWnathan;	",
"	19 en van JôWjarib, Máttenai; van JedaJaH, Ussi;	",
"	20 van Sállai, Kállai; van Amok, Heber;	",
"	21 van GielkiJaH, GashabJaH; van JedaJaH, NethanEl.	",
"	22 Wat die Leviete betref - in die dae van El-Jashib, JôWjada en JôWganan en Jaddúa is die hoofde van die vaders opgeskrywe, en die priesters tot aan die regering van Daríus, die Pers.	",
"	23 Die kinders van Levi, die hoofde van die vaders, is opgeskrywe in die Boekrol van die kronieke tot die dae van JôWganan, die seun van El-Jashib.	",
"	24 En die hoofde van die Leviete was: GashabJaH, SerébJaH en Jehshua, KadmiEl, en hulle broers was teenoor hulle om te loof [en] te dank volgens die bevel van Dawid, die man van die Elohim, wag naas wag:	",
"	25 MattánJaH en BakbukJaH, ObadJaH, Mesúllam, Talmon, Akkub was poortwagters wat wag gehou het by die voorraadkamers van die poorte.	",
"	26 Hulle was in die dae van JôWjakim, die seun van Jehshua, die seun van JôWtsadak, en in die dae van NegemJaH, die goewerneur, en van die priester Ezra, die skrifgeleerde.	",
"	27 EN by die inwyding van die muur van Jerusalem is die Leviete uit al hulle woonplekke gesoek, om hulle na Jerusalem te bring ten einde die inwyding te hou met danksegging en met sang - simbale, harpe en siters.	",
"	28 Toe het die seuns van die sangers byeengekom uit die streek rondom Jerusalem sowel as uit die dorpe van die Netofatiete,	",
"	29 en uit Bet-Gilgal en uit die buiteveld van Geba en Asmáwet, want die sangers het vir hulle dorpe rondom Jerusalem gebou.	",
"	30 En die priesters en die Leviete het hulleself gesuiwer , en die volk en die poorte en die muur gesuiwer .	",
"	31 En ek het die owerstes van JeHûWdah bo-op die muur laat klim en twee groot dankseggings[groepe] opgestel en optogte, een na regs bo-op die muur na die Aspoort toe;	",
"	32 en agter hulle aan het geloop: HoshiJaH en die helfte van die owerstes van JeHûWdah,	",
"	33 en AzarJaH, Ezra en Mesúllam,	",
"	34 JeHûWdah en Benjamin en ShemaJaH en JirmeJaH,	",
"	35 en van die seuns van die priesters met trompette, ZekarJaH, die seun van JôWnathan, die seun van ShemaJaH, die seun van MattánJaH, die seun van MikaJaH, die seun van Sakkur, die seun van Asaf,	",
"	36 en sy broers ShemaJaH en AzarEl, Mílalai, Gílalai, Maäi, NethanEl en JeHûWdah, Hanáni, met die musiekinstrumente van Dawid, die man van die Elohim; en Ezra, die skrifgeleerde, voor hulle uit.	",
"	37 En by die Fonteinpoort het hulle, reg voor hulle uit, met die trappe van die Stad van Dawid opgegaan, waar die muur opgaan bo die huis van Dawid, tot by die Waterpoort teen die ooste.	",
"	38 En die tweede [groep] dankbetuigers het in teenoorgestelde rigting getrek, en ek met die helfte van die volk agteraan, bo-op die muur by die Bakoond-toring langs tot by die Breë Muur;	",
"	39 verder by die Efraimspoort langs en die Ou Poort en die Vispoort en die toring GanánEl en die toring Hamméa tot by die Skaapspoort; en hulle het bly staan by die Gevangenispoort.	",
"	40 Toe het die twee [groepe] dankbetuigers in die Huis van die Elohim gaan staan, en ek en die helfte van die leiers met my saam;	",
"	41 en die priesters El-Jakim, MaàseiJâH, Mínjamin, MikaJaH, ElJôWeynay, ZekarJaH, GanánJaHmet trompette,	",
"	42 en MaàseiJâH en ShemaJaH en El-Azar en Ussi en JeHôWganan en MalkiJaH en Elam en Eser. En die sangers het hulle laat hoor, en JizragJaH was die leier.	",
"	43 En op dié dag het hulle baie slagdiere geslag en was vrolik; want die Elohim het hulle groot Vreugde verskaf, en ook die vroue en kinders was vrolik, sodat die Vreugde van Jerusalem tot ver weg gehoor is.	",
"	44 EN op dié dag is manne aangestel oor die kamers vir die voorrade, die bydraes, die eerstelinge en die tiendes, om daarin die wetlike bydraes volgens die landerye van die stede vir die priesters en die Leviete te versamel; want JeHûWdah was bly oor die priesters en die Leviete wat in die diens gestaan het.	",
"	45 En hulle het die Ordening van hulle Elohey en die ordening van die suiwering onderhou; ook die sangers en die poortwagters, volgens die bevel van Dawid [en] sy seun Salomo.	",
"	46 Want in die dae van Dawid en Asaf, van die voortyd af, lê die oorsprong van die sangers en [leiers van] die lofsang en die danksegging aan Elohim.	",
"	47 En die hele JisraEl het in die dae van Serubbábel en in die dae van NegemJaH die aandele van die sangers en van die poortwagters gegee, na die eis van elke dag; en hulle het die apartgesteldes afgegee aan die Leviete, en die Leviete het die apartgesteldes afgegee aan die seuns van Aäron.	",

]
},
{
book: 'Nehemia',
chapter: '13',
content: [
		
"	1 OP dié dag is daar voor die ore van die volk voorgelees uit die Boekrol van Moshè, en daarin het geskrywe gestaan dat geen Ammoniet of Moabiet tot in ewigheid in die vergadering van die Elohim mag kom nie,	",
"	2 omdat hulle die kinders van JisraEl nie teëgekom het met brood en water nie, en Bíleam teen hulle gehuur het om hulle te vervloek; maar onse Elohey het die vloek in ’n seën verander.	",
"	3 En toe hulle die Wet hoor, het hulle al die mense van gemengde bloed uit JisraEl afgesonder. [Exodus 20:14]	",
"	4 Maar tevore het El-Jashib, die priester wat oor die kamers van die Huis van onse Elohey aangestel was, ’n verwant van TobiJaH,	",
"	5 vir hom ’n groot kamer ingerig waar hulle vroeër die spysbydrae, die wierook en die gereedskap en die tiendes van koring, druiwesap en olie, die bydrae volgens die Wet vir die Leviete en die sangers en die poortwagters, en die bydrae aan die priesters neergesit het.	",
"	6 Maar gedurende dit alles was ek nie in Jerusalem nie; want in die twee-en-dertigste jaar van Artasásta, die koning van Babel, het ek by die koning gekom; en ná verloop van tyd het ek verlof gevra van die koning	",
"	7 en na Jerusalem gekom. Toe het ek die kwaad opgemerk wat El-Jashib gedoen het deur vir TobiJaH ’n kamer in die voorhowe van die Huis die van Elohim in te rig.	",
"	8 En ek was erg ontstemd, sodat ek al die huisraad van TobiJaH uit die kamer buitentoe gegooi het,	",
"	9 met die bevel dat hulle die kamers moes suiwer; en ek het die stukke gereedskap van die Huis van die Elohim, die spysbydrae en die wierook daarin teruggebring.	",
"	10 Ook het ek verneem dat die aandele van die Leviete nie gegee is nie, sodat die Leviete en die sangers wat die dienswerk moes verrig, elkeen na sy landerye gevlug het.	",
"	11 En ek het met die leiers getwis en gesê: Waarom is die Huis van die Elohim in verwaarlosing? En ek het hulle bymekaar laat kom en hulle weer op hulle pos aangestel.	",
"	12 En die hele JeHûWdah het die tiendes van koring en druiwesap en olie na die voorraadkamers gebring.	",
"	13 En oor die voorraadkamers het ek SelemJaH, die priester, en Sadok, die skrywer, en PedahJaH, uit die Leviete, as skatmeesters aangestel; en as hulp vir hulle: Hanan, die seun van Sakkur, die seun van MattánJaH, omdat hulle vertroubaar geag is; en hulle moes aan hulle broers uitdeel.	",
"	14 Dink hierom aan my, my Elohey, en delg tog my dade van Medelye nie uit wat ek aan die Huis van my Elohey en aan die instellinge daarvan bewys het nie.	",
"	15 In dié dae het ek in JeHûWdah parskuipe gesien wat op die Sabbat getrap word – vragte koring wat op esels gelaai en ingebring word, en ook wyn, druiwe en vye en allerhande vragte, en dit is op die Sabbatdag in Jerusalem ingebring; en ek het teen hulle geprotesteer op die dag toe hulle wildsvleis verkoop het.	",
"	16 Ook die Tiriërs wat in haar gewoon het, het vis en allerhande koopware ingebring en op die Sabbat aan die kinders van JeHûWdah selfs in Jerusalem verkoop.	",
"	17 En ek het met die edeles van JeHûWdah getwis en vir hulle gesê: Watter besoedelde ding is dit wat julle doen, dat julle die Sabbatdag besoedel het?	",
"	18 Het julle vaders nie so gehandel, sodat onse Elohey oor ons en oor hierdie Stad al hierdie rampe gebring het nie? Ja, julle vermeerder die brandende Woede oor JisraEl deur die Sabbat te besoedel!	",
"	19 En sodra dit in die Poorte van Jerusalem voor die Sabbat donker was, het ek gesê dat die deure gesluit moes word; en ek het gesê dat hulle dit nie mag oopmaak tot na die Sabbat nie, en van my kinders het ek by die Poorte aangestel: geen vrag mag op die Sabbatdag inkom nie.	",
"	20 Toe het die koopmans en handelaars in allerhande koopware ’n paar keer buitekant Jerusalem vernag.	",
"	21 Maar ek het hulle gewaarsku en vir hulle gesê: Waarom vernag julle voor die muur? As julle dit weer doen, sal ek die hand aan julle slaan. Van dié tyd af het hulle nie meer op die Sabbat gekom nie.	",
"	22 Verder het ek aan die Leviete gesê dat hulle hul moes suiwer en die Poorte kom bewaak om die Sabbatdag apart te stel. Dink ook hierom aan my, my Elohey, en ontferm U oor my na die grootheid van U Medelye.	",
"	23 In dié dae het ek ook manne van JeHûWdah gesien wat Asdodiese, Ammonitiese, Moabitiese vroue getrou het.	",
"	24 En van hulle kinders het die helfte Asdodies gepraat, of die taal van watter volk ook al; maar hulle kon geen Hebreeus praat nie.	",
"	25 Daarom het ek met hulle getwis en hulle gevloek, en sommige van hulle geslaan en die hare uitgepluk en hulle by Elohim besweer: Julle mag julle dogters nie aan hulle seuns gee, en julle mag nie van hulle dogters vir julle seuns of vir julleself neem nie!	",
"	26 Het Salomo, die koning van JisraEl, nie deur hulle oortree nie? Alhoewel daar onder baie nasies nie ’n koning gewees het soos hy nie en hy ’n liefling van sy Elohey was, sodat Elohim hom as koning aangestel het oor die hele JisraEl, het die uitlandse vroue hom tog laat oortree.	",
"	27 Moet ons nou van julle hoor dat julle hierdie menigte besoedelde dade pleeg, om te oortree teen onse Elohey deur bastervroue te trou?	",
"	28 En een van die seuns van JôWjada, die seun van die hoëpriester El-Jashib, was ’n skoonseun van Sanballat, die Horoniet; daarom het ek hom van my af weggejaag.	",
"	29 Dink aan hulle, my Elohey, oor die verswarting van die priesterskap en van die Verbond met die priesterskap en met die Leviete.	",
"	30 So het ek hulle dan gesuiwer van al wat baster was, en die diensordeninge vir die priesters en die Leviete vasgestel vir elkeen in sy werk,	",
"	31 ook vir die bydrae van die hout op vasgestelde tye en vir die eerstelinge. Dink aan my, my Elohey, aan my suiwer dade!	",

]
}
];
