const openbaring_van_henogChapters = [

{
book: 'Openbaring_Van_Henog',
chapter: '1',
content: [
		
"	1 EK het aan hulle gesê: Kyk, my kinders, ek weet nie waarheen ek gaan nie of wat van my sal word nie;	",
"	2 En nou, daarom, my kinders, moenie julle van Elohim wegkeer nie, maar leef julle lewens voor die Aangesig van JaHWeH, en hou Sy Insettinge;	",
"	3 en moenie die bydrae van vergoeding weier nie, en JaHWeH sal nie die werke van jou hande weier nie;	",
"	4 moenie die gawes van JaHWeH weier nie, en JaHWeH sal [jou] nie Sy besittings in jou stoorkamers weier nie;	",
"	5 seën JaHWeH met die eerstelinge onder jou vee en jy sal die geseënde van JaHWeH genoem word vir ewig;	",
"	6 moet julle nie wegkeer van JaHWeH nie, moet ook nie gode aanbid wat nie die Hemele of die Aarde gemaak het nie: mag JaHWeH in julle harte Vrees vir Hom bevestig.	",
"	7 En nou, my kinders, laat niemand na my soek totdat JaHWeH my na julle laat terugkeer nie.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '2',
content: [
		
"	1 NADAT ek met my seuns gepraat het, het die twee Manne my geroep en my op hulle Vleuels geneem; en hulle het my tot in die eerste Hemele gedra en daar neergesit. En hulle het my voor die oudstes gebring, die Vorste van die leërmagte van die Sterre, en hulle het my hul bewegings en hul verplasings van jaar tot jaar getoon.	",
"	2 Hulle het aan my tweehonderd Boodskappers gewys wat die Sterre en die sterrestelsels in die Hemele beheer.	",
"	3 En hulle het aan my ‘n see gewys, baie groot, baie groter as die aardse see; en die Boodskappers het met hulle Vleuels gevlieg.	",
"	4 En hulle het aan my die skatkamers van die sneeu en ys getoon en die skrikwekkende Boodskappers wat die skatte beheer, en hulle het aan my die stoorkamers van die wolke gewys, waaruit hulle kom, en waarheen hulle terugkeer.	",
"	5 Hulle het aan my die skatkamers van die Dou getoon, die voorkoms daarvan was soos olie van die Olyfbome; en ook die Boodskappers wat hulle skatte bewaak het, en hulle bedekking was soos al die blomme van die Aarde.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '3',
content: [
		
"	1 DAARDIE Manne het my toe geneem en boontoe gelei na die tweede Hemele.	",
"	2 En hulle het aan my die bewaakte gevangenes gewys van die onmeetbare oordeel, en daar het ek die boodskappers gesien wat verdoem was; en ook het hulle aan my ‘n duisternis getoon wat groter was as die aardse duisternis ... en hierdie boodskappers was swart van aange-sig, meer as die aardse donkerte, en hulle het deur al die ure aanhoudend geween.	",
"	3 En ek het aan die Manne wat met my was, gesê: Hoekom word hulle so gefolter?	",
"	4 Die Manne het my geantwoord: Hulle is diegene wat JaHWeH versaak het, wat nie JaHWeH se bevele gehoorsaam het nie, maar wat gehandel het volgens hulle eie wil en afgedwaal het met hulle prins, wat ook vasgebind is in die vyfde Hemele.	",
"	5 En ek het ‘n groot deernis vir hulle gevoel en daardie boodskappers het laag voor my gebuig: Man van Elohim, ons vra jou dat jy tot JaHWeH vir ons sal bid;	",
"	6 en ek het hulle geantwoord en gesê: Wie is ek, ‘n sterflike adamiet, dat ek vir boodskappers moet bid? Wie weet waarheen ek sal gaan en wat met my sal gebeur? Of wie vir my sal bid?	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '4',
content: [
		
"	1 DAARDIE Manne het my toe geneem en boontoe gelei na die tweede Hemele.	",
"	2 En hulle het aan my die bewaakte gevangenes gewys van die onmeetbare oordeel, en daar het ek die boodskappers gesien wat verdoem was; en ook het hulle aan my ‘n duisternis getoon wat groter was as die aardse duisternis ... en hierdie boodskappers was swart van aange-sig, meer as die aardse donkerte, en hulle het deur al die ure aanhoudend geween.	",
"	3 En ek het aan die Manne wat met my was, gesê: Hoekom word hulle so gefolter?	",
"	4 Die Manne het my geantwoord: Hulle is diegene wat JaHWeH versaak het, wat nie JaHWeH se bevele gehoorsaam het nie, maar wat gehandel het volgens hulle eie wil en afgedwaal het met hulle prins, wat ook vasgebind is in die vyfde Hemele.	",
"	5 En ek het ‘n groot deernis vir hulle gevoel en daardie boodskappers het laag voor my gebuig: Man van Elohim, ons vra jou dat jy tot JaHWeH vir ons sal bid;	",
"	6 en ek het hulle geantwoord en gesê: Wie is ek, ‘n sterflike adamiet, dat ek vir boodskappers moet bid? Wie weet waarheen ek sal gaan en wat met my sal gebeur? Of wie vir my sal bid?	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '5',
content: [
		
"	1 EN die Manne het my daarvandaan weggeneem, en het my boontoe gelei na die derde Hemele en my daar in die middel van die Paradys neergesit;	",
"	2 en daardie plek was mooier as enigiets wat daar te sien is - al die bome het gebot, al die vrugte was ryp, elke soort voedsel was altyd in oorvloed, elke briesie welriekend.	",
"	3 En daar was vier riviere wat in stille gang verbygevloei het. Die hele Tuin was suiwer, en het voortgebring wat suiwer is om te eet.	",
"	4 En die Boom van die Lewe was in daardie plek waar JaHWeH rus wanneer Hy na die Paradys gaan; en die kwaliteit van die geur van daardie Boom was onbeskryflik - en Sy was meer as ‘n sieraad vir alle bestaande dinge; en van alle kante het Sy in voorkoms gelyk soos goud en skarlakenrooi en soos vuur, en Sy het alles bedek, en alle soorte vrugte geproduseer. Haar wortel is in die Tuin aan die Einde van die Aarde. En die Paradys is tussen bedorwenheid en onbedorwenheid. En daar is twee Fonteine waaruit heuning en melk voortkom, en hulle Fonteine bring wyn en olie voort, en hulle verdeel in vier dele en gaan op ‘n stille koers, en gaan af in die Paradys van Eden tussen bedorwenheid en onbedorwenheid. En vandaar gaan hulle met die Aarde langs voort en het ‘n ommekeer in hulle kringloop soos die ander elemente. Daar is driehonderd Boodskappers wat die Tuin in stand hou en met voortdurende soet gesang en met nimmerswyende stemme Elohim dien dwarsdeur al die dae en ure.	",
"	5 Daar is nog ‘n Boom daar naby, ‘n Olyfboom, wat onophoudelik met olie vloei.	",
"	6 En elke Boom is oortrek met suiwer vrugte, daar is nie ‘n Boom sonder vrugte nie; en die hele plek is geseënd.	",
"	7 En die Boodskappers wat die Paradys bewaak, is die mees wonderbaarlikes en hulle dien Elohim sonder ophou met ononderbroke stem en soet gesang.	",
"	8 En ek het gesê: Hoe geseënd is hierdie plek nie! Die Manne het my geantwoord: Hierdie plek, Henog, word voorberei vir die regverdiges wat in hul lewes swaarkry moes verduur,	",
"	9 wat hulleself kasty en hul oë afgewend het van Ongeregtigheid en ware regverdige oordeel gespreek het, en wat brood gegee het aan die verhongerdes, en die naaktes met klere bedek het,	",
"	10 wat die struikelendes orent gehelp het, en diegene behulpsaam was teenoor wie onreg gedoen is, wat hul lewes voor die Aangesig van JaHWeH geleef en Hom alleen gedien het.	",
"	11 Vir hulle word hierdie plek toeberei as hulle ewige Erfdeel.	",
		

		
"	12 EN daardie twee Manne het my van daar af boontoe gelei na die Noordekant van die Hemele en het aan my ‘n verskriklike plek gewys.	",
"	13 Elke soort marteling en kastyding was in daardie plek, en duisternis en mis, maar ‘n somber vuur het ewigdurend opgevlam in daardie plek,	",
"	14 en ‘n brandende rivier het uitgekom teen die hele plek. En daar was koue en ys en tronke in daardie plek, en verskriklike en wrede boodskappers wat wapens dra en kasty sonder Barmhartigheid.	",
"	15 En ek het gesê: Hoe verskriklik is hierdie plek. En die Manne het my geantwoord: [Openbaring van Petrus 1]	",
"	16 Hierdie plek, Henog, word voorberei vir die wetteloses wat op Aarde wetteloos gehandel het - wat op Aarde oortree het teen die natuur en wat kinders verdorwe het met sodomie;	",
"	17 wat dwelmhandel en besweringe bedryf het en oor hulle besoedelde dade spog, wat gesteel het en die siele van adamiete deur geheimenisse berowe, [Openbaring 22:15]	",
"	18 wat die juk wat hulle bind, losgemaak het, en wat hulself deur Ongeregtigheid verryk het uit ander se besittings,	",
"	19 en wat die honger man gelaat het om te sterf van honger terwyl hulle aan hom kon gee om te eet, wat die naakte gestroop het terwyl hulle hom kon klee,	",
"	20 wat nie hul Skepper erken het nie, maar gode aanbid en afbeeldings gemaak het, en hulle neergebuig het voor die werke van hul eie hande.	",
"	21 Vir hulle almal is hierdie plek voorberei as ‘n ewige Erfdeel.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '6',
content: [

"	1 DIE Manne het my boontoe gelei en na die vierde Hemele gedra. En kyk, hulle het my al die bewegings gewys en al die strale van die lig van die son en die maan.	",
"	2 En ek het hulle gange gemeet en dit met hulle lig vergelyk en gesien dat die son se lig sewe maal sterker is as die van die maan.	",
"	3 Sy wentelbaan en die strydwa waarop dit reis, is soos ’n Gees in beweging; en daar is vir hulle geen rus terwyl hulle met die dag uitgaan en met die nag terugkeer nie.	",
"	4 En ek het vier groot Sterre aan die regterkant van die son se strydwa en vier aan die linkerkant sien hang wat vir ewig met die son saamgaan.	",
"	5 En ek het Boodskappers voor die son se strydwa sien gaan, vlieënde Wesens: elke Boodskapper wat die son se strydwa trek, het twaalf Vleuels, en wanneer JaHWeH hulle beveel om af te gaan Aarde toe, dra hulle ook die dou en die hitte met die son se strale. Ek het baie Sterre gesien, en elke Ster het onder hom ‘n duisend Sterre na die regterkant van die son se wiel gehad. Daar was vier Sterre na die linkerkant, elkeen met ‘n duisend Sterre onder hom, altesaam agtduisend wat deurentyd met die son saamgaan. Gedurende die dag sien vyftien menigtes van Boodskappers daarna om, en ‘n duisend gedurende die nag. En sesgevlerktes (Serafs) stroom uit saam met die Boodskappers voor die strydwa van die son in die vurige vlamme, en ‘n honderd Boodskappers steek die son aan die brand. Ek het gekyk en ander vlieënde elemente van die son gesien, wie se name was Fenikses en Galkydri, wonderbaarlik en wonderlik, met voete en sterte in die vorm van ‘n leeu en ‘n krokodil se kop; hulle voorkoms was verpurper soos die reënboog; hulle grootte is negehonderd mate, hul Vleuels is soos die van die Boodskappers, elkeen het twaalf en hulle bedien en begelei die son, en verdra die hitte en die dou soos dit deur Elohim beveel is. So draai die son en gaan en reis onder die Hemele deur en sy baan gaan onder die Aarde met die lig van sy strale nimmereindigend.	",
"	6 EN die Manne het my na die ooste van die Hemele geneem.	",
"	7 Hulle het my die poorte gewys waardeur die son uitgaan volgens die aangewese tyd en volgens die kringloop van die maande van die hele jaar, en die verkorting en verlenging van die dae en van die nagte.	",
"	8 Hulle het aan my gewys ses poorte, een geopen op ‘n afstand van dertig stadia; en ek het hulle grootte probeer meet, maar ek kon nie - en elke poort het een-en-sestig stadia en ‘n kwart van ‘n stadium, en ek het hulle suiwer gemeet en verstaan dat hulle mate soveel is;	",
"	9 deur hulle het die son ingegaan en na die weste beweeg. Deur die eerste poort het hy twee-en-veertig dae gegaan,	",
"	10 deur die tweede vyf-en-dertig dae, deur die derde vyf-en-dertig dae, deur die vierde vyf-en-dertig dae, deur die vyfde vyf-en-dertig dae, en deur die sesde twee-en-veertig dae.	",
"	11 En weer, terugkerend deur die sesde poort volgens die kringloop van die seisoene het hy deur die vyfde poort ingegaan, vyf-en-dertig dae,	",
"	12 deur die vierde poort vyf-en-dertig dae, vyf-en-dertig dae deur die derde poort, vyf-en-dertig dae deur die tweede poort.	",
"	13 En die dae van die jaar word beëindig volgens die kringloop van die seisoene.	",
"	14 En die Manne het my boontoe gelei na die weste van die Hemele, en aan my die ses groot poorte gewys wat oop was soos die oostelike poorte aan die teenoorgestelde kant waar die son sak, volgens die getal van die dae.	",
"	13 So gaan hy weer onder deur die westelike poorte - en die skittering van sy kroon is by JaHWeH in die Hemele en word bewaak deur vierhonderd Boodskappers, terwyl die son omwentel op sy wiel onder die Aarde, en hy sewe groot ure in die nag staan; die helfte van sy omwenteling spandeer hy onder die Aarde. Wanneer hy die ooste nader in die agste uur van die nag, bring hy sy ligte en die kroon van sy skittering, en die son vlam voort meer as vuur.	",
"	14 Wanneer hy weer by die westelike poorte uitkom, neem vier Boodskappers sy kroon en dra dit op na JaHWeH.	",
"	17 Maar die son draai sy strydwa en gaan voort sonder lig; en daar sit hulle die kroon op hom.	",
"	18 Hulle het aan my die getal van die son en die poorte waardeur hy in en uitgaan gewys; want hierdie poorte het JaHWeH gemaak en Hy het die son aangewys as die uurwagter van die jaar. Toe het die elemente van die son wat genoem word Fenikses en Galkydri aan die sing gegaan, daarop het elke vlieënde wese met sy Vleuels gefladder, verbly in die Gewer van Lig, en op die bevel van JaHWeH het hulle ‘n lied aangehef.	",
"	19 Van die maan het hulle my ‘n ander getal gewys: Hulle het my al haar bewegings en al haar kringlope en haar poorte laat sien.	",
"	10 Hulle het my die twaalf poorte na die ooste gewys: hulle het my die poorte van die kroon gewys waardeur die maan in en uitgaan volgens die gebruiklike tye.	",
"	21 Deur die eerste poort na die ooste een-en-dertig dae, deur die tweede een-en-dertig dae, en deur die derde een-en-dertig dae uitsonderlik,	",
"	22 en deur die vierde dertig dae, deur die vyfde een-en-dertig dae, ongewoon, en deur die sesde een-en-dertig dae gewis,	",
"	23 deur die sewende dertig dae, deur die agste een-en-dertig dae uitsonderlik, en deur die negende dertig dae presies, en deur die tiende dertig dae verseker,	",
"	24 deur die elfde een-en-dertig dae, deur die twaalfde poort gaan sy in twee-en-twintig dae.	",
"	25 En so ook deur die westelike poorte volgens die siklus en getal van die oostelike poorte; so gaan sy ook deur die westelike poorte in en sy voltooi die jaar met driehonderd-vier-en-sestig dae.	",
"	26 Sy gaan die jaar in met vier uitsonderlike kwart dae en om hierdie rede word hulle uitgehou en eenkant gesit, weg van die Hemele en die jaar en word nie getel in die getal van die dae nie;	",
"	27 want hulle verander die seisoene van die jaar, twee nuwe mane wanneer sy groei en ‘n tweede twee nuwe mane wanneer sy afneem.	",
"	28 Wanneer sy klaar is by die westelike poorte, dan keer sy terug en gaan na die ooste met haar lig: en so beweeg sy dag en nag in ‘n sirkel.	",
"	29 Haar wentelbaan is soos die lug: en die strydwa waarop sy ry is ‘n Gees in beweging, en die wat haar strydwa trek, is vlieënde Wesens, elke Boodskapper het ses Vleuels. Dit is die getal van die maan.	",
"	23 In die middel van die Hemele het ek ‘n gewapende Vors gesien wat JaHWeH dien op simbale en blaasinstrumente en met ‘n onophoudelike stem: en ek was betower terwyl ek daarna kyk.	",
]
},
{
book: 'Openbaring_Van_Henog',
chapter: '7',
content: [
		
"	1 Die Manne het my vandaar geneem en opgedra na die vyfde Hemele. En ek het daar ‘n enorme Leërskare gesien - die Wagters.	",
"	2 Hulle voorkoms was soos die adamiet se voorkoms: in grootte was hulle groter as die groot reuse wat genoem is Grigori.	",
"	3 En hulle aangesigte was treurig en hulle monde was stil en daar was geen diens in die vyfde Hemele nie.	",
"	4 En ek het aan die Manne wat by my was gesê: Waarom is hulle so baie bedroef en hul aangesigte so treurig, en hul monde stil, en waarom is daar geen diens in hierdie Hemele nie?	",
"	5 Hulle het aan my gesê: Hierdie is die Wagters wat nie by hulle broers aangesluit het nie.	",
"	6 Twee prinse en die tweehonderd ander wat hulle gevolg en afgegaan het na die Aarde en hulle eed op die skouer van die berg Hermon verbreek het om hulleself nie met die adamiet se vroue te besoedel nie;	",
"	7 en omdat hulle hulself besoedel het, het JaHWeH hulle verdoem. Hulle het die Aarde besoedel met hul dade, in al hul dae was hulle wetteloos en het vermeng, en reuse is gebore en wonderbaarlike groot manne en groot vyandskap. En hierdie [groep] treur oor hul broers en die straf wat op hulle gelê is.	",
"	8 Ek het aan die Wagters gesê: Ek het julle broers gesien en ek het gehoor wat hulle gedoen het: en ek ken hulle gebede en ek het vir hulle gebid.	",
"	9 En kyk, JaHWeH het hulle verdoem onder die Aarde totdat die Hemele en die Aarde verbygegaan het: waarom wag julle dan vir julle broers, en waarom dien julle nie voor die Aangesig van JaHWeH nie?	",
"	10 Hervat julle vorige pligte: bied julle dienste aan in die Naam van JaHWeH, ingeval julle JaHWeH, onse Elohey vertoorn en Hy julle neerwerp uit hierdie plek.	",
"	11 Hulle het geluister na wat ek gesê het en is oorreed en hulle het in vier rye in die Hemele gestaan.	",
"	12 En kyk, terwyl ek daar staan, het hulle saam op vier trompette begin blaas, en die Wagters het begin dien, asof met ‘n enkele stem en hulle stem het opgegaan voor die Aangesig van JaHWeH.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '8',
content: [
	
"	1 DIE Manne het my vandaar boontoe gelei en my gedra na die sesde Hemele.	",
"	2 Ek het daar sewe Boodskappers in ‘n groep gesien, helder en baie glorieryk en hulle Aangesigte het geskyn soos ‘n straal van die son.	",
"	3 Daar was geen verskil in hulle Aangesigte nie, of in hulle grootte of in hulle klere nie; hulle het die verordeninge van die wêreld gereël en daaroor onderrig;	",
"	4 ook die beweging van die Sterre, die son, die maan en die Boodskappers [hul gidse] en die hemelse roepstemme - hulle wat harmonie aan alle lewe in die Hemele gee.	",
"	5 En hulle het die uitvoering van die sang en aanbiedinge, lofprysinge en glansrykheid gereël en georden:	",
"	6 die van die Boodskappers wat oor die seisoene en die jare aangestel is, en die Boodskappers wat oor die riviere en die see is, en die Boodskappers wat oor die vrugte en gras en alles wat groei, is, en die Boodskappers van al die nasies.	",
"	7 Hulle is die draers van gesag en skryf neer al die dade van die lewende dinge voor die Aangesig van JaHWeH.	",
"	8 Tussen hulle is sewe Fenikse en sewe Gérubs en sewe Serafs wat in eenheid saampraat en saamsing: en dit is onmoontlik om hulle sang te beskryf. En JaHWeH het Hom in Sy Voetbank verbly. [1 Kronieke 28:2; Klaagliedere 2:1; 2; 2 Ezra 6:4 ]	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '9',
content: [
		
"	1 DIE Manne het my opgetel vandaar en my tot in die sewende Hemele gedra.	",
"	2 Ek het daar ‘n baie groot Lig gesien, en vurige vorste van die geestelike magte, die Hoof-boodskappers, die Boodskappers en die helderheid van die Ofaniem; daar was Gérubs en Serafs, trone en veelogiges, nege regimente, die vestings van Lig, en ek het bang geword en van groot angs begin bewe.	",
"	3 Die Manne het my in hulle midde geneem en aan my gesê: Wees dapper, Henog, moenie bevrees wees nie, en hulle het JaHWeH van ver af aan my gewys waar Hy op Sy troon sit:	",
"	4 en die hemelse Skeppingsleërmag, gegroepeer volgens hulle rang, het na vore gekom en JaHWeH gedien, en hulle het weer omgedraai en na hulle plekke gegaan met Vreugde en Blydskap en in onmeetbare Lig.	",
"	5 Daar was die Glansrykes wat Hom in die nag gedien het en nie bedags weggegaan het nie, en voor die Aangesig van JaHWeH gestaan het en Sy wil gedoen het.	",
"	6 Al die vorste van die Gérubs en die Serafs was rondom die Troon en het nie daarvandaan weggegaan nie, en die Serafs het Sy hele Troon oordek terwyl hulle voor die Aangesig van JaHWeH gesing het: Apartgestel, apartgestel, apartgestel is JaHWeH Elohim van die Skeppingsleërmagte; die Hemele en Aarde is gevul met U Glansrykheid. [Boekrol van Henog 39:12; JeshaJaH 6:2; Openbaring 4:8]	",
"	7 En toe ek al hierdie dinge sien, het daardie Manne van my weggegaan en daarop het ek hulle nie meer gesien nie.	",
"	8 Hulle het my alleen aan die einde van die [sewende] Hemele gelaat en ek het bang geword en op my aangesig neergeval.	",
"	9 En JaHWeH het een van Sy Glansrykes na my gestuur, die Hoof-boodskapper GabriEl, en hy het aan my gesê: Wees dapper, Henog, moenie bevrees wees nie, staan op en kom saam met my en staan voor die Aangesig van JaHWeH vir ewig.	",
"	10 En ek het hom geantwoord en gesê: Helaas, my meester, ek is verlam van angs. Roep na my die Manne wat my na hierdie plek gebring het, want ek het vertroue in hulle en saam met hulle sal ek JaHWeH se Teenwoordigheid betree.	",
"	11 En GabriEl het my gevang soos ‘n blaar deur die wind gevang word, en hy het my meegevoer en voor die Aangesig van JaHWeH neergeplaas. En ek het die agtste Hemele gesien wat in die Hebreeuse taal, Musalot genoem word, die herskepper van seisoene, droogte en nattigheid, en van die twaalf tekens van die diereriem wat bo die sewende Hemele is. En ek het die negende Hemele gesien wat in Hebreeus genoem word Kuchavim, waar die hemelse tuistes is van die twaalf tekens van die diereriem.	",
"	12 En in die tiende Hemele het ek JaHWeH gesien, Sy gelaat Magtig en buitengewoon Glansryk en Ontsagwekkend - soos yster wat in die vuur gloei en vonke afgee as dit uitgehaal word en brand	",
"	13 Wie is ek om die voorkoms van Sy Wese te beskryf en die Aangesig van JaHWeH, Magtig en baie, baie Ontsagwekkend, en Sy veelogiges en veelstemmige koor en die ontsaglike Troon van JaHWeH, gemaak sonder hande?	",
"	14 Of die geselskap wat daarom heen vergader is [die leërmagte van Gérubs en Serafs], of die onveranderlike, onuitspreeklike, nimmerswyende en glansryke diens wat aan Hom gewy word?	",
"	15 En ek het op my aangesig neergeval en Hom vereer.	",
"	16 En JaHWeH het my met Sy eie Mond geroep: Wees dapper, Henog, moenie bevrees wees nie, staan op en staan voor My Aangesig tot in die ewigheid.	",
"	17 En JaHWeH se groot Hoofbood-skapper, MíkaEl, het my opgelig en voor die Aangesig van JaHWeH ingebring.	",
"	18 JaHWeH het Sy diensknegte op die proef gestel en aan hulle gesê: Laat Henog voor My staan tot in ewigheid.	",
"	19 En die Glansrykes het voor die Aangesig van JaHWeH neergebuig en gesê: Laat hom opkom.	",
"	20 En JaHWeH het aan MíkaEl gesê: Neem Henog en verwyder sy aardse kledingstukke en salf hom met My suiwer olie en klee hom in glansryke kledingstukke.	",
"	21 MíkaEl het my klere uitgetrek en my gesalf met suiwer olie.	",
"	22 En die voorkoms van die salf was meer glansend as ‘n groot lig en die rykheid daarvan soos soet Dou, en die geur soos mirre, blinkend soos ‘n straal van die son.	",
"	23 Ek het na myself gekyk en ek was soos een van die Glansrykes, en daar was geen opvallende verskil nie.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '10',
content: [
		
"	1 EN JaHWeH het FrewiEl ontbied, een van die Hoof-boodskappers wat wys was en wat al die dade van JaHWeH neergeskryf het; en JaHWeH het aan FrewiEl gesê:	",
"	2 Neem die Boekrolle uit hulle bergplek en gee aan Henog ‘n pen en dikteer die Boekrolle aan hom.	",
"	3 En FrewiEl het gou gemaak en die Boekrolle gebring, helder met smirnioot, en hy het my ‘n pen uit sy eie hand gegee.	",
"	4 Hy het my alles vertel wat gebeur het in die Hemele en op die Aarde, en onder die see, en die bewegings en bane van al die elemente,	",
"	5 en al die veranderinge van die jare, en die bewegings en mutasies van die dae, en die beheer en volgorde en uitvoering van die sang, en die ingaan van die wolke en die opkom van die winde, en al die woorde van die liedere van die gewapende Skeppingsleërmagte. En dit was alles gepas dat ek dit moet leer.	",
"	6 FrewiEl het alles aan my in dertig dae en dertig nagte verduidelik. Sy lippe was nooit stil soos hy aangehou het met praat nie;	",
"	7 en ek, vir my aandeel, het geen rus gehad vir dertig dae en dertig nagte terwyl ek my aantekeninge gemaak het nie.	",
"	8 En toe ek klaar was, het FrewiEl aan my gesê: Sit en skryf uit alles wat Ek aan jou verduidelik het - skryf [oor] al die siele van die mensdom, dit maak nie saak hoe baie van hulle gebore word nie, en skryf oor die plekke wat vir hulle voorberei is vir die ewigheid; want alle siele word vir die ewigheid voorberei, nog voor die ontstaan van die wêreld. [JirmeJaH 1:5]	",
"	9 Ek het ‘n tweede keer vir dertig dae en dertig nagte gaan sit en ek het alles presies neergeskryf. En ek het driehonderd ses-en-sestig boekrolle geskryf.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '11',
content: [
		
"	1 JaHWeH het my geroep en Hy het my aan Sy Linkerhand laat sit, nader as GabriEl; en ek het JaHWeH vereer. En JaHWeH het aan my gesê:	",
"	2 Henog, alles wat is en alles wat beweeg, is alles deur My geskape en Ek sal alles aan jou openbaar van voordat alles was sedert die begin, alles wat Ek voortgebring het uit nie-materie om te wees en uit wat onsigbaar is, dit wat gesien kan word.	",
"	3 Selfs nie eens aan My Boodskappers het Ek My geheim openbaar nie, en Ek het nie aan hulle vertel hoe hulle self gevorm is nie,	",
"	4 ook nie hoe My oneindige en onverstaanbare skepping volbring is nie; en tog openbaar Ek dit aan jou vandag.	",
"	5 Want voordat dit wat sigbaar is, gemaak is, het Lig verskyn; maar Ek, al was Ek deur Lig omgewe, was soos een van die Onsigbares, en Ek het gereis soos die son van die ooste na die weste en van die weste na die ooste.	",
"	6 Die son sal rus vind, maar Ek vind nie rus nie, want Ek het alle dinge geskape.	",
"	7 En omdat dit My doel was om ‘n fondament daar te plaas en om ‘n sigbare skepping te vorm, het Ek aan die dieptes bevel gegee dat een van die onsigbares moet uitkom en sigbaar word.	",
"	8 En Adoïl het uitgekom, geweldig in grootte, en Ek het hom aanskou, en kyk! Hy het die Groot Eon [‘n onmeetike tydruimte] in sy buik gehad, en Ek het aan hom gesê:	",
"	9 Maak jouself oop, Adoïl, en laat dit wat is, sigbaar uit jou gebore word.	",
"	10 En hy het homself oopgemaak en die Groot Eon het uit hom gekom; en so is die Lig uit hom gebore wat die hele skepping dra wat Ek ten doel gestel het om te skep - en Ek was in die middel van die groot Lig en omdat lig uit Lig gebore word, het daar ‘n groot tydperk verskyn, en dit het die hele skepping vertoon wat Ek beplan het om te skep. [2 Ezra 7:59]	",
"	11 En Ek het gesien dat dit goed was.	",
"	12 En Ek het vir Myself ‘n Troon geplaas en daarop gaan sit, maar aan die Lig het Ek gesê: Gaan hoër op en vestig jouself hoog bo die Troon en wees ‘n fondament vir die hoëre dinge.	",
"	13 Want bokant die Lig is daar niks nie.	",
"	14 En Ek het opgekyk van My Troon en ‘n tweede keer na die dieptes geroep en gesê: Laat wat hard en sigbaar is uit die onsigbare voortkom. [2 Ezra 8:7]	",
"	15 En Aroegas het uitgekom, hard, swaar en baie swart [of rooi]. En Ek het gesien dat hy goed was en Ek het aan hom gesê: Gaan ondertoe en vestig jouself en wees die fondament van die onderste dinge.	",
"	16 En hy het afgegaan en homself gevestig, en het die fondament geword vir die laer dinge en onder die Duisternis was daar niks nie.	",
"	17 Ek het die eter met Lig omring en Ek het dit dik gemaak en uitgesprei oor die Duisternis,	",
"	18 en van die water het Ek groot rotse opgebou en Ek het die mis van die Afgrond beveel om droog te word, en Ek het die Afgrond, wat verval het, teruggeroep - toe het Ek die waters bevestig, dit wil sê, die bodemlose,	",
"	19 en Ek het ‘n fondament van Lig om die water gemaak, en sewe sirkels uit die binnekant geskep, soos kristal, nat en droog, dit wil sê, soos glas en die besnyding van die waters en die ander elemente.	",
"	20 Ek het aan elkeen van hulle sy weg gewys, en aan die sewe Sterre, elkeen in sy Hemele, sy weg gewys dat hulle so moet gaan, en Ek het gesien dat dit goed was.	",
"	21 En Ek het skeiding gemaak tussen lig en tussen duisternis, dit wil sê, in die middel van die water hier en daar [duskant en anderkant] en Ek het aan die lig gesê dat dit dag moet wees en aan die duisternis, dat dit nag moet wees en daar was aand en daar was more, die eerste dag.	",
"	22 Toe het Ek die hemelse sirkel stewig gemaak en bepaal dat die laer waters wat onder die Hemele is in een holte versamel, en dat die chaos droog moet word, en dit was so.	",
"	23 Uit die golwe het Ek harde en groot rotse gevorm, en van die droë rotse het Ek hoog opmekaar gestapel, en die droë dele het Ek Aarde genoem en die middel van die Aarde het Ek Afgrond genoem, dit wil sê, die bodemlose.	",
"	24 Nadat Ek die see op een plek versamel het, het Ek dit saamgebind met ‘n juk en Ek het ‘n ewige grens tussen die see en die droë grond gemaak, sodat die Aarde nie sal oorstroom word deur die water nie:	",
"	25 Ek het die Koepel van die Hemele geheg en hom bo die water bevestig.	",
"	26 Vir al die hemelse Skeppingsleërmagte het Ek die son uit die groot Lig gevorm en Ek het hom in die Hemele geplaas sodat hy op die Aarde sal skyn.	",
"	27 Ek het uit die klippe vuur geslaan, en uit die vuur het Ek die hemelse leërskare geskep, en al die Sterre-leërs, en die Gérubs en die Serafs en die Ofaniem [dit alles het Ek uit vuur geslaan].	",
"	28 En Ek het die Aarde beveel om alle soorte bome voort te bring, en al die berge, en al die lewegewende plante en elke soort saad wat gesaai kan word.	",
"	29 Voordat Ek lewende siele geskep het, het Ek voedsel vir hulle voorberei.	",
"	30 En Ek het die see beveel om visse voort te bring en al die reptiele wat kruip oor die Aarde, en al die voëls wat vlieg.	",
"	31 Toe Ek met alles klaar was, het Ek My Wysheid beveel om die adamiet te skep. [Wysheid van Salomo 9:9 / Spreuke 8:22-30] Vir al die hemelse leërskare het Ek die gelykenis van vuur bedink, en My oog het die baie harde, ferm rots aanskou en van die glinstering in My oog het die weerlig sy wonderlike aard ontvang,	",
"	32 wat beide vuur in water is en water in vuur, en die een sal nie die ander blus nie en die een sal nie die ander opdroog nie, daarom is die weerlig helderder as die son, sagter as water en harder as die harde rots.	",
"	33 En uit die rots het Ek vuur gesny, en van die vuur het ek die rangordes van die tien hemelse Skeppingsleërmagte, Boodskappers geskape; hul wapens is vurig en hul gewade ‘n brandende vlam, en Ek het beveel dat elkeen moet staan in sy rangorde. [Génesis 2:1]	",
"	34 Een uit hierdie rangordes van die Boodskappers het, nadat hy weggedwaal het met die rangorde onder hom, ‘n onmoontlike gedagte bedink, om sy troon hoër te plaas as die Wolkkolom bokant die Aarde sodat hy in rang gelyk aan My kon wees. [Boek van die Opregte 9:26; Judas 1:6]	",
		
		
"	35 EK het hom vanuit die hoogte met sy boodskappers neergewerp, en hy het onophoudelik in die lug bokant die Afgrond bly vlieg.	",
"	36 Hierna het Ek al die Hemele geskape, en dit was die derde dag. Op die vierde dag het Ek beveel dat daar groot ligte moet wees op die hemelse kringlope.	",
"	37 Op die eerste, heel boonste kringloop het Ek die Sterre geplaas. [Lukas 4:6]	",
"	38 En op die laer kringloop het Ek die son geplaas vir lig bedags en die maan en die Sterre vir lig in die nag.	",
"	39 Die son dat hy moet gaan volgens elke dier [van die diereriem], twaalf in getal, en Ek het die opeenvolging van die maande aangewys, en hulle name en hulle lewens, hul donderslae en hul uurmerke, hoe hulle mekaar moet opvolg. Toe het die aand gekom en die môre, die vyfde dag.	",
"	40 Ek het My Wysheid beveel om die adamiet uit sewe stowwe te skep: een, sy vlees uit die Aarde; twee, sy bloed uit die Dou; drie, sy oë van die son; [Spreuke van Salomo 9:1; Wysheid van Salomo 11:17; Wysheid van Sirah 17:6; Boekrol van Henog 60:8; 2 Ezra 8:7]	",
"	41 vier, sy bene uit klip; vyf, sy intellek uit die snelheid van die Boodskappers en van die Wolkkolom; ses, sy are en sy hare uit die gras van die Aarde; en sewe, sy siel uit My asem en van die Gees. [Spreuke 9:1; Wysheid van Salomo 9:9-11; 7:21-29; 8:4; JeshaJaH 40:7]]	",
"	42 En Ek het aan hom sewe eienskappe gegee: aan die vlees gehoor, die oë vir gesig, aan die siel reuk, die are vir aanraking, die bloed vir smaak, die bene vir volharding, en aan die intellek, soetheid [plesier].	",
"	43 En Ek het aan ‘n wyse spreuk gedink: Ek het die adamiet geskape uit die onsigbare en uit ‘n sigbare natuur en van beide is sy dood en sy lewe ‘n afbeelding, hy ken spraak soos ‘n geskapene, klein in grootheid, en groot in kleinheid,	",
"	44 en Ek het hom op die Aarde geplaas, ‘n tweede Boodskapper, eerbaar, groot en glansryk, en Ek het hom aangewys as die Vors om te heers oor die Aarde en om My Wysheid te besit, en daar was niemand soos hy op Aarde of in My hele skepping nie.	",
"	45 En Ek het aan hom ‘n naam toegesê, van die vier saamgestelde dele van die ooste, die weste, die suide, en van die noorde; en Ek het aan hom vier spesiale Sterre toegesê,	",
"	46 en Ek het hom Adam genoem, en aan hom die twee Weë gewys, die Lig en die Duisternis, en Ek het aan hom gesê:	",
"	47 Dit is suiwer en dit is besoedel, sodat Ek sou kon weet of hy My liefhet, of haat, sodat dit duidelik sou wees wie in sy saadlyn My lief het.	",
"	48 Want Ek het sy natuur gesien, maar hy het nie sy eie natuur gesien nie, en omrede hy nie gesien het nie, sou hy erger oortree, en Ek het gesê: Na die oortreding, wat is daar behalwe die Dood?	",
"	49 Ek het hom aan die slaap gemaak en hy het aan die slaap geraak. En Ek het van hom ‘n sykant geneem en vir hom ‘n vrou gemaak, dat Dood na hom sou kom deur sy vrou, en Ek het sy laaste woord geneem en haar naam moeder genoem, dit wil sê, Eva. [Génesis 2:21, 22]	",
"	50 Adam het lewe op Aarde, Ek het die Tuin van Eden in die ooste geskep sodat hy die Verbond moet waarneem en die Bevel gehoorsaam.	",
"	51 Ek het die Hemele vir hom oopgemaak, sodat hy die Boodskappers kon sien sing van oorwinning en die skadulose Lig kon sien.	",
"	52 En hy was gedurig in die Paradys, en Satan het verstaan dat Ek ‘n ander wêreld wou skep, want Adam was meester op Aarde om haar te beheer en te regeer.	",
"	53 Die Duiwel is die gees van besoedeling van benede, as ‘n vlugteling het hy Sotona van die Hemele gemaak omdat sy naam Sataniël was, so het hy verskillend van die boodskappers geword,	",
"	54 maar sy geaardheid het nie sy intellek [kennis] verander wat sy begrip van Geregtigheid en oortreding betref nie.	",
"	55 En hy het sy doemvonnis verstaan en die oortreding wat hy vroeër gepleeg het, daarom het hy ‘n gedagte teen Adam verwek, op so ‘n manier het hy Eva bedrieg en met haar gemeenskap gehad,	",
"	56 maar hy het Adam nie aangeraak nie. Maar Ek vervloek onkunde, maar wat Ek vroeër geseën het, het Ek nie vervloek nie,	",
"	57 Ek het nie die adamiet vervloek nie, ook nie die Aarde nie, ook nie die kruipende diere nie, maar die besoedelde vrug van die adamiet en sy werke.	",
"	58 Ek het aan hom gesê: Aarde is jy en na die Aarde waaruit Ek jou geneem het, sal jy teruggaan. En Ek sal jou nie vernietig nie, maar jou terugstuur waaruit Ek jou geneem het.	",
"	59 Dan kan Ek jou weer neem met My Tweede Koms. En Ek seën al My skepsele, sigbaar en onsigbaar.	",
"	60 En Adam was vyf en ‘n halwe tydperke in die Paradys. En Ek seën die sewende dag, wat die Sabbat is, waarop hy rus van al sy werke.	",
		
		
"	61 EK het ook die agtste dag aangewys, dat die agtste dag die eersgeskapene sal wees nadat Ek My werk voltooi het, en dat die eerste sewe sal draai in die vorm van die sewende duisend, [2 Ezra 7:54]	",
"	62 en dat aan die begin van die agtste duisend daar ‘n tyd sal wees van nie-telling, eindeloos, met nóg jare, nóg maande, nóg weke, nóg dae, nóg ure.	",
"	63 En nou, Henog, alles wat Ek aan jou vertel het, alles wat jy in die Hemele gesien het en alles wat jy in jou boekrolle neergeskryf het, dit was deur My Wysheid dat Ek beplan het om dit alles te skape.	",
"	64 Ek het dit geskape vanuit die laagste fondamente tot die hoogste en tot die verste eindes van albei: Ek het geen raadgewer of helper nie.	",
"	65 Ek alleen is Ewig, nie deur hande gemaak nie: My onveranderlike doel is My Raadgewer, en My Woord is My daad,	",
"	66 en My Oë hou wag oor alle dinge: as Ek My Aangesig wegdraai, sal alles vergaan; maar as Ek na alle dinge kyk, sal hulle bly bestaan.	",
"	67 Dink daaraan, Henog, en besef Wie dit is wat met jou praat; en neem die Boekrolle wat jy geskryf het [en Ek gee jou Semeil en Rasuil, wat jou na My gebring het] en gaan af na die Aarde, en vertel jou seuns alles wat Ek aan jou gesê het en alles wat jy gesien het vanaf die laagste Hemele op tot by My Troon.	",
"	68 Al die leërskare wat Ek geskep het: daar is nie een tussen hulle wat teen My is nie en wat nie onderdanig aan My is nie: almal is onderdanig aan My Gesag en dien My Mag alleen.	",
"	69 En gee aan hulle die boekrolle wat jou hand geskryf het, en hulle sal dit lees en die Skepper herken, en hulle sal ook verstaan dat daar geen ander Skepper as Ek is nie;	",
"	70 en hulle sal die boekrolle wat jou hand geskryf het deurgee aan hulle kinders, en hulle kinders na hul kinders, en naasbestaandes aan naasbestaandes [bloedverwante], van een geslag na ‘n ander.	",
"	71 Want Ek gee jou, Henog, as middelaar, MíkaEl, Vors van My leërskare, want wat jy geskryf het, en wat jou vaders, Adam en Set geskryf het, sal tot aan die einde van die tyd nie vernietig word nie.	",
"	72 Ek gee aan jou My Boodskappers, Ariog en Mariog wat Ek op die Aarde geplaas het om haar te bewaak en om die verbygaande dinge te orden en om jou vader se geskrifte te bewaar sodat dit nie vernietig word in die Vloed wat gaan kom nie en wat Ek in jou geslag op die Aarde sal bring.	",
"	73 Ek ken die besoedeling van die adamiet, dat hulle nie die juk wil dra wat Ek op hulle lê nie, ook saai hulle nie die saad [hul eie geslag] wat Ek aan hulle gegee het nie,	",
"	74 maar hulle het My juk afgegooi en hulle sal ‘n ander juk neem en waardelose saad saai, en hulle sal gode aanbid en My gesag verwerp, en die hele Aarde sal oortree met ongeregtigheid en oortredinge en verbastering,	",
"	75 en dan sal Ek ‘n Vloed op die Aarde bring: en die Aarde self sal vergaan in die magtige moeras.	",
"	76 En Ek sal een rasegte man uit jou nageslag met sy hele gesin bewaar, wat My wense sal uitvoer,	",
"	77 en uit hulle kinders sal ‘n ander nageslag verrys, die laaste [op Aarde], baie in getal en met groot verwagtinge.	",
"	78 Dan, in die loop van daardie geslag, sal die Boekrolle wat jy en jou vader geskryf het, openbaar gemaak word;	",
"	79 want die bewakers van die Aarde sal die Boekrolle toon aan manne van geloof, en die Boekrolle sal aan daardie geslag verduidelik word en dit sal hoër geag word as vantevore.	",
"	80 Maar nou, Henog, gee Ek jou ‘n verposing van dertig dae sodat jy tyd in jou huis kan spandeer en aan jou seuns alles kan vertel wat jy van My gehoor het,	",
"	81 en jou huishouding, en elkeen wat My Gebooie met sy hele hart onderhou, laat hom lees en verstaan, daar is niemand anders behalwe Ek nie.	",
"	82 En na dertig dae sal Ek die Boodskappers na jou stuur en hulle sal jou van die Aarde af wegneem van jou seuns na My toe.	",
"	83 Want daar is ‘n plek vir jou voorberei en jy sal voor My Aangesig vir altyd leef en My geheime aanskou;	",
"	84 en jy sal My diensknegte se skrywer wees, want jy sal alles neerskryf wat op die Aarde gebeur en alles wat gedoen word deur diegene op Aarde en in die Hemele, en jy sal vir My optree as getuie in die oordeel van die Groot Eon.	",
"	85 Al hierdie dinge het JaHWeH aan my gesê asof Hy ‘n Man was wat met Sy getroue vriend praat.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '12',
content: [
		
"	1 JaHWeH het een van die senior Boodskappers geroep, verskriklik en dreigend, en hom by my geplaas, in voorkoms was hy so wit soos sneeu en sy hande soos ys, met die voorkoms van groot ryp,	",
"	2 en hy het my gesig [met sy hande] gevries, want ek kon die verskrikking van JaHWeH nie verduur nie, soos dit nie moontlik is om die vuur van ‘n stoof en die son se hitte en die ryp in die lug te verduur nie.	",
"	3 En JaHWeH het aan my gesê: Henog, as jou gesig nie hier gevries word nie, sal geen adamiet in staat wees om na jou gesig te kyk nie.	",
"	4 En JaHWeH het aan daardie Manne gesê wat my eerste opgeneem het: Laat Henog met julle afgaan na die Aarde en wag saam met hom tot op die vasgestelde dag.	",
"	5 En hulle het my in die nag op my slaapbank neergesit. En Metúsalag, wat my koms verwag het, en dag en nag by my slaapbank gewaak het, was gevul met ontsag toe hy my hoor kom, en ek het aan hom gesê:	",
"	6 Laat my hele huishouding bymekaarkom sodat ek hulle alles kan vertel.	",
		

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '13',
content: [
		
"	1 EN nou, my kinders, luister na wat julle vader sê en na al die gebooie wat ek julle vandag gee:	",
"	2 Lei julle lewens asof voor die Aangesig van JaHWeH en sien toe dat alles wat julle doen, volgens die wil van JaHWeH is.	",
"	3 Want ek is op die bevel van JaHWeH na julle gestuur, om vir julle alles te vertel wat is en alles wat sal wees tot op die dag van die oordeel.	",
"	4 En nou, my kinders, dis nie deur my eie mond dat ek vandag met julle praat nie, maar deur die Mond van JaHWeH, wat my na julle gestuur het.	",
"	5 Want julle hoor die woorde uit my mond, ‘n man wat geformeer is net soos julle;	",
"	6 maar ek het die woorde van JaHWeH gehoor uit die vurige Mond van JaHWeH [want JaHWeH se Mond is ‘n vurige oond en Sy woorde ‘n vurige vlam wat daaruit voortkom].	",
"	7 Julle, my kinders, julle sien my gesig, die gesig van ‘n man wat soos julle geformeer is; maar ek het die Aangesig van JaHWeH gesien soos ‘n stuk Yster wat in die vuur verhit word sodat dit vonke strooi.	",
"	8 Want julle sien ‘n man se oë, die oë van ‘n man wat soos julle geformeer is; maar ek het JaHWeH se Oë gesien soos die strale van die skynende son wat die menslike oog verblind.	",
"	9 Julle, my kinders, julle sien my regterhand aan julle beduie, die hand van ‘n man wat net soos julle gemaak is, maar ek het die Regterhand van JaHWeH voor my sien beweeg en die Hemele sien vul.	",
"	10 Julle kan sien hoe groot my liggaam is, dit is net soos julle s’n; maar ek het gesien hoe groot JaHWeH is, dat Hy onmeetbaar, onvergelykbaar is en geen einde het nie.	",
"	11 Want julle hoor die woorde van my mond; maar ek het die woorde van JaHWeH gehoor, soos groot donder en onophoudelike dreuning van die wolke.	",
"	12 En nou, my kinders, luister na iemand wat oor ‘n aardse koning spreek en sê:	",
"	13 Dit is angswekkend en gevaarlik om voor ‘n aardse koning te staan, verskriklik en baie gevaarlik, want die koning se wil is dood en die koning se wil is lewe.	",
"	14 Maar om te staan voor die Koning van konings - wie kan die oneindige Vrees of die groot hitte verduur?	",
"	15 Maar JaHWeH het een van Sy Boodskappers in beheer van Tartarus geroep en hom by my gesit, en die voorkoms van die Boodskapper was soos sneeu, en sy hande was ys, en hy het my gesig afgekoel [want ek kon nie die angs van die vurige hitte verduur nie].	",
"	16 Toe het JaHWeH al hierdie woorde met my gepraat.	",
"	17 Dus nou, my kinders, weet ek alles, sommige uit die Mond van JaHWeH, ander het ek met my oë gesien, van die begin tot die einde en van die einde tot die hernuwing.	",
"	18 Ek weet alles, en ek het in die boekrolle neergeskryf die omvang van die Hemele en alles wat daarin is:	",
"	19 Ek het hulle bewegings gemeet en ek ken hul leërmagte: Ek het die telling van die Sterre voltooi, ‘n groot menigte sonder getal.	",
"	20 Watter man kan hulle omwentelinge of hulle beweginge verstaan, of hul terugkeer, of diegene wat hulle lei of diegene wat gelei word?	",
"	21 Selfs nie die Boodskappers ken hulle getal nie: maar ek het hulle name neergeskryf.	",
"	22 Ek het die omtrek van die son gemeet en ek het sy strale genommer en sy ingang en sy uitgang en al sy beweginge: ek het hulle name neergeskryf.	",
"	23 En ek het die omtrek van die maan gemeet en sy bewegings elke dag, die afneming van sy lig elke dag en uur; en ek het die name in die boekrolle neergeskryf.	",
"	24 Die woonplekke van die Wolkkolom en hul monde en hul Vleuels en hul reën en hulle druppels het ek ondersoek; en ek het geskryf van die gerammel van die donder en die wonder van die weerlig.	",
"	25 En hulle het aan my hulle Bewaarders gewys en die deurgange wat vir hulle uitgemeet was waarin hulle op en af kon gaan [hulle gaan gebonde op en kom gebonde af, sodat hulle nie met ruwe geweld die Wolkkolom af skeur en alles op Aarde vernietig nie].	",
"	26 Ek het die skatte van die sneeu en die stoorkamers van die ys en die koue lug neergeskryf.	",
"	27 Ek het opgelet hoe die Bewaarders van tyd tot tyd die wolke vul, tog is die skatte nie uitgeput nie.	",
"	28 Ek het die rusplekke van die Geeste/winde neergeskryf: Ek het gekyk en gesien hoe hulle Bewaarders hulle skale en mates bring:	",
"	29 Eers plaas hulle die Geeste/winde op die skaal en dan in die maat, en hulle is volgens hul maat uitgelaat oor die hele Aarde sodat hulle nie met ruwe asem die Aarde laat skud nie.	",
"	30 Vandaar is ek ondertoe geneem en het gekom by die plek van oordeel; en ek het die Doderyk/Sheol sien oopgaan en ek het daar ‘n stuk gelyk grond gesien soos ‘n tronk, ‘n oordeelsplek sonder weerga.	",
"	31 En ek het afgegaan en het neergeskryf al die oordele van diegene wat geoordeel is, en ek het al hulle vertwyfeling gesien en ek het gesug en geween ter wille van die verdoemenis van die wettelose en ek het vir myself gesê:	",
"	32 Geseënd is die man wat nooit gebore is nie, of wat na sy geboorte, sonder oortreding in die Oë van JaHWeH gelewe het, sodat hy nie na hierdie plek sal kom en die juk van hierdie plek moet dra nie.	",
"	33 En ek het die bewaarders van die sleutels van die Doderyk/Sheol gesien wat by die ontsaglike poorte gestaan het: [Openbaring 9:1]	",
"	34 Hulle gesigte was soos die gesigte van groot adders, hulle oë soos kerse wat doodgegaan het, hulle tande was ontbloot en het tot by hulle bors gereik. [Openbaring 9:8]	",
"	35 En ek het openlik aan hulle gesê: Mag dit wees dat ek julle nie gesien het, of gesien het wat julle doen nie, mag geeneen van my afstammelinge ooit na julle kom nie.	",
"	36 En vandaar het ek opgegaan na die Paradys van die regverdiges; en ek het daar ‘n geseënde plek gesien, en elke skepsel is geseënd, en almal leef in Vreugde en Blydskap, en in onmeetbare Lig en in die Ewige Lewe.	",
"	37 En ek het gesê, my kinders [en nou sê ek dit weer aan julle], geseënd is die man wat die Naam van JaHWeH vrees,	",
"	38 wat Hom sal dien asof hy altyd voor Sy Aangesig is, en slagdiere as aanbiedinge gee van die lewe, en wat sy lewe sal leef en sterwe.	",
"	39 Geseënd is die man wat sal doen wat regverdig en Reg is en die naakte met klere klee en brood gee aan die wat honger het.	",
"	40 Geseënd is die man wat ‘n voorvegter vir die weduwees en die wese sal wees en wat almal sal help teenoor wie daar ‘n onreg gepleeg is.	",
"	41 Geseënd is die man wat die onseker weg sal weier en sal loop op die Weg van Geregtigheid.	",
"	42 Geseënd ook is die man wat die saad van Geregtigheid saai, want hy sal sewevoudig maai.	",
"	43 Geseënd is die man in wie die Waarheid is en wat die waarheid teenoor sy naaste spreek.	",
"	44 Geseënd is die man op wie se lippe waaragtige Medelye is en Sagmoedigheid.	",
"	45 Geseënd is die man wat die werke van JaHWeH verstaan en Hom vereer en deur Sy werke weet wie hulle gemaak het. [MattithJaHûW 5:1-12]	",
"	46 En kyk, my kinders, nadat ek die dinge wat op Aarde verorden is ondersoek het, het ek hulle neergeskryf.	",
"	47 Ek het al die jare vergelyk, en van die jaar het ek die maande gemeet, en van die maande het ek die dae getel, en van die dae het ek die ure getel.	",
"	48 Ek het die ure gemeet en hulle uitgeskryf.	",
"	49 Ek het onderskei tussen verskillende soorte adamiete op Aarde; en ek het gemeet en elke mate bewys en elke eerlike balans soos wat JaHWeH my beveel het.	",
"	50 En ek het ‘n verskil in hierdie dinge gevind: een jaar is belangriker as ‘n ander jaar, een dag belangriker as ‘n ander dag, een uur belangriker as ‘n ander uur.	",
"	51 So is ook een adamiet belangriker as ‘n ander adamiet - een oor sy groot besittings, ‘n ander oor sy wysheid, ‘n ander oor sy intellek, sy vaardigheid en sy vermoë om stil te bly; ‘n ander weer oor sy suiwerheid, sy jeug, skerp humor, die vorm van sy liggaam of sy redelikheid.	",
"	52 Maar daar is geeneen groter as die adamiet wat JaHWeH vrees nie; want hulle wat JaHWeH vrees, sal vir ewig vereer word.	",
"	53 JaHWeH het die adamiet met Sy eie Hande geskape en na die beeltenis van Sy eie gesig: klein en groot het JaHWeH hom gemaak.	",
"	54 Hy wat die gesig van ‘n adamiet beskimp, beskimp die gesig van JaHWeH; hy wat die gesig van ‘n adamiet verafsku, verafsku die gesig van JaHWeH: gramskap en groot oordeel is aangewys vir diegene wat in die gesig van ‘n adamiet spuug.	",
"	55 Maar geseënd is die man wat sy hart na elke adamiet draai, om diegene wat veroordeel word, te help, om die gevalle een orent te help en om te gee aan die armes;	",
"	56 want op die dag van die groot oordeel sal al die adamiet se dade deur die Boekrol herroep word. [Openbaring 5:1]	",
"	57 Geseënd is die man wie se mate eerlik is, en sy gewig eerlik en sy balans eerlik;	",
"	58 want op die dag van die groot oordeel sal elke mate en elke gewig en elke balans uitgestal word soos op die mark en elke adamiet sal die waarheid omtrent sy mate ken en sy beloning daarvolgens ontvang.	",
"	59 Die adamiet wat ‘n slagdier voor die Aangesig van JaHWeH slag, JaHWeH sal sy sake laat floreer: die adamiet wat die lamp voor die Aangesig van JaHWeH met olie vul en nie ware oordeel ken nie, JaHWeH sal nie net sy skat in die Hemele vermeerder nie, JaHWeH sal sy skure met koring vul.	",
"	60 Het JaHWeH brood of kerse of skape of beeste nodig? Nee, glad nie; maar op hierdie manier toets JaHWeH die hart van die adamiet. JaHWeH eis suiwer harte.	",
"	61 Want dan sal JaHWeH Sy groot Lig stuur en in Hom sal die oordeel wees; en wie, as Hy daar is, kan verberg word? Luister, my kinders, en neem in die woorde van my lippe.	",
"	62 As enigiemand geskenke na ‘n aardse heerser bring, en trouelose gedagtes in sy hart koester, en die heerser weet daarvan, sal hy nie teenoor hom vertoorn wees en sy geskenke weier nie, en hom nie oorgee aan die oordeel nie?	",
"	63 Of as ‘n man homself suiwer voordoen voor ‘n ander deur misleiding van die tong, maar besoedel is in sy hart, sal die ander nie die verraad van sy hart herken en hom verdoem omdat sy ontrou aan almal duidelik was nie?	",
"	64 En wanneer JaHWeH die groot Lig stuur, dan sal daar oordeel wees vir die regverdige en die ongehoorsame en niemand sal ontsnap nie.	",
"	65 Nou, my kinders, hou al hierdie dinge in gedagte en skenk aandag aan wat julle vader sê: aan alles wat ek julle vertel het, net soos JaHWeH my beveel het.	",
"	66 Neem hierdie boekrolle wat met julle vader se hand geskryf is en lees hulle en leer daaruit die werke van JaHWeH, en as julle die geskrifte nakom, sal julle nie teen JaHWeH oortree nie;	",
"	67 want daar is niemand anders behalwe JaHWeH nie, nie in die Hemele nie, ook nie op die Aarde nie, ook nie in die plekke benede nie, ook nie in ‘n fondasie nie.	",
"	68 Dis niemand behalwe JaHWeH wat die fondamente op die onbekende gevestig het nie, wat die Hemele bo die onsigbare uitgestrek het,	",
"	69 die Aarde op die water gesit en haar bevestig het op die wankelbare, wat alleen die ontelbare dinge in die skepping gemaak het;	",
"	70 [want wie het die stof van die Aarde, of die sand van die see, of die druppels van die wolke getel?]	",
"	71 Wie het die Aarde en die see saamgebind met onoplosbare bande, wat uit vuur die onbegryplike skoonheid van die Sterre geslaan het en die Hemele versier het,	",
"	72 wie het alle dinge geskep sodat dit wat onsigbaar was, sigbaar geword het, terwyl Hyself onsigbaar was...	",
"	73 [Het JaHWeH nie gesê nie: Ek het die Sterre uit vuur gesny, en die Hemele daarmee versier, en dit in hul midde geplaas.	",
"	74 Die son reis volgens die sewe hemelse bane wat die bepaling is van honderd twee-en-tagtig trone, dan gaan hy onder op ‘n kort dag; en na weer honderd-twee en tagtig, gaan hy onder op ‘n lang dag.	",
"	75 En hy het twee trone waarop hy rus, wat heen en weer wentel bo die trone van die maande. Vanaf die sewentiende dag van die maand Tsivian gaan hy af na die maand Thevan, en vanaf die sewentiende van Thevan gaan hy op.	",
"	76 En so kom hy naby die Aarde, dan is die Aarde bly en laat haar vrugte groei en wanneer hy weggaan, dan is die Aarde hartseer en die vrugte het geen bloeityd nie].	",
"	77 Dit alles het Hy gemeet met die goeie maat van die ure, en Hy het ‘n maat deur Sy Wysheid vasgestel van die sigbare en die onsigbare. Van die onsigbare het Hy alles gemaak wat sigbaar is, terwyl Hyself onsigbaar is.	",
"	78 En gee hierdie Boekrolle deur na julle kinders, en sien toe dat julle kinders dit deurgee aan hulle kinders en aan al julle bloedverwante en al julle geslagte, aan hulle wat Wysheid het en JaHWeH vrees;	",
"	79 en hulle sal dit [die Boekrolle] ontvang en sal meer Vreugde daaruit put as uit enige uitsoekkosse, en hulle sal dit lees en vashou daaraan.	",
"	80 Maar die dwase en diegene wat JaHWeH nie ken nie, sal dit nie aanneem nie en sal dit verwerp; want die juk daarvan sal vir hulle te swaar wees.	",
"	81 Geseënd is die man wat sy juk sal dra en vashou daaraan, want hy sal beloning op die dag van die Groot Oordeel vind.	",
"	82 Want ek sweer aan julle, my kinders, dat voor die adamiet bestaan het, is daar ‘n plek van oordeel vir hom voorberei; en ‘n maat en ‘n gewig waardeur hy getoets sal word, is vooraf vir hom toeberei.	",
"	83 En ek sal elke adamiet se dade neerskryf en niemand sal kan ontsnap nie. [Exodus 32:33; Psalm 69:28]	",
"	84 Daarom, my kinders, leef julle volle lewe in lydsaamheid en sagmoedigheid, sodat julle die ewigheid wat gaan kom, sal beërwe.	",
"	85 En elke hou en elke wond en elke skroeiende hitte en elke besoedelde woord, as dit na jou kom terwille van JaHWeH, verduur dit; [MattithJaHûW 5:11]	",
"	86 en alhoewel jy sal kan vergeld, moenie teen jou naaste vergeld nie, want vergelding kom JaHWeH toe, Hy sal jou wreker op die dag van oordeel wees.	",
"	87 Verduur die verlies van jou goud en jou silwer ter wille van jou broer, sodat jy hemelse skatte op die dag van oordeel mag ontvang.	",
"	88 En steek jou hande uit na die weduwees en die wese, en help die armes met al jou mag, en hulle sal ‘n beskerming wees in die tyd van beproewing. [Psalm 41:1, 2]	",
"	89 Elke harde en swaar juk, as dit na julle kom ter wille van JaHWeH, verduur dit, en so sal julle jul beloning ontvang op die dag van die oordeel.	",
"	90 Dit is goed om in die oggend en in die middag en in die aand van die dag in die Huis van JaHWeH in te gaan en die Skepper van alle dinge te vereer.	",
"	91 Geseënd is die man wat sy hart oopmaak vir lofprysing en wat JaHWeH loof: vervloek is hy wat sy hart oopmaak vir verguising en om sy naaste te beskinder.	",
"	92 Geseënd is die man wat sy mond open en JaHWeH seën en verhoog: vervloek is hy wat sy mond oopmaak om te vloek en te laster voor die Aangesig van JaHWeH.	",
"	93 Geseënd is die man wat al die werke van JaHWeH eer: vervloek is hy wat die skepping van JaHWeH beskimp.	",
"	94 Geseënd is die man wat die werke van sy eie hande aanskou om dit tot stand te bring: vervloek is hy wat na ‘n geleentheid soek om die werke van ander te vernietig.	",
"	95 Geseënd is die man wat afkyk en die wat geval het, ophef; vervloek is hy wat kyk en gretig is vir die vernietiging van wat nie aan hom behoort nie.	",
"	96 Geseënd is die man wat die ou fondamente van die vaders onderhou: vervloek is hy wat die wette van die vaders en die grense vernietig.	",
"	97 Geseënd is die man wat Vrede saai: vervloek is hy wat die Vrede van ander vernietig.	",
"	98 Geseënd is die man wat Vrede spreek, en Vrede sy met hom: vervloek is hy wat geen Vrede spreek en in wie se hart geen Vrede is nie.	",
"	[99 Geseënd is hy wat met ‘n nederige mond en hart spreek: vervloek is hy wat Vrede met sy mond spreek, terwyl daar geen Vrede in sy hart is nie, maar die swaard.]	",
"	100 Want al hierdie dinge sal openbaar gemaak word in die weegskale en in die Boekrolle op die dag van die Groot Oordeel.	",
"	101 Dus, my kinders, bewaar julle harte van die besoedeling, volgens die balans van die Lig, wees erfgename vir ewig.	",
"	102 Julle mag nie sê: ons vader is by JaHWeH en in antwoord op sy gebede sal ons oortredinge vergewe word nie.	",
"	103 Julle sien dat ek al die dade van die adamiet opteken; en niemand kan vernietig wat my hand geskryf het nie, want JaHWeH sien alles. [Exodus 32:33; JeségiEl 9:3]	",
"	104 Dus nou, my kinders, luister na al julle vader se woorde, alles wat ek aan julle sê: sodat dit ‘n Erflating van Vrede vir julle sal wees.	",
"	105 En die Boekrolle wat ek aan julle gegee het, moet dit nie wegsteek nie: verduidelik dit aan almal wat die begeerte het om daarin te kyk, want hulle mag miskien die werke van JaHWeH herken.	",
"	106 Want kyk my kinders, die dag van die aangewese tyd kom nader, en die aangewese tyd laat my geen keuse nie, die Boodskappers wat saam met my moet gaan, staan voor my: en more sal ek opgaan tot in die hoogste Hemele, na my ewige erfenis.	",
"	107 Dit is waarom ek julle beveel, my kinders, om al die dinge van JaHWeH te doen.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '14',
content: [
		
"	1 EN Metúsalag het sy vader Henog geantwoord: Watter soort voedsel, vader, wil u hê moet ons vir u gereed kry, sodat u ons huise kan seën en u seuns, en u hele huishouding, om u adamiete te verhoog voordat u weggaan?	",
"	2 En Henog het sy seun geantwoord en gesê: Luister, my kind, van die dag af wat JaHWeH my gesalf het met die olie van Sy Glansrykheid, het ek nog geen voedsel ingeneem nie: voedsel is van geen waarde vir my nie en ek het geen behoefte aan aardse voedsel nie.	",
"	3 Maar roep jou broers en die hele huishouding en die oudstes van my volk, sodat ek met hulle kan praat en dan vertrek.	",
"	4 En Metúsalag het haastig gegaan, sy broers Regim en Ariïm en Agasugan en Garimion en al die oudstes van die volk bymekaar geroep; en hy het hulle na sy vader Henog gebring, en hulle het voor hom neergebuig.	",
"	5 En Henog het hulle ontvang en hulle geseën en hy het hulle geantwoord en gesê:	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '15',
content: [
		
"	1 LUISTER, my kinders. In die dae van julle vader, Adam, het JaHWeH na die Aarde gekom om haar te besoek en ook al die wesens wat Hy self gemaak het.	",
"	2 Toe het JaHWeH al die vee van die Aarde en al die reptiele van die Aarde en al die voëls met vlerke ontbied, en hulle na jul vader, Adam, gebring sodat hy name aan alles op Aarde moes gee.	",
"	3 En JaHWeH het hulle by hom gelaat en Hy het elke ding aan hom onderwerp as sy mindere en dat dit gehoorsaam moes wees aan die adamiet.	",
"	4 Want JaHWeH het die adamiet geskape en hom aangestel oor al Sy besittings: om die adamiet se ontwil sal daar geen oordeel wees vir ‘n enkele siel van die wilde dier van die veld nie, maar slegs vir die adamiet, want die adamiet het ‘n spesiale plek.	",
"	5 Daar is een plek in die Groot Eon vir al die siele van die wilde diere, en een kraal en een weiveld;	",
"	6 want die siel van ‘n dier wat JaHWeH gemaak het sal nie vergaan voor die dag van oordeel nie, maar alle siele sal die adamiet beskuldig.	",
"	7 Die adamiet wat die siel van ‘n dier sleg voed, oortree teen sy eie siel; maar die adamiet wat ‘n rassuiwer slagdier sonder gebrek naderbring - hy genees sy eie siel.	",
"	8 En die adamiet wat ‘n rassuiwer aanbieding van voëls sonder gebrek naderbring - dit is genesing vir sy siel.	",
"	9 En alles wat julle as voedsel het, bind dit by vier bene vas, dit is genesend [hy genees sy eie siel].	",
"	10 Die adamiet wat ‘n dier doodmaak sonder om hom vas te bind - dit is ‘n besoedelde gebruik [hy oortree teen sy eie siel].	",
"	11 Die adamiet wat in die geheim ‘n dier beseer - dit is ‘n besoedelde gebruik [hy oortree teen sy eie siel].	",
"	12 ‘n Adamiet wat ‘n ander se siel benadeel, benadeel sy eie siel; en daar is vir hom nooit enige genesing nie.	",
"	13 ‘n Adamiet wat moord pleeg, maak sy eie siel dood; en daar is vir hom nooit genesing nie.	",
"	14 Die adamiet wat vir ‘n ander ‘n strik stel, val self daarin, en daar is vir hom nooit genesing nie;	",
"	15 en ‘n adamiet wat ‘n ander voor die gereg sleep, sy eie oordeel sal tot in ewigheid nie ophou nie.	",
"	16 Nou daarom, my kinders, hou julle harte weg van Ongeregtigheid vir wie JaHWeH haat, en bo alles, van elke lewende siel wat deur JaHWeH gemaak is.	",
"	17 Soos wat ‘n adamiet JaHWeH vra vir sy siel, so sal hy aan elke lewende wese doen, want in die Groot Eon is daar baie woonplekke vir die adamiet voorberei, sommige baie suiwer huise en ander ontelbare besoedelde huise. [JeHôWganan 14:2]	",
"	18 Geseënd is die adamiet wat in die geseënde huise ingaan, want in die besoedelde is daar geen moontlikheid van bekering nie.	",
"	19 En as ‘n adamiet hom in sy hart voorneem om ‘n geskenk aan JaHWeH aan te bied, en sy hande doen dit nie, dan sal JaHWeH die werke van sy hande tot niks bring, sodat daar geen wins daarin is nie.	",
"	20 As sy hande dit doen en sy hart verskil van mening, selfs al sou die twyfel in sy hart voortduur, sal dit hom nie skade bring nie. [Prediker 5:3]	",
"	21 Geseënd is die man wat in geduld ‘n geskenk aan JaHWeH aanbied, want hy sal sy beloning kry.	",
"	22 En as ‘n adamiet belowe dat hy op ‘n gegewe tyd ‘n geskenk aan JaHWeH sal aanbied en dit doen, dan sal hy sy beloning kry;	",
"	23 maar as die tyd wat hy gestel het verbygaan, en tog kom hy sy belofte daarna na, en dit is werklik berou, sal hy nogtans nie geseën word nie, want elke vertraging is ‘n rede tot krenking.	",
"	24 En as ‘n adamiet die naaktes klee en brood gee aan die wat honger het, sal hy sy beloning ontvang, maar as sy hart anders voel, sal hy ‘n verloorder wees en niks wen nie.	",
"	25 En as die arm man versadig is en sy hart is hoogmoedig, dan sal hy al die voorspoed [goeie behandeling] verloor en geen voordeel kry nie; want JaHWeH verag ‘n hoogmoedige adamiet.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '16',
content: [
		
"	1 EN so het dit gekom dat toe Henog met sy seuns en met die oudstes van die volk gepraat het, het al die adamiete en al sy naastes [die hele volk] JaHWeH na Henog hoor roep.	",
"	2 En hulle het saam besluit en gesê: Laat ons gaan en vir Henog groet.	",
"	3 En omtrent tweeduisend mans het bymekaar gekom en hulle het gegaan na die plek Asugan, waar Henog en sy seuns was en die oudstes van die volk.	",
"	4 En almal het Henog gegroet en gesê: Jy, wie JaHWeH, die ewige Koning, geseën het, seën nou jou volk en verhoog ons in die Oë van JaHWeH, want JaHWeH het jou uitgekies en jou aangewys om ons oortredinge weg te neem.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '17',
content: [
		
"	1 EN Henog het sy volk geantwoord en gesê: Luister, my kinders. Voor alle dinge was, voor die skepping plaasgevind het, het JaHWeH die tyd van die skepping vasgestel.	",
"	2 Daarna het Hy Sy hele skepping geskape, beide dit wat sigbaar is en dit wat onsigbaar is; en na dit alles het Hy die adamiet na Sy eie beeld geskape,	",
"	3 en Hy het in hom oë geplaas om te sien en ore om te hoor en ‘n hart om te dink en ‘n verstand om te oorweeg.	",
"	4 Toe het JaHWeH die jaar tot voordeel van die adamiet georden en Hy het dit verdeel in seisoene en in ure sodat die adamiet die veranderinge en die einde van die seisoene kan waarneem, die begin van die jare en die einde van die maande en dae en die ure, en dat hy die lengte van sy eie lewe kan meet.	",
"	5 Wanneer die hele skepping wat deur JaHWeH tot stand gebring is tot ‘n einde kom, en elke adamiet na die Groot Oordeel van JaHWeH gaan, dan sal die seisoene vergaan, en daar sal geen jare meer wees nie,	",
"	6 ook sal die maande en die dae en die ure nie meer bereken word nie, maar daar sal ‘n enkele tydperk wees.	",
"	7 En al die regverdiges wat JaHWeH se oordeel ontsnap, sal verenig word met die Groot Eon, en die Eon sal verenig met die regverdiges en hulle sal vir ewig lewe.	",
"	8 En hulle sal geen arbeid meer hê nie, nóg lyding, nóg smart, nóg vrees vir vervolging, nóg barensweë, nóg nag, nóg Duisternis,	",
"	9 maar hulle sal om hulle ‘n groot en wonderlike Lig vir ewig hê en ‘n onvernietigbare muur en in die groot Paradys sal hulle die skuiling hê van ‘n ewige woonplek. [Openbaring 21:22]	",
"	10 Geseënd is die regverdiges wat die Oordeel van JaHWeH sal ontsnap, want hulle gesigte sal so helder soos die son skyn.	",
"	11 So nou, my kinders, bewaar julle siele van alle ongeregtigheid, van alles wat JaHWeH haat.	",
"	12 Leef jul lewens asof voor die Aangesig van JaHWeH en dien Hom alleen en bring aan Hom elke aanbieding wat verorden is.	",
"	13 As julle opkyk na die Hemele, JaHWeH is daar, want JaHWeH het die Hemele geskape: as julle na die Aarde en na die see kyk, en julle die dinge onder die Aarde aanskou, JaHWeH is daar ook, want JaHWeH het alles geskape.	",
"	14 Niks wat julle doen, kan verborge wees van die Oë van JaHWeH nie.	",
"	15 Laat dit wees met lydsaamheid en sagmoedigheid en in die teistering van julle droefheid dat julle hierdie wêreld van lyding verlaat.	",
"	16 En as julle die wêreld verlaat, sal julle nie meer in die wêreld wees nie, maar julle sal in die Paradys wees.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '18',
content: [
    	
"	1 TERWYL Henog met sy volk gepraat het, het JaHWeH ‘n duisternis oor die Aarde gestuur en dit was donker, en die duisternis het die adamiete wat by Henog gestaan het, oordek.	",
"	2 En die Boodskappers het gou gemaak en Henog opgeneem en hom gelei tot by die hoogste Hemele; en JaHWeH het hom ontvang en Hy het hom voor Sy Aangesig vir ewig geplaas.	",
"	3 En die duisternis het van die Aarde gewyk en dit was lig en die adamiete het gesien en verstaan hoe Henog weggeneem is; en hulle het Elohim vereer en teruggegaan na hulle wonings.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '19',
content: [
		
"	1 HENOG was gebore op die sesde dag van die maand Tsivan en het drie-honderd-vyf-en-sestig jaar geleef. Hy is opgeneem in die Hemele op die eerste dag van die maand Tsivan en het vir dertig dae in die Hemele gebly.	",
"	2 Hy het al hierdie tekens van die skepping wat JaHWeH geskep het, neergeskryf en het driehonderd ses-en-sestig Boekrolle geskryf, en hulle aan sy seuns oorhandig en vir dertig dae op die Aarde gebly en hy is weer in die Hemele opgeneem op die sesde dag van die maand Tsivan op die presiese dag en uur waarop hy gebore is.	",
"	3 Soos wat elke mens se natuur in hierdie lewe duister is, so is ook sy bevrugting, geboorte en vertrek uit hierdie lewe. Op die oomblik van sy bevrugting, op daardie oomblik is hy gebore en op daardie oomblik het hy ook gesterf.	",
	
]
},
{
book: 'Openbaring_Van_Henog',
chapter: '20',
content: [
		
"	2 EN Metúsalag het gou gemaak ... en my broers, die seuns van Henog, en hulle het ‘n altaar gebou op die plek Asugan waar Henog weggeneem is en hulle het skape en vee geneem en dit voor JaHWeH geslag.	",
"	2 En hulle het al die adamiete wat saam met hulle was, bymekaar geroep om fees te vier; en die adamiete het geskenke vir Henog se seuns gebring en hulle was vrolik en hulle het hul vir drie dae lank verbly.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '21',
content: [
		
"	1 OP die derde dag met sononder, het die oudstes van die volk na Metúsalag gekom en gesê:	",
"	2 Gaan en staan voor die Aangesig van JaHWeH en voor jou volk en voor die altaar van JaHWeH en jy sal deur jou volk vereer word.	",
"	3 En Metúsalag het sy volk geantwoord: JaHWeH, die Elohey van my vader Henog self, Hy sal self ‘n priester uit die volk oproep.	",
"	4 En die volk het die hele nag daar by die plek Asugan gewag en Metúsalag het by die altaar gebly en tot JaHWeH gebid en gesê:	",
"	5 Ewige JaHWeH, die enige El, wat ons vader, Henog, uitverkies het, U, o JaHWeH, moet ‘n priester vir U volk aanwys, en aan hulle harte begrip gee om U Glansrykheid te vrees en alles te doen volgens U wil.	",
"	6 En Metúsalag het aan die slaap geraak en JaHWeH het aan hom in ‘n visioen in die nag verskyn en aan hom gesê:	",
"	7 Luister, Metúsalag, Ek is JaHWeH, die Elohey van jou vader, Henog: luister na wat jou volk sê en staan voor hulle en voor My altaar en Ek sal jou voor My volk verhoog al die dae van jou lewe.	",
"	8 En Metúsalag het opgestaan uit sy slaap en Hom wat aan hom verskyn het, geseën.	",
"	9 En die oudstes van die volk het in die oggend na Metúsalag gekom en JaHWeH Elohim het Metúsalag se hart verander sodat hy geluister het na wat die volk sê en hy het aan hulle gesê: Laat JaHWeH julle Elohey, doen wat hierdie volk wil hê.	",
"	10 Sarsan en Garmis en Sazas en die oudstes van die volk het gou gemaak en Metúsalag opgetooi in pragtige klere en het ‘n skitterende kroon op sy kop geplaas en die volk het gou skape en vee en allerhande soorte voëls wat aangewys is, gebring sodat Metúsalag voor die Aangesig van JaHWeH en voor die volk kon slag.	",
"	11 Metúsalag het na die altaar opgegaan na JaHWeH, soos die Môrester wanneer hy opkom, en die hele volk het hom gevolg.	",
"	12 Metúsalag het by die altaar gestaan en die hele volk was om die altaar vergader.	",
"	13 En die oudstes van die volk het die skape en die vee geneem en hulle vier bene vasgebind en hulle by die kop van die altaar neergelê en die volk het aan Metúsalag gesê: Vat jou mes en slag hierdie aangewese slagdiere voor die Aangesig van JaHWeH.	",
"	14 En Metúsalag het sy hand na die Hemele uitgestrek en JaHWeH aangeroep en gesê:	",
"	15 O ek, my Elohey, wie is ek om te staan by die hoof van U altaar en aan die hoof van U volk! En nou, my Elohey, JaHWeH, sien neer op U dienskneg en op die hoofde van U hele volk en op al diegene wat uitverkies is, en betoon Barmhartigheid aan U dienskneg voor hierdie volk, dat hulle mag verstaan dat U verorden het ‘n priester vir U volk.	",
"	16 Terwyl Metúsalag gebid het, het die altaar geskud en die mes het van die altaar af in die lug opgestyg en in Metúsalag se hand gespring voor die hele volk.	",
"	17 En die volk het gebewe en JaHWeH vereer; en Metúsalag was van daardie dag af voor die Aangesig van JaHWeH vereer en geëer voor die hele volk.	",
"	18 En Metúsalag het die mes geneem en alles wat die volk gebring het, geslag.	",
"	19 En die volk was verheug en was vrolik voor die Aangesig van JaHWeH en voor Metúsalag op daardie dag; en daarna het elkeen na sy eie huis gegaan.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '22',
content: [
		
"	1 MAAR Metúsalag het van daardie dag af as die hoof van die altaar gestaan en as die hoof van die volk.	",
"	2 In eenduisend vierhonderd-en-tagtigste jaar het hy die hele Aarde verken en almal opgesoek wat in JaHWeH geglo het en ook die wat afvallig geraak het:	",
"	3 Hy het hulle reggehelp en bekeer; en geen man kon gevind word wat afvallig was van die Weë van JaHWeH nie, al die dae wat Metúsalag geleef het.	",
"	4 En JaHWeH het Metúsalag geseën in sy gawes en geskenke, in al sy bediening voor die Aangesig van JaHWeH.	",
"	5 En toe Metúsalag se dae naby hulle einde was, het JaHWeH aan hom in die nag in ‘n visioen verskyn en aan hom gesê: Luister, Metúsalag, Ek is die Elohey van jou vader, Henog.	",
"	6 Ek wil hê jy moet weet dat die dae van jou lewe hier op ‘n einde is en dat die dag van jou rus nader kom.	",
"	7 Roep Nir, jou seun Lameg, se tweede seun, en tooi hom in jou gewyde klere en plaas hom by My altaar en vertel hom alles wat gedurende sy lewe sal gebeur. Want die tyd kom vir die verwoesting van die hele Aarde en van elke adamiet en alles wat op Aarde beweeg.	",
"	8 Want gedurende sy lewe sal daar groot wanorde op Aarde wees, want die adamiet het afgunstig op mekaar geword; en mense sal mense onderdruk en nasie sal teen nasie oorlog voer: die hele Aarde sal gevul word met besoedelde bloed en wanorde.	",
"	9 Meer nog, hulle sal afvallig raak van hulle Skepper en aanbid wat in die Hemele bevestig is en wat op die Aarde beweeg en die golwe van die see; en die Teenstander sal homself vergroot en hom verbly in wat hulle doen tot My verdriet.	",
"	10 Die hele Aarde sal haar orde verander, en al die vrugte en al die gras sal hulle seisoene verander, want hulle sal wag op die tyd van vernietiging; en al die nasies van die Aarde sal afvallig raak tot My verdriet.	",
"	11 En dan sal Ek die Afgrond beveel en hy sal homself uitstort op die Aarde, en die skatte van die waters van die Hemele sal hulle uitstort op die Aarde en alles sal sonder vorm wees soos dit in die begin was; [Openbaring 9:2]	",
"	12 en die ganse struktuur van die Aarde sal vergaan, en die hele Aarde sal bewe en sy standvastigheid verloor van daardie dag af.	",
"	13 En dan sal Ek vir Noag, Lameg se oudste seun, bewaar; en Ek sal uit sy nageslag ‘n ander wêreld voortbring, en sy nageslag sal vir altyd bestaan [in stand bly].	",
"	14 En toe hy uit sy slaap opstaan, was Metúsalag baie bekommerd oor sy droom.	",
"	15 Hy het al die oudstes van die volk geroep en hulle alles vertel wat JaHWeH aan hom gesê het en die visioen wat JaHWeH aan hom openbaar het, en hulle het hom geantwoord:	",
"	16 JaHWeH het die mag om te doen wat Hy wil; dus moet jy nou alles doen wat JaHWeH aan jou gesê het.	",
"	17 Metúsalag het Nir, Lameg se tweede seun, geroep en hom voor die hele volk in die priesterlike kleed getooi en hy het hom by die hoof van die altaar geplaas en hom alles geleer wat hy onder die volk moet doen.	",
"	18 En Metúsalag het aan die volk gesê: Aanskou Nir! Aanskou, hy sal van vandag af julle leier wees en die gids van die vorste.	",
"	19 En die volk het Metúsalag geantwoord: Mag die Woord van JaHWeH oor ons vervul word soos wat Hy aan jou belowe het.	",
"	20 En terwyl Metúsalag met die mense gepraat het, was sy gees gekwel en hy het op sy knieë geval en sy hande uitgestrek na die Hemele en tot JaHWeH gebid en terwyl hy bid, het sy gees hom verlaat.	",
"	21 Nir het gou gemaak, asook die hele volk, en ‘n graftombe vir Metúsalag gebou; en hulle het wierook en soetriet en baie dinge daarin gesit om dit te wy.	",
"	22 En Nir en die volk het gegaan en Metúsalag se liggaam in die grafkelder wat hulle vir hom gebou het, neergelê en dit toegemaak.	",
"	23 En die volk het gesê: Geseënd is Metúsalag voor die Aangesig van JaHWeH en voor die hele volk.	",
"	24 Daarna het hulle bymekaar gekom en Nir het aan die volk gesê: Maak gou vandag en bring die skaap en die bul en die tortelduif en die duif sodat ons voor die Aangesig van JaHWeH kan slag sodat Hy Hom kan verbly in vandag, en gaan dan terug na julle eie huise.	",
"	25 En die volk het na Nir, die priester, geluister: hulle het gou gemaak en die slagdiere gebring en hulle vasgebind by die hoof van die altaar en Nir het die slagmes geneem en voor die Aangesig van JaHWeH geslag.	",
"	26 En die volk het gou gemaak en gedoen wat aan hulle gesê is en hulle was die hele dag lank vrolik voor die Aangesig van JaHWeH: hulle het die Majesteit JaHWeH, die Verlosser van Nir, voor die volk verhoog.	",
"	27 Van daardie dag af was daar Vrede en orde dwarsoor die hele Aarde in Nir se dae, vir tweehonderd-en-twee jaar lank.	",
"	28 En daarna het die volk van JaHWeH afvallig geraak en jaloers op mekaar begin word: en adamiete het teen adamiete opgestaan en nasie het teen nasie in stryd opgestaan en daar was groot opskudding.	",
"	29 En Nir, die priester, het daarvan te hore gekom, en hy was baie ontsteld en het aan homself gesê: Die tyd het gekom dat die woorde vervul word wat JaHWeH tot my grootvader, Metúsalag gespreek het.	",

]
},
{
book: 'Openbaring_Van_Henog',
chapter: '23',
content: [
	
"	1 EN kyk, Sofonima, Nir se vrou, was onvrugbaar en het vir Nir geen kinders gebaar nie.	",
"	2 En Sofonima was ver in jare gevorder en baie naby haar dood; en sy is bevrug, al het Nir, die priester, nie met haar gemeenskap gehad sedert die dag dat JaHWeH hom voor die volk geplaas het nie.	",
"	3 Sofonima was beskaamd en het dag vir dag weggekruip en nie een van die volk het geweet nie; en die dag het aangebreek dat sy geboorte moes skenk.	",
"	4 En Nir het aan sy vrou gedink en haar na hom geroep in sy huis om met haar te praat; en Sofonima het na haar man gegaan, en kyk, sy was op die punt om geboorte te skenk.	",
"	5 En toe Nir haar sien, het hy hom vir haar geskaam en hy het aan haar gesê: Hoekom het jy dit gedoen, vrou, en skande op my gebring voor die hele volk?	",
"	6 En nou, weg van my: gaan na waar jy so skaamteloos bevrug is, ingeval ek my hande op jou besoedel en oortree voor die Aangesig van JaHWeH.	",
"	7 En Sofonima het haar man geantwoord en gesê: Kyk, my meester, ek is ver in jare gevorder en geen jeugdige begeertes is nog in my oor nie: Ek weet nie hoe ek in my onskuld bevrug kon word nie.	",
"	8 Nir het haar nie geglo nie en hy het aan haar ‘n tweede keer gesê: Weg van my, ingeval ek aan jou slaan en voor die Aangesig van JaHWeH oortree.	",
"	9 En terwyl Nir met sy vrou gepraat het, het Sofonima voor Nir se voete neergeval en gesterf.	",
"	10 En Nir was baie ontsteld en het aan homself gesê: Is dit oor wat ek gesê het dat dit met haar gebeur het?	",
"	11 Maar nou is die ewiglewende JaHWeH barmhartig, want ek het geen hand teen haar opgelig nie.	",
"	12 Nir het gou gemaak en die deure van sy huis gesluit en na sy broer, Noag, gegaan en hom alles vertel wat met sy vrou gebeur het.	",
"	13 En Noag het gou gemaak en na sy broer se huis gegaan; en sy broer se vrou was duidelik dood, en sy was op die punt om geboorte te skenk. [JirmeJaH 1:5]	",
"	14 En Noag sê aan Nir: Moet jou nie ontstel nie, Nir, my broer, want JaHWeH het ons skaamte vandag bedek, aangesien niemand van die volk hiervan weet nie; en nou, maak gou, laat ons haar begrawe en JaHWeH sal ons skande bedek.	",
"	15 En hulle het Sofonima op ‘n bed neergelê en haar in swart klere aangetrek, en die deur toegemaak en in die geheim grafkelders gaan uithol.	",
"	16 En toe hulle uitgegaan het na haar graf, het die kind uit die lyk van Sofonima gekom en op die bed gesit.	",
"	17 Noag en Nir het ingekom om Sofonima te begrawe en hulle het die kind gesien wat by die lyk gesit het en hy het ‘n kledingstuk aangehad.	",
"	18 Noag en Nir was baie verskrik, want die kind se liggaam was volmaak: hy het met sy mond gepraat en JaHWeH geseën.	",
"	19 Noag en Nir het na hom gestaar en gesê: Dit is die werk van JaHWeH, my broer.	",
"	20 Kyk, die Seël van die priesterskap was op sy bors en hy was ‘n vreugde om te aanskou.	",
"	21 En Noag het aan Nir gesê: Broer, kyk, JaHWeH sal die Tabernakel van Apartheid na ons herstel.	",
"	22 En Nir en Noag het gou gemaak en die kind gewas en hom getooi in die priesterlike klere, en hulle het hom brood gegee wat geseën was en hy het hom geëet, en hulle het hom Melgisédek genoem.	",
"	23 En Noag en Nir het Sofonima se liggaam geneem en die swart klere van haar afgehaal: en hulle het haar liggaam gewas en haar geklee in skitterende en kosbare klere.	",
"	24 En hulle het vir haar ‘n grafkelder gebou; en Noag het gegaan en Nir en Melgisédek, en hulle het haar openlik met eer begrawe.	",
"	25 Noag het aan sy broer gesê: Hou die kind in die geheim tot die aangewese tyd, want die mens se besoedeling het oral op die Aarde vermeerder, en as hulle hom sien, sal hulle ‘n manier vind om hom dood te maak.	",
"	26 En Noag het huis toe gegaan.	",
"	27 En kyk, in die dae van Nir het al die soorte ongeregtigheid tot ‘n groot mate orals op die Aarde vermeerder; en Nir was baie ontsteld, en nog meer oor die kind en hy het gesê: Wat kan ek vir hom doen?	",
"	28 Nir het sy hande na die Hemele uitgestrek en JaHWeH aangeroep en gesê: Helaas, ewiglewende JaHWeH, alle soorte ongeregtigheid het grootliks op die Aarde in my dae vermeerder, en ek kan aanvoel dat ons einde naby is.	",
"	29 Wat kan ek vir hom doen, sodat hy nie betrokke sal wees by ons in hierdie vernietiging nie?	",
"	30 JaHWeH het Nir gehoor en aan hom in ‘n visioen in die nag verskyn en aan hom gesê: Aanskou, Nir, die verbastering op die Aarde is oral: Ek sal dit nie langer verduur of uithou nie.	",
"	31 Kyk, Ek gaan baie gou ‘n groot vernietiging oor die Aarde bring, maar Ek het geen bekommernis oor die kind nie, Nir, want na ‘n klein rukkie sal Ek My Hoofboodskapper GabriEl stuur en hy sal die kind neem en hom in die Paradys van Eden plaas.	",
"	32 Hy sal nie vergaan saam met die wat op die punt staan om te vergaan nie, want Ek het hom as ‘n Teken gestuur- hy sal vir My ‘n priester van priesters vir ewig wees, Melgisédek, en Ek sal hom eenkant sit, en Ek sal van hom ‘n groot volk maak wat My sal eer.	",
"	33 Nir het uit sy slaap opgestaan en JaHWeH wat aan hom verskyn het, geseën en gesê: Geseënd is U, Elohey van ons vaders, wat nie oneer oor my priesterskap laat val het nie of oor die priesterskap van my vaders nie, want U Woord het ‘n Hoëpriester in die baarmoeder van my vrou Sofonima geskep.	",
"	34 Want ek het geen kinders gehad nie en hierdie kind sal in die plek van my eie kinders wees en my seun word;	",
"	35 en U sal hom by U diensknegte tel met Sonfi en Onog en Rusi en Milam en Serug en Arusan, Nail en Henog, en Metúsalag en U dienskneg Nir, en Melgisédek sal die hoëpriester wees in ‘n ander geslag. [Génesis 14:18]	",
"	36 Want ek weet dat hierdie geslag sal eindig in verwarring en almal sal vergaan, en Noag, my broer, sal bewaar bly vir ‘n ander geslag om die vader daarvan te wees,	",
"	37 en uit sy familie sal ‘n talryke volk voortspruit en Melgisédek sal die hoëpriester onder ‘n volk wees wat U onderdane sal wees, o JaHWeH, en U sal dien. [Hebreërs 7:1-2,3]	",
"	38 En toe die kind vir veertig dae in Nir se huis was, het JaHWeH aan die Hoofboodskapper GabriEl gesê: Gaan af na die Aarde, na Nir, die priester, en neem die kind Melgisédek wat by hom is en sit hom in die Tuin van Eden om hom veilig te bewaar.	",
"	39 Want die tyd is baie naby dat Ek al die waters oor die Aarde sal loslaat en alles wat op die Aarde is, sal vergaan en Ek sal hom ‘n plek van eer in ‘n volgende geslag gee, en Melgisédek sal die Hoëpriester van daardie geslag wees.	",
"	40 En GabriEl het gou gemaak en in die nag afgevlieg; en daardie nag was Nir aan die slaap op sy bed en GabriEl het aan hom verskyn en gesê:	",
"	41 So sê JaHWeH aan Nir, laat die kind wat Ek aan jou toevertrou het, na My toe kom.	",
"	42 Nir het nie herken wie dit was wat met hom gepraat het nie en hy was baie ontsteld en het aan homself gesê: Kan dit wees dat die volk weet van die kind om hom weg te vat en dood te maak?	",
"	43 [want die volk se gedagtes en voornemens was besoedel in die Oë van JaHWeH]. En hy het GabriEl geantwoord en gesê: Ek het geen kind nie en ek weet ook nie wie dit is wat met my praat nie.	",
"	44 En GabriEl het hom geantwoord: Moenie bevrees wees nie, Nir, ek is die Hoof-boodskapper GabriEl: JaHWeH het my gestuur, en kyk, ek gaan jou kind vandag neem en ek sal gaan en hom in die Paradys van Eden sit.	",
"	45 En Nir het sy eerste droom onthou en hy het geglo en GabriEl geantwoord: Geseënd is JaHWeH wat jou vandag na my gestuur het; en seën dan nou u dienskneg, Nir, en neem die kind en doen met hom alles wat aan u gesê is.	",
"	46 En GabriEl het die kind Melgisédek daardie nag op sy Vleuels geneem en hom in die Paradys van Eden geplaas.	",
"	47 En toe Nir in die oggend wakker word en in die huis ingaan, het hy die kind nie gevind nie; en dit was vir Nir ‘n teken van beide groot blydskap en groot droefheid, want die kind het vir hom geword soos ‘n eie seun.	",


]
}

];
