const petrusChapters = [

{
book: 'Petrus',
chapter: '1',
content: [
				
"	1 EN van die Jode het niemand die hande gewas nie, ook nie Herodes of enigeen van sy regters nie. En toe hulle nie [die hande] wou was nie, het Pilatus opgestaan.	",
"	2 Toe het koning Herodes hulle beveel om JaHWèshua te neem en gesê: Alles wat ek julle beveel het om aan Hom te doen, doen dit!	",
"	3 En JôWsef, die vriend van Pilatus en van JaHWèshua, het daarby staan. En wetende dat hulle Hom wou gaan folter, het hy na Pilatus gegaan en die liggaam van JaHWèshua gevra om te begrawe.	",
"	4 En Pilatus het na Herodes gestuur en om Sy liggaam gevra.	",
"	5 En Herodes sê: Broer Pilatus, selfs al sou niemand Hom gevra het nie, sou ons Hom begrawe het, aangesien ook die Sabbat op hande is. Want daar staan geskrywe in die Wet dat die son nie moet ondergaan oor een wat ter dood gebring is nie. [Deuteronómium 21:23]	",
"	6 En hy het Hom oorgelewer aan die volk op die dag vóór hul Fees van die Ongesuurde Brode. Hulle neem toe die Meester en soos hulle aanloop, stoot hulle Hom voort en sê: Laat ons die Seun van Elohim aansleep noudat ons Hom in ons mag gekry het.	",
"	7 En hulle trek vir Hom ‘n purper kleed aan en laat Hom op ‘n regterstoel sit en sê:  Gee ‘n regverdige regspraak, o Koning van JisraEl!	",
"	8 En een van hulle het ‘n kroon van dorings gebring en haar op JaHWèshua se hoof gesit.	",
"	9 En ander het daar gestaan en in Sy oë gespuug, en ander het Hom op Sy wange geslaan; ander het Hom met ‘n riet gesteek, en sommige het Hom gegesel en gesê: Laat ons met so ‘n Eer die Seun van Elohim vereer! [Psalm 129:3; JeshaJaH 50:6; MattithJaHûW 27:30; Markus 14:65]	",
"	10 En hulle het twee misdadigers gebring en JaHWèshua tussen die twee gefolter.	",
"	11 Maar Hy het stilgebly soos een wat geen pyn voel nie. En toe hulle die folterpaal opgerig het, het hulle daarop geskrywe: JaHWèshua, die Nasaréner, die Koning van die manne van JeHûWdah.	",
"	12 En hulle het Sy klere voor Hom neergelê en dit [tussen hulle] verdeel en die lot daaroor gewerp.	",
"	13 En een van die misdadigers het hulle berispe en gesê: Ons ly so vanweë die misdade wat ons begaan het, maar hierdie Man wat die Verlosser van die adamiete geword het, watter misdaad het Hy julle aangedoen?	",
"	14 En hulle het toornig op hom geword en opdrag gegee dat Sy bene nie gebreek moes word nie, sodat Hy in marteling kon sterwe.	",
"	15 Dit was nou middag, en duisternis het oor die hele JeHûWdah geheers. En hulle was verontrus en in angs dat die son dalk al ondergegaan het terwyl Hy nog leef, want daar staan vir hulle geskrywe dat die son nie mag ondergaan oor een wat ter dood gebring is nie.	",
"	16 En een van hulle sê: Gee vir Hom gal met asyn om te drink! en hulle het dit gemeng en dit vir Hom te drinke gegee.	",
"	17 En hulle het alles vervul en [die maat van] hul dade van ongeregtigheid oor hul eie hoofde volbring.	",
"	18 En baie het met lampe rondgegaan, menende dat dit nag was, en party het geval.	",
"	19 En die Meester het luid uitgeroep en gesê: Eli, Eli, LAMMA AZABAGTANI? Dit is: My El, My El, waarom het U My verlaat. En nadat Hy dit gesê het, is Hy opgeneem.	",
"	20 En in dieselfde uur het die voorhangsel van die Tempel te Jerusalem in twee geskeur.	",
"	21 En daarna trek hulle die spykers uit die hande van die Meester en lê Hom op die Aarde neer. En die hele Aarde het gebewe, en daar het ‘n groot vrees [oor hulle] gekom.	",
"	22 Daarop skyn die son weer, en bevind hulle dat dit die negende uur is.	",
"	23 Toe verheug die Jode hulle en gee Sy liggaam aan JôWsef om te begrawe omdat hy al die goeie dinge aanskou het wat Hy gedoen het.	",
"	24 Hy het toe die Meester geneem, Hom gewas en in linne toegedraai en Hom gebring na Sy eie graf, die JôWsefsgraf genoem.	",
"	25 Toe die Jode en die oudstes en die priesters insien watter groot boosheid hulle hulself aangedoen het, begin hulle weeklaag en sê: Wee oor ons dade van ongeregtigheid! Die oordeel en die einde van Jerusalem het naby gekom!	",
"	26 Maar ek en my metgeselle was vol droefheid, ons was verwond in ons harte en moes ons verberg. Want hulle het na ons gesoek soos na misdadigers, en soos na mense wat die Tempel aan die brand wou steek.	",
"	27 En by dit alles het ons gevas, en ons het in droefheid en trane gesit, nag en dag, tot aan die Sabbat.	",
"	28 Maar die skrywers en die Fariseërs en die oudstes het saamgekom, want hulle het gehoor dat die hele volk murmureer en op hul bors slaan en sê: As hierdie besonder groot tekens by Sy dood plaasgevind het, kyk hoe regverdig was Hy!	",
"	29 En toe die oudstes bevrees word, het hulle na Pilatus met ‘n versoek gegaan en gesê:	",
"	30 Gee ons soldate dat ons Sy graf drie dae lank kan bewaak, sodat Sy studente nie kom en Hom steel, en die volk meen dat Hy uit die dode opgestaan het, en hulle ons kwaad aandoen nie.	",
"	31 Toe gee Pilatus aan hulle die hoofman oor honderd, Petronius, met soldate om die graf te bewaak, en saam met hulle het oudstes en skrywers na die graf gegaan.	",
"	32 En nadat hulle, met die hoofman oor honderd en die soldate, ‘n groot steen daarheen gerol het, het almal wat daar saam was dit voor die ingang van die graf geplaas.	",
"	33 En hulle het dit met sewe seëls verseël en hul tent daar opgeslaan en wag gehou.	",
"	34 En vroeg in die môre, toe die Sabbat aanbreek, het skares uit Jerusalem en die omgewing gekom om die graf te sien wat verseël was.	",
"	35 En in die nag waarin die dag van JaHWèshua aangebreek het, terwyl die soldate twee‑twee op wag gestaan het, het daar ‘n geweldige geluid uit die Hemele geklink.	",
"	36 En hulle sien die Hemele geopen, en twee Manne wat vandaar in ‘n helder glans neerdaal en die graf nader.	",
"	37 En daardie steen wat voor die ingang geplaas was, het vanself weggerol en opsy gaan lê, en die graf is geopen en albei jong manne het daar ingegaan.	",
"	38 Maar toe die soldate dit sien, het hulle die hoofman oor honderd en die oudstes wakker gemaak ‑ want ook húlle het deelgeneem aan die wag -	",
"	39 En terwyl hulle nog vertel wat hulle gesien het, sien hulle weer drie Manne uit die graf kom, en twee van Hulle het die Ander ondersteun.	",
"	40 En hulle sien dat van die twee die hoofde tot aan die Hemele raak, maar die hoof van Hom wat deur Hulle gelei word, steek bó die Hemele uit.	",
"	41 En hulle hoor ‘n Stem uit die Hemele wat sê: Het U aan die ontslapenes afgekondig?	",
"	42 En Hy het geantwoord: Ja!	",
"	43 Toe beraadslaag hulle met mekaar of hulle nie sou gaan en dit aan Pilatus rapporteer nie.	",
"	44 En terwyl hulle nog hul gedagtes daaroor laat gaan, is die Hemele weer geopen en Iemand het neergedaal en die graf binnegegaan.	",
"	45 Toe die hoofman oor honderd en die wat met hom was, dit sien, het hulle hul nog in die nag na Pilatus gehaas terwyl hulle die graf wat hul bewaak het, net so gelaat het, en in groot angs het hulle alles vertel wat hulle gesien het en gesê: Waarlik Hy was die Seun van die Elohim!	",
"	46 Pilatus antwoord en sê: Ek is skoon van die bloed van die Seun van die Elohim, maar só het julle dit goedgedink!	",
"	47 Toe kom hulle almal en smeek hom en versoek hom ernstig om aan die hoofman oor honderd en die soldate opdrag te gee om niks te vertel van wat hulle gesien het nie.	",
"	48 Want, so het hulle gesê, dit is vir ons beter om aan die grootste oortreding voor Elohim skuldig te staan as om in die hande van die volk van die Jode te val en gestenig te word.	",
"	49 Pilatus het dan toe ook die hoofman oor honderd en die soldate beveel dat hulle niks moes sê nie.	",
"	50 En vroeg in die môre op die dag van JaHWeH het Mirjam die Migdalieth, ‘n student van JaHWèshua ‑ uit vrees vir die Jode, want hulle was vervul van woede, het sy nie by die graf van JaHWèshua die dinge gedoen wat vroue gewoond is om te doen aan die dodes wat hul liefhet nie ‑	",
"	51 haar vriendinne meegeneem en by die graf gekom waar hulle Hom neergelê het.	",
"	52 En hulle was bang dat die Jode hulle sou sien en het gesê: Al was ons nie in staat om oor Hom te ween en te rouklaag op die dag toe Hy gefolter is nie, laat ons dit dan nou hier by Sy graf doen.	",
"	53 Maar wie sal vir ons die steen wegrol wat voor die ingang van die graf lê, sodat ons kan binnegaan en by Hom sit en doen wat nodig is? Want die steen was groot. En ons is bang dat iemand ons sal sien!	",
"	54 En as ons dit nie kan doen nie, laat ons ten minste by die ingang neerlê dit wat ons tot ‘n gedagtenis aan Hom bring, en ons sal ween en rouklaag totdat ons by die huis kom.	",
"	55 En toe hulle daar kom, vind hulle die graf geopen. En hulle het nader gekom, daarin gekyk, en daar ‘n jong Man met ‘n skone voorkoms en in ‘n skitterende gewaad geklee, in die middel van die graf sien sit. En Hy sê vir hulle:	",
"	56 Waarvoor het julle gekom? Wie soek julle? Tog nie die Gefolterde nie? Hy het opgestaan en het vertrek. Maar as julle dit nie glo nie, kyk in en aanskou die plek waar Hy gelê het, dat Hy nie hier is nie, want Hy het opgestaan en het daarheen gegaan van waar Hy gestuur was.	",
"	57 Toe het die vroue bevrees geword en gevlug.	",
"	58 Dit was nou die laaste dag van die Fees van die Ongesuurde Brode, en baie het vertrek en na hul eie huise teruggekeer omdat die Fees ten einde was.	",
"	59 Maar ons, die studente van die Meester, het geween en was vol droefheid, en elkeen het huis toe gegaan, treurende oor wat gebeur het.	",
"	60 Maar ek, Simon Petrus, en Andreas, my broer, het ons nette geneem en na die see gegaan; en met ons was Levi, die seun van Alfeus, wat die Meester..	",

]
}
];
