const spreuke_van_salomoChapters = [

{
book: 'Spreuke_Van_Salomo',
chapter: '1',
content: [
"	1 DIE spreuke van Salomo, die seun van Dawid, die koning van JisraEl,	",
"	2 om Wysheid en Tug te ken, om woorde van Insig te verstaan,	",
"	3 om aan te neem Tug wat verstandig maak, Geregtigheid en Reg en regverdigheid;	",
"	4 om aan die eenvoudiges skrander-heid te gee, aan die jongeling Kennis en Oorleg;	",
"	5 laat die wyse luister, dan sal hy Insig vermeerder, en die verstandige sal verstandige gedagtes verkry,	",
"	6 om ’n spreuk en beeldspraak te verstaan, die woorde van die wyse manne en hulle raaisels.	",
		
		
"	7 DIE Vrees van JaHWeH is die begin van die Kennis; sotte verag Wysheid en Tug.	",
"	8 My seun, luister na die tug van jou Vader, en verwerp die Wet van jou Moeder nie; [Wysheid van Sirah 15:2; 2 Ezra 2:5]	",
"	9 want sy is ’n lieflike Krans vir jou hoof en sierlike kettings vir jou hals.	",
"	10 My seun, as die wetsoortreders jou wil verlei, moet jy nie inwillig nie;	",
"	11 as hulle sê: Gaan saam met ons, laat ons loer op bloed, laat ons die onskuldige voorlê sonder oorsaak.	",
"	12 Verslind lewendig vir die Doderyk/Sheol die rassuiweres, soos ook die wat in die put neerdaal;	",
"	13 allerhande kosbare goed sal ons vind, ons huise sal ons vol maak met buit;	",
"	14 jy sal jou lot onder ons werp, ons sal almal een beurs hê -	",
"	15 my seun, gaan nie met hulle saam op die weg nie, hou jou voet terug van hulle pad;	",
"	16 want hulle voete hardloop na die besoedeling en haas hulle om bloed te vergiet;	",
"	17 want die net word tevergeefs uitgesprei voor die oë van allerhande vlieënde wesens:	",
"	18 so loer hulle op hul eie bloed, hulle lê hul siel voor.	",
"	19 So gaan dit met almal wat onregverdige wins maak: dit ontneem sy besitter die siel.	",
		
		
"	20 DIE Wysheid roep hardop daarbuite, Sy verhef haar stem op die pleine,	",
"	21 op die hoek van die rumoerige strate roep Sy, by die ingange van die Poorte, in die Stad, spreek Sy Haar woorde:	",
"	22 Hoe lank sal julle, eenvoudiges, die eenvoudigheid liefhê en die spotters lus hê om te spot en die dwase Kennis haat?	",
"	23 Wend julle tot My Teregwysing, dan laat ek My Gees vir julle uitstroom, wil Ek My woorde aan julle bekend maak.	",
"	24 Omdat Ek geroep en julle geweier het, Ek My Hand uitgestrek en niemand geluister het nie,	",
"	25 en julle al My Raad nie opgevolg en van My Teregwysing nie wou geweet het nie,	",
"	26 daarom sal Ek ook lag by julle ondergang, Ek sal spot as julle verskrikking kom;	",
"	27 as julle verskrikking kom soos ’n onweer, en julle ondergang soos ’n stormwind aankom, as benoudheid en angs julle oorval.	",
"	28 Dan sal hulle na My roep, maar Ek sal nie antwoord nie; hulle sal My soek, maar My nie vind nie.	",
"	29 Omdat hulle die Kennis gehaat en die Vrees van JaHWeH nie verkies het nie,	",
"	30 van My Raad nie wou weet nie, My Teregwysing verag het,	",
"	31 daarom sal hulle eet van die vrug van hulle wandel en versadig word van hulle planne.	",
"	32 Want hulle eie afkerigheid maak die eenvoudiges dood, en hulle eie sorgeloosheid rig die dwase te gronde;	",
"	33 maar die wat na My luister, sal veilig woon en gerus wees teen die vrese van besoedeling.	",
	
]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '2',
content: [
	
"	1 MY seun, as jy My Woorde aanneem en My Gebooie by jou bewaar,	",
"	2 sodat jy jou oor laat luister na Wysheid, jou hart neig tot Verstand;	",
"	3 ja, as jy na die Insig roep, na die Verstand jou stem verhef,	",
"	4 as jy Haar soek soos silwer en Haar naspeur soos verborge skatte	",
"	5 dan sal jy die Vrees van JaHWeH verstaan en die Kennis van Elohim vind	",
"	6 want JaHWeH gee Wysheid, uit Sy Mond kom Kennis en Verstand,	",
"	7 en Hy bewaar Wysheid vir die opregtes, Hy is ’n Skild vir die wat in rassuiwerheid wandel	",
"	8 deurdat Hy die Paaie van die Reg bewaak en die Weg van sy toegewydes bewaar;	",
"	9 dan sal jy Geregtigheid en Reg verstaan en regverdigheid - elke suiwer Pad.	",
"	10 Want Wysheid sal in jou hart kom, en Kennis vir jou siel lieflik wees;	",
"	11 Oorleg sal oor jou wag hou, Verstand sal jou bewaak,	",
"	12 om jou te red van die weg van besoedeling, van die man wat valse dinge spreek;	",
"	13 [van] die wat die Paaie van Opregtheid verlaat om op weë van Duisternis te wandel;	",
"	14 die wat hulle verheug in besoedeling, wat juig oor die valse streke van die besoedeldes,	",
"	15 wie se lewenswyse verdraaid is, en wat afwyk van die Weg;	",
"	16 om jou te red van die verbasterde vrou, van die Ontugtige wat met haar woorde vlei [Psalm 18:30]	",
"	17 wat die Vriend van haar jeug verlaat, en die Verbond van haar Elohey vergeet;	",
"	18 want haar huis sink weg na die Dood en haar paaie na die skimme;	",
"	19 almal wat by haar ingaan, kom nie terug nie en bereik die paaie van die lewe nie	",
"	20 sodat jy kan wandel op die Weg van Suiwerheid en die paaie van die regverdiges kan hou;	",
"	21 want die opregtes sal hul in die Aarde vestig, en die rassuiweres sal in haar oorbly,	",
"	22 maar die besoedeldes sal uit die Aarde uitgeroei, en die verraaiers sal uit haar weggeruk word.	",
	
]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '3',
content: [
		
"	1 MY seun, vergeet My Wet nie, en laat jou hart My Gebooie bewaar;	",
"	2 want hulle sal lengte van dae en jare van lewe en Vrede vir jou vermeerder.	",
"	3 Laat Medelye en Waarheid jou nie verlaat nie; bind Hulle om jou hals, skryf Hulle op die tafel van jou hart,	",
"	4 dan sal jy Barmhartigheid vind en suiwer Insig in die Oë van Elohim en die adam.	",
"	5 Vertrou op JaHWeH met jou hele hart en steun nie op jou eie insig nie.	",
"	6 Ken Hom in al jou weë, dan sal Hy jou paaie gelykmaak.	",
"	7 Wees nie wys in jou eie oë nie; vrees JaHWeH, en vermy besoedeling;	",
"	8 Sy sal genesing wees vir jou liggaam en verkwikking vir jou gebeente.	",
"	9 Vereer JaHWeH uit jou goed en uit die eerstelinge van al jou inkomste;	",
"	10 dan sal jou skure vol word van oorvloed en jou parskuipe oorloop van druiwesap.	",
"	11 My seun, verag die Tug van JaHWeH nie, en laat Sy Teregwysing nie jou weersin wek nie,	",
"	12 want JaHWeH tugtig hom wat Hy liefhet, ja, soos ’n vader die seun in wie hy behae het. [Hebreërs 12:6]	",
"	13 Verbly is die adamiet wat Wysheid gevind het, en die adamiet wat Verstand verkry;	",
"	14 want Haar wins is beter as dié van silwer, en Haar produkte suiwerder as goud;	",
"	15 Sy is kosteliker as robyne, en al jou kleinode kan nie met Haar mee vergelyk word nie.	",
"	16 In Haar regterhand is lengte van dae, in Haar linkerhand rykdom en Eer;	",
"	17 Haar Weë is lieflike Weë, en al Haar Paaie is Vrede.	",
"	18 Sy is die Lewensboom vir die wat Haar aangryp, en elkeen wat Haar vashou, sal reguit gaan. [Wysheid van Sirah 24:13; Génesis 3:22]	",
"	19 JaHWeH het deur Wysheid die Aarde gegrond, deur Verstand die Hemele vasgestel; [Wysheid van Salomo 9:9]	",
"	20 deur Sy Kennis het die Afgrond oopgebreek en het die wolke Dou gedrup.	",
"	21 My seun, laat Hulle nie uit jou oë wyk nie, bewaar Wysheid en oorleg.	",
"	22 dan sal Sy die lewe wees vir jou siel en ’n versiersel vir jou hals;	",
"	23 dan sal jy veilig jou weg bewandel en jou voet nie stamp nie;	",
"	24 as jy gaan lê, sal jy nie skrik nie, en lê jy, dan sal jou slaap soet wees.	",
"	25 Jy hoef nie bang te wees vir ’n skielike skrik, of vir die ondergang van die besoedelde as dit kom nie;	",
"	26 want JaHWeH sal jou Vertroue wees, en Hy sal jou voet bewaar vir die strik.	",
"	27 Hou ’n weldaad nie terug van hom aan wie dit toekom as dit in jou mag is om dit te doen nie.	",
"	28 Sê nie vir jou naaste nie: Gaan en kom terug, dan sal ek môre gee - terwyl jy dit het.	",
"	29 Bewerk geen besoedeling teen jou naaste terwyl hy vol vertroue by jou woon nie.	",
"	30 Twis nie sonder oorsaak met ’n adamiet as hy jou nie besoedel het nie.	",
"	31 Wees nie afgunstig op ’n man van geweld en verkies geeneen van sy weë nie.	",
"	32 Want die verkeerde is vir JaHWeH ’n gruwel, maar Sy Verborgenheid is met die opregtes.	",
"	33 Die vloek van JaHWeH is in die huis van die besoedelde, maar Hy seën die woning van die regverdiges.	",
"	34 As dit spotters betref, spot Hy, maar aan die ootmoediges gee Hy Barmhartigheid.	",
"	35 Die wyse sal Eer beërwe, maar die dwase behaal skande.	",
	
]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '4',
content: [
	
"	1 HOOR, julle seuns, na die Tug van die Vader, en luister om Insig te leer ken;	",
"	2 want Ek gee aan julle lering van Suiwerheid, verlaat nie My Wet nie.	",
"	3 Want toe Ek ’n Seun was by My Vader, teer en ‘n enigste voor My Moeder,	",
"	4 het HY My geleer en vir My gesê: Laat U hart MY Woorde vashou; onderhou MY Gebooie, dan sal U lewe.	",
"	5 Verkry Wysheid, verkry Insig; vergeet nie en wyk nie af van die Woorde van MY Mond nie;	",
"	6 verlaat Haar nie, dan sal Sy U bewaar; kry Haar lief, dan sal Sy U bewaak.	",
"	7 Die beginsel van die Wysheid is: Verwerf Wysheid en verwerf Insig deur al wat U besit.	",
"	8 Hou Haar hoog, dan sal Sy U verhoog; Sy sal U eer as U Haar omhels.	",
"	9 Sy sal ’n lieflike Krans gee vir U hoof, Sy sal U ’n sierlike Kroon verskaf. [Odes van Salomo 20:7]	",
"	10 Hoor, MY seun, en neem MY Woorde aan; dan sal die lewensjare vir U vermeerder word.	",
"	11 In die Weg van die Wysheid onderrig EK U, EK laat U die spore van opregtheid betree; [Odes van Salomo 1:3 - 4]	",
"	12 as U loop, sal U treë nie belemmer word nie, en as U hardloop, sal U nie struikel nie.	",
"	13 Hou vas aan die Tug, laat Haar nie los nie; bewaar Haar, want Sy is U lewe.	",
"	14 Kom nie op die pad van die besoedelde, en betree die weg van besoedeling nie.	",
"	15 Vermy haar, gaan nie daarop nie, wyk van haar af en gaan verby;	",
"	16 want hulle kan nie slaap as hulle geen kwaad doen nie; en hulle slaap is weg as hulle nie tot ’n val bring nie.	",
"	17 Want hulle eet brood van besoedeling en drink wyn van verkeerdheid. [Amos 2:8]	",
"	18 Terwyl die Weg van die regverdiges is soos ‘n helder Lig wat verlig soos dit gaan, totdat die dag opgerig is,	",
"	19 is die weg van die besoedelde soos Duisternis: hulle weet nie waaroor hulle sal struikel nie. [Exodus 10:23]	",
"	20 MY Seun, luister na wat EK sê, neig u oor tot MY Woorde,	",
"	21 laat hulle nie wyk uit U oë nie, bewaar hulle binne-in U hart.	",
"	22 Want hulle is die lewe vir die wat hulle vind, en ’n genesing vir hulle hele liggaam.	",
"	23 Bewaak U hart meer as alles wat bewaar moet word, want daaruit is die oorspronge van die lewe.	",
"	24 Verwyder van U die valsheid van mond, en hou ver van U af die verkeerdheid van lippe.	",
"	25 Laat U Oë reguit kyk en U Ooglede hulle reg voor U uit hou.	",
"	26 Maak die Weg van U voet gelyk, en laat al U Weë vas wees,	",
"	27 wyk nie regs of links af nie, hou U Voet ver van besoedeling.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '5',
content: [
		
"	1 MY seun, luister na My Wysheid, neig jou oor tot My Insig,	",
"	2 dat jy volle oorleg kan behou en jou lippe Kennis kan bewaar;	",
"	3 want die lippe van die verbasterde vrou drup heuningstroop, en haar verhemelte is gladder as olie,	",
"	4 maar op die end is sy bitter soos Alsem, soos ’n swaard aan weerskante skerp.	",
"	5 Haar voete daal na die Dood toe af, haar treë streef na die Doderyk/Sheol toe.	",
"	6 Dat sy die pad na die lewe nie sou inslaan nie, wankel haar gange sonder dat sy dit weet.	",
"	7 Luister dan nou na My, julle seuns, en wyk nie af van die Woorde van My Mond nie.	",
"	8 Hou jou weg ver van haar af, en kom nie naby die deur van haar huis nie,	",
"	9 sodat jy nie jou bottyd aan ander gee en jou jare aan een wat onbarmhartig is nie;	",
"	10 sodat verbasterdes hulle nie versadig met jou vermoë en jou moeitevolle arbeid in die huis van ’n uitlander kom nie	",
"	11 en jy uiteindelik moet steun as jou liggaam en jou vlees verteer is,	",
"	12 en moet sê: Hoe het ek die Tug gehaat en my hart die Teregwysing versmaad,	",
"	13 en nie geluister na die Stem van my Onderwysers en geen gehoor gegee aan Hulle wat my geleer het nie!	",
"	14 Amper was ek heeltemal in die besoedeling, in die vergadering by die samekoms.	",
"	15 Drink water uit jou eie Reënbak en strome uit jou eie Put.	",
"	16 Sal jou Fonteine buitentoe oorstroom, waterstrome op die pleine?	",
"	17 Hulle moet vir jou alleen wees en nie vir verbasterdes saam met jou nie. [MattithJaHûW 7:6]	",
"	18 Mag jou Fontein geseënd wees, en verheug jou oor die Vrou van jou jeug -	",
"	19 die liefdevolle Bokkie en Bergbokram; laat Haar borste jou altyd versadig, mag jy voortdurend van Haar Liefde bedwelmd wees.	",
"	20 Maar waarom sou jy, My seun, by ’n verbasterde vrou bedwelmd raak en die boesem van ’n Ontugtige omhels?	",
"	21 Want elke mens se weë is voor die Oë van JaHWeH, en Hy weeg al sy gange.	",
"	22 Sy eie Ongeregtigheid vang hom, die besoedelde, en in die vangstrikke van sy oortredinge word hy vasgehou.	",
"	23 Hy sal sterf deur gebrek aan Tug, en deur die grootheid van sy dwaasheid sal hy dwaal.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '6',
content: [
		
"	1 MY seun, as jy vir jou naaste borg gestaan het, en jou handpalm vir ’n verbasterde gegee het, [Spreuke 11:15]	",
"	2 verstrik is in die woorde van jou mond, gevang is deur die woorde van jou mond,	",
"	3 doen dan dit, My seun, om jouself te bevry - wanneer jy in die handpalms van jou vriend geval het - gaan onderwerp jouself en bemoedig jou vriend,	",
"	4 gun jou oë geen slaap en jou ooglede geen sluimering nie;	",
"	5 red jou soos ’n gemsbok uit die hand, en soos ’n voël uit die hand van ’n voëlvanger.	",
"	6 Gaan na die mier, luiaard, kyk na haar weë en word wys!	",
"	7 Wie vir haar geen aanvoerder, opsigter of heerser het nie,	",
"	8 maak haar brood klaar in die somer, bêre haar voedsel weg in die oestyd.	",
"	9 Hoe lank, luiaard, sal jy bly lê, wanneer sal jy opstaan uit jou slaap?	",
"	10 Nog ’n bietjie slaap, nog ’n bietjie sluimer, nog ’n bietjie hande vou om uit te rus!	",
"	11 So kom dan jou armoede soos ’n rondloper en jou gebrek soos ’n gewapende man.	",
"	12 ’n Adamiet van Belijaal, ’n wettelose is hy wat met ’n valse mond rondloop,	",
"	13 wat met sy oë knip, met sy voete beduie, met sy vingers tekens gee;	",
"	14 in wie se hart valse streke is, wat altyd besoedeling bewerk en tweedrag saai.	",
"	15 Daarom sal sy ondergang skielik kom, onvoorsiens sal hy verbreek word sonder dat daar genesing voor is.	",
"	16 Hierdie ses dinge haat JaHWeH, en sewe is vir SY Siel ’n gruwel:	",
"	17 trotse oë, ’n leuenagtige tong en hande wat onskuldige bloed vergiet,	",
"	18 ’n hart wat wettelose planne beraam, voete wat haastig na die besoedeling toe loop, [1 Ezra 1:26]	",
"	19 een wat as valse getuie leuens uitstrooi en tussen broers tweedrag saai.	",
		
		
"	20 BEWAAR, My seun, die Gebod van jou Vader, en verwerp die Wet van jou Moeder nie; [Wysheid van Salomo 6:18]	",
"	21 bind Haar voortdurend op jou hart, hang Haar om jou hals;	",
"	22 mag Sy jou lei as jy wandel, oor jou wag hou as jy slaap en jou toespreek as jy wakker word.	",
"	23 Want die Gebod is ’n lamp en die Wet is ’n Lig en die Teregwysing van die Tug ’n Weg tot die lewe, [Wysheid van Sirah 4:11-19]	",
"	24 om jou te bewaar vir die Vrou van Besoedeling, vir die gevlei van ’n volksvreemde vrou.	",
"	25 Begeer haar skoonheid nie in jou hart nie, en laat sy jou nie vang met haar ooglede nie;	",
"	26 want ‘n vrou hoereer vir ’n ronde brood, en ’n vrou van ‘n man maak jag op ’n kosbare siel.	",
"	27 Kan iemand vuur in sy skoot dra sonder dat sy klere verbrand?	",
"	28 Of kan iemand op gloeiende kole loop sonder dat sy voete brandwonde kry?	",
"	29 So is dit met hom wat by die vrou van sy naaste ingaan; elkeen wat haar aanraak, sal nie ongestraf bly nie.	",
"	30 ’n Dief word nie verag as hy steel om sy siel te bevredig nie, omdat hy honger het;	",
"	31 en as hy uitgevind word, moet hy sewevoudig vergoeding gee; al die goed van sy huis moet hy gee.	",
"	32 Hy wat vermeng, is sonder Verstand; hy wat sy eie siel wil verwoes, hy doen so iets;	",
"	33 slae en skande sal hy kry, en sy smaad sal nie uitgewis word nie;	",
"	34 want Jaloersheid is ’n Toorngloed in ’n vegter, en op die dag van wraak verskoon Hy nie; [Exodus 20:5]	",
"	35 Hy neem glad geen losprys in aanmerking nie, en Hy willig nie in nie al maak jy die omkoopgeskenk nog so groot.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '7',
content: [
		
"	1 MY seun, onderhou My woorde en bewaar My Gebooie by jou;	",
"	2 onderhou My Gebooie, dan sal jy lewe, en My Wet soos jou oogappel;	",
"	3 bind hulle aan jou vingers, skryf hulle op die tafel van jou hart.	",
"	4 Sê aan die Wysheid: U is my suster! en noem die Verstand [jou] vertroueling,	",
"	5 sodat Hulle jou kan bewaar van die verbasterde vrou, van die Ontugtige wat met haar woorde vlei.	",
"	6 Want Ek het deur die venster van My Huis, deur My tralievenster uitgekyk,	",
"	7 en Ek het onder die eenvoudiges gesien, onder die jongmense ’n jongman sonder Insig opgemerk,	",
"	8 wat op die straat verbygaan naby haar hoek en in die rigting van haar huis stap,	",
"	9 in die skemer, in die aand van die dag, in die middel van die nag en die donker.	",
"	10 En kyk, daar kom ’n vrou hom tegemoet, soos ’n hoer aangetrek en listig van hart -	",
"	11 sy is rumoerig en opstandig, haar voete kan nie in haar huis bly nie -	",
"	12 nou buitekant, dan weer op die pleine, en sy staan by elke hoek en loer.	",
"	13 En sy het hom gegryp en hom gesoen, met haar onbeskaamde gesig vir hom gesê:	",
"	14 Ek moes slagdiere as vergoeding bring, vandag het ek my geloftes betaal;	",
"	15 daarom het ek uitgegaan om jou te ontmoet, om jou aangesig te soek, en ek het jou gekry.	",
"	16 Ek het my bed met dekens opgemaak, met bont spreie van Egiptiese linne; [Boekrol van die Opregte 44:49; JeshaJaH 57:8]	",
"	17 ek het my bed besprinkel met mirre, alewee en kaneel -	",
"	18 kom, laat ons dronk word van liefde tot die môre toe, laat ons mekaar vrolik maak in welluste.	",
"	19 Want die man is nie tuis nie, hy het ver weg op reis gegaan,	",
"	20 die geldbeurs het hy met hom saamgeneem, teen die dag van volmaan sal hy eers tuis kom.	",
"	21 Sy het hom verlei deur haar baie mooipraatjies, deur die gladheid van haar lippe het sy hom verlok.	",
"	22 Hy loop skielik agter haar aan soos ’n bees wat na die slagpaal gaan, en met voetboeie wat dien tot Tugtiging van die sot,	",
"	23 totdat die pyl sy lewer splits; soos ’n voël haastig na die vangnet vlieg - sonder om te weet dat dit ten koste van sy siel is.	",
"	24 Luister dan nou na My, seuns, en luister na die Woorde van My Mond.	",
"	25 Laat jou hart nie afwyk na haar weë nie, dwaal nie rond in haar paaie nie.	",
"	26 Want baie is die gesneuweldes wat sy laat val het, en talryk almal wat deur haar vermoor is.	",
"	27 Haar huis is weë na die Doderyk/Sheol, wat afdaal na die kamers van die Dood. [Boekrol van Henog 22:2]	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '8',
content: [
		
"	1 ROEP die Wysheid nie, en verhef die Verstand nie Haar Stem nie?	",
"	2 Op die top van die verhewe plekke langs die Weg, op die kruispunt van die Paaie staan Sy,	",
"	3 aan die kant van die Poorte by die uitgang van die Stad, by die ingang van die deure roep Sy hardop:	",
"	4 Ek roep na julle, manne, en My Stem is tot die seuns van die Adam.	",
"	5 Leer tog skranderheid verstaan, eenvoudiges, en dwase, leer verstandigheid verstaan.	",
"	6 Hoor, want Ek sal voortreflike dinge spreek, en My Lippe gaan oop vir wat Reg is.	",
"	7 Want My verhemelte spreek Waarheid, en besoedeling is vir My Lippe ’n gruwel.	",
"	8 Al die Woorde van My Mond is Geregtigheid; geen verdraaidheid of valsheid nie,	",
"	9 hulle is almal duidelik vir die verstandige en Reg vir die wat Kennis gevind het.	",
"	10 Neem My Tug aan, en nie silwer nie, en Kennis liewer as uitgesoekte goud.	",
"	11 Want Wysheid is suiwerder as robyne, en al die kleinode kan nie met Haar vergelyk word nie.	",
"	12 Ek, Wysheid, is vertroud met die skranderheid, en Ek vind Kennis van regte Oorleg.	",
"	13 Die Vrees van JaHWeH is om te haat wat besoedel is; hoogmoed en trotsheid en ’n besoedelde wandel en ’n huigelagtige mond haat Ek.	",
"	14 Raad en Wysheid is Myne, Ek is die Insig, Sterkte is Myne.	",
"	15 Deur My regeer die konings en skryf die maghebbers wetgewing van Geregtigheid;	",
"	16 deur My heers die vorste en die edeles, al die regters van die Aarde.	",
"	17 Ék het lief die wat My liefhet, en die wat My soek, sal My vind.	",
"	18 Rykdom en Eer is by My, duursame goed en Geregtigheid.	",
"	19 My vrug is suiwerder as goud en as fyn goud, en My opbrengs as uitgesoekte silwer.	",
"	20 Ek wandel op die Weg van Geregtigheid, in die middel van die Paaie van Reg,	",
"	21 om die wat My liefhet, ’n besitting te laat erwe, en hulle skatkamers maak Ek vol.	",
		
		
"	22 JaHWeH het My berei as eersteling van Sy Weg, voor Sy werke, van ouds af. [Wysheid van Sirah 24]	",
"	23 Van ewigheid af is Ek geformeer, van die begin af, van die voortyd van die Aarde af.	",
"	24 Toe daar nog geen Afgrond was nie, is Ek gebore; toe Fonteine, swaar van water, nog nie daar was nie;	",
"	25 voordat die berge ingesink het, voor die heuwels is Ek gebore;	",
"	26 toe HY die Aarde en die velde en al die stoffies van die wêreld nog nie gemaak het nie.	",
"	27 Toe HY die Hemele berei het, was Ek daar; toe HY ’n kring afgetrek het op die aangesig van die Afgrond;	",
"	28 toe HY die Hemele daarbo versterk het, toe die Fonteine van die Afgrond versterk was;	",
"	29 toe HY vir die see sy grens gestel het, dat die waters SY bevel nie sou oortree nie; toe HY die fondamente van die Aarde vasgelê het -	",
"	30 toe was Ek by HOM, soos een wat opgelei word en Ek was dag vir dag vol verlustiging en het gespeel voor SY Aangesig altyd,	",
"	31 en het gespeel op die bewoonde deel van SY Aarde, en My verlustiginge was met die seuns van adam.	",
"	32 Luister dan nou na My, seuns; want geseënd is hulle wat My Weë bewaar.	",
"	33 Luister na Tug en word wys, en verwerp Haar nie.	",
"	34 Geseënd is die adamiet wat na My luister, om dag vir dag te waak aan My deure, by die syposte van My Poorte die wag te hou.	",
"	35 Want hy wat My vind, het die lewe gevind en verkry Vreugde van JaHWeH.	",
"	36 Maar hy wat My nie vind nie, benadeel sy eie siel; almal wat My haat, het die Dood lief.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '9',
content: [
		
"	1 DIE Wysheid het Haar Huis gebou, Haar sewe Pilare uitgekap, [Openbaring van Henog 11:40]	",
"	2 Haar slagvee geslag, Haar wyn gemeng, ook Haar tafel gedek.	",
"	3 Sy het Haar Diensmeisies uitgestuur, Sy nooi uit op die hange van die verhewe plekke van die Stad: [Spreuke 31:15; Hooglied 6:8; DaniEl 13:15]	",
"	4 Wie eenvoudig is, laat hy inkom hierheen, wie verstandeloos is, vir hom sê Sy:	",
"	5 Kom, eet julle van My Brood, en drink van die Wyn wat Ek gemeng het;	",
"	6 laat staan die eenvoudigheid, dan sal julle lewe, en betree die Weg van Verstand.	",
"	7 Hy wat ’n spotter teregwys, behaal vir homself skande, en hy wat ’n besoedelde bestraf, bevlek homself.	",
"	8 Bestraf ’n spotter nie, anders haat hy jou; bestraf ’n wyse, en hy sal jou liefhê.	",
"	9 Deel mee aan die wyse, en hy sal nog wyser word, leer die regverdige, en hy sal Insig vermeerder.	",
"	10 Die beginsel van die Wysheid is die Vrees van JaHWeH, en Kennis van die apartes is Verstand.	",
"	11 Want deur My word jou dae meer en word jare van lewe vir jou toegevoeg.	",
"	12 As jy wys is, is jy wys tot jou voordeel, en is jy ’n spotter, dan moet jy dit alleen dra.	",
"	13 Vrou Dwaasheid is onrustig, pure eenvoudigheid en heeltemal onkundig; [Boekrol van Henog 42:3]	",
"	14 en sy sit by die deur van haar huis, op ’n stoel op die verhewe plekke van die Stad,	",
"	15 om te nooi die wat op die Weg verbygaan, die wat op hulle Paaie reguit wandel:	",
"	16 Wie eenvoudig is, laat hy inkom hierheen! En die verstandelose, aan hom sê sy:	",
"	17 Gesteelde waters is soet, en brood in die geheim [geëet], is lekker.	",
"	18 Maar hy weet nie dat daar skimme is, dat haar genooides in die dieptes van die Doderyk/Sheol is nie.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '10',
content: [
		
"	1 DIE spreuke van Salomo. ’n Wyse seun verbly die Vader, maar ’n dwase seun is ’n bekommernis vir sy Moeder.	",
"	2 Skatte deur besoedelde winsbejag bring geen voordeel nie, maar Geregtigheid red van Dood.	",
"	3 JaHWeH laat die regverdige nie honger ly nie, maar die verderflikheid van die besoedelde stoot Hy weg.	",
"	4 Hy word arm wat met ’n trae handpalm werk, maar die hand van die vlytiges maak ryk.	",
"	5 Hy wat in die somer wegbêre, is ’n verstandige seun; hy wat vas slaap in die oestyd, is ’n seun wat skande maak. [MattithJaHûW 9:37]	",
"	6 Seëninge is daar op die hoof van die regverdige, maar geweld skuil in die mond van die besoedelde.	",
"	7 Die nagedagtenis van die regverdige is tot seën, maar die naam van die besoedelde vergaan.	",
"	8 Hy wat wys van hart is, neem die Gebooie aan, maar hy wat dwaas van lippe is, kom tot ’n val.	",
"	9 Hy wat in egtheid wandel, wandel veilig, maar hy wat sy weë krom maak, word bekend.	",
"	10 Hy wat met sy oog knip, veroorsaak smart, en hy wat dwaas spreek, kom tot ’n val.	",
"	11 Die mond van die regverdige is ’n fontein van lewe, maar geweld skuil in die mond van die besoedelde.	",
"	12 Haat verwek twiste, maar liefde bedek al die oortredinge.	",
"	13 Op die lippe van die verstandige word Wysheid gevind, maar die roede is vir die rug van die verstandelose.	",
"	14 Die wyse lê kennis weg, maar die mond van die dwaas is ’n ondergang wat naby is.	",
"	15 Die goed van die ryke is vir hom ’n sterk stad; die ondergang van die behoeftiges is hulle armoede.	",
"	16 Wat die regverdige verwerf, is vir die lewe; die inkomste van die besoedelde is tot oortreding.	",
"	17 ’n Pad ten lewe is hy wat die Tug in ag neem; maar hy wat die Teregwysing verontagsaam, raak verdwaald.	",
"	18 Hy wat haat verberg, het valse lippe; en hy wat skindertaal uitstrooi, is ’n dwaas.	",
"	19 By veelheid van woorde ontbreek die oortreding nie; maar hy wat sy lippe inhou, handel verstandig.	",
"	20 Die tong van die regverdige is uitgesoekte silwer; die hart van die besoedelde is min werd. [Psalm 12:6]	",
"	21 Die lippe van die regverdige help baie mense reg; maar die dwase sterf deur gebrek aan Verstand.	",
"	22 Die Seën van JaHWeH - Sy maak ryk, en moeitevolle arbeid voeg niks by Haar nie.	",
"	23 Dit is vermaak vir ’n dwaas om bloedvermenging te pleeg, maar ‘n man van Wysheid het Verstand.	",
"	24 Waar die besoedelde bang voor is - dit kom oor hom; maar die begeerte van die regverdiges vervul Hy.	",
"	25 Wanneer ’n stormwind verbygaan, is die besoedelde nie meer nie; maar die regverdige is vir ewig gegrondves.	",
"	26 Soos asyn vir die tande en soos rook vir die oë, so is die luiaard vir die wat hom stuur.	",
"	27 Die Vrees van JaHWeH vermeerder die dae, maar die jare van die besoedelde word verkort.	",
"	28 Die verwagting van die regverdiges is vreugde, maar die hoop van die besoedelde vergaan.	",
"	29 Die Weg van JaHWeH is vir die egte ’n vesting, maar ’n ondergang vir die bewerkers van Ongeregtigheid.	",
"	30 Die regverdige sal vir ewig nie wankel nie, maar die besoedelde sal in die Aarde nie bly woon nie.	",
"	31 Die mond van die regverdige laat Wysheid uitspruit, maar die valse tong word uitgeroei.	",
"	32 Die lippe van die regverdige ken vreugde, maar die mond van die besoedelde is pure valsheid.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '11',
content: [
		
"	1 ‘N VALSE weegskaal is vir JaHWeH ’n gruwel, maar in ’n volle gewig het HY behae.	",
"	2 Kom die hoogmoedigheid, dan kom die skande, maar by die beskeie is Wysheid.	",
"	3 Die opregtheid van die opregtes is vir hulle ’n riglyn, maar die valsheid van die verraaiers vernietig hulle.	",
"	4 Goed bring geen voordeel op die dag van die Grimmigheid nie, maar Geregtigheid red van die Dood.	",
"	5 Die Geregtigheid van die rassuiwere rig sy lewenswandel, maar die besoedelde val deur sy besoedeling.	",
"	6 Die Geregtigheid van die opregtes red hulle, maar deur hulle eie verderflikheid word die verraaiers uitgevang.	",
"	7 Wanneer die Dood die besoedelde adamiet neem, gaan sy hoop tot niet, en die verwagting van die roekelose vergaan.	",
"	8 Word die regverdige uit die benoudheid gered, dan kom die besoedelde in sy plek.	",
"	9 Deur sy mond stort die tweegesig sy naaste in die verderf, maar deur Kennis word die regverdiges gered.	",
"	10 Oor die voorspoed van die regverdiges jubel ’n Stad, en as die besoedelde omkom, is daar gejubel.	",
"	11 Deur die Seën van die opregtes gaan ’n Stad vooruit, maar deur die mond van die besoedelde word sy afgebreek.	",
"	12 Die verstandelose verag sy naaste, maar ’n verstandige man bly stil.	",
"	13 Die wat met kwaadsprekery omgaan, maak ’n geheim openbaar, maar hy wat betroubaar is van gees, bedek ’n saak.	",
"	14 As daar nie suiwer oorleg is nie, val ’n volk; maar in die veelheid van raadgewers is redding.	",
"	15 Hy wat vir ’n verbasterde borg gestaan het, sal vernietig word deur die besoedeling; maar hy wat borgskap haat, is veilig. [Spreuke van Salomo 6:1]	",
"	16 ’n Aanvallige vrou verkry eer, en die geweldenaars verkry rykdom.	",
"	17 ’n Man wat medelye betoon, doen goed aan sy eie siel, maar ’n wreedaard pynig sy eie vlees.	",
"	18 Die besoedelde behaal oneerlike wins, maar hy wat Geregtigheid saai, verkry Waarheid as loon.	",
"	19 Geregtigheid lei tot die lewe, maar hy wat die besoedeling najaag, jaag na die Dood.	",
"	20 Verbasterde neigings is vir JaHWeH ’n gruwel; maar Hy het behae in die wat rassuiwer wandel.	",
"	21 Sekerlik, die besoedelde bly nie ongestraf nie; maar die saad van regverdiges raak vry.	",
"	22 ’n Goue ring in ’n vark se snuit, [so is] ’n vrou wat mooi is, maar sonder beleid.	",
"	23 Die begeerte van die regverdiges is tot suiwerheid, [maar] die hoop van die besoedelde is ’n strafgerig van toorn.	",
"	24 Daar is een wat ruim uitdeel en nog meer kry, en een wat terughou meer as wat reg is, maar tot sy gebrek.	",
"	25 Die siel wat seën, word versadig; en hy wat laaf, word self ook gelaaf.	",
"	26 Hy wat koring terughou, hom vloek die gemeenskap; maar seëning kom op die hoof van hom wat koring verkoop.	",
"	27 Wie Suiwerheid nastreef, soek wat welgevallig is; maar hy wat Besoedeling soek, oor hom sal sy kom.	",
"	28 Wie op sy rykdom vertrou, dié sal val; maar die regverdiges sal soos blare uitspruit.	",
"	29 Wie sy huis in beroering bring, sal die gees erwe, en ’n dwaas word ’n slaaf van hom wat wys van hart is.	",
"	30 Die vrug van die regverdige is die Boom van die Lewe, en hy wat siele win, is wys.	",
"	31 As die regverdige op Aarde vergelding ontvang, hoeveel te meer die besoedelde en die oortreder!	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '12',
content: [
		
"	1 EEN wat die Tug liefhet, het Kennis lief; maar wie die Teregwysing haat, is dom.	",
"	2 Die suiwere verkry ’n Vreugde van JaHWeH, maar HY besoedel ’n slinkse man.	",
"	3 Geen adamiet kan deur besoedeling opgerig word nie, maar die wortel van die regverdiges wankel nie.	",
"	4 ’n Deugsame vrou is die kroon van haar man, maar een wat skande maak, is soos ’n verrotting in sy gebeente.	",
"	5 Die denke van die regverdiges is Reg, die advies van die besoedelde is bedrog.	",
"	6 Die woorde van die besoedelde is om te loer op bloed, maar die mond van die opregtes red hulle.	",
"	7 Die besoedelde mense word omgekeer, en hulle is daar nie meer nie; maar die huis van die regverdiges bly staan.	",
"	8 Ooreenkomstig sy Insig word ’n man geprys; maar ’n verkeerde van hart sal verag word.	",
"	9 Wie gering geag word en ’n slaaf het, is beter as hy wat hom vernaam aanstel en gebrek aan brood het.	",
"	10 Die regverdige ken die siel van sy dier, maar die barmhartigheid van die besoedelde is wreed.	",
"	11 Wie sy Adamah [die adamiet se Aarde] bewerk, het volop brood; maar hy wat nietighede najaag, het gebrek aan Verstand.	",
"	12 Die besoedelde begeer die net van besoedeling, maar die wortel van die regverdiges lewer [vrugte] op.	",
"	13 By die oortreding van die lippe, word jy verstrik deur besoedeling; maar die regverdige ontkom aan die benoudheid.	",
"	14 Uit die vrug van iemand se mond word hy versadig met die suiwere, en die daad van ’n adamiet se hande kom op hom terug.	",
"	15 Die weg van ’n dwaas is reg in sy eie oë, maar die wyse luister na raad.	",
"	16 Die dwaas laat sy drif op die daad bekend word, maar die skrandere verberg skande.	",
"	17 Hy wat die in Getrouheid spreek, bring Regverdigheid voort; maar ’n valse getuie bedrog.	",
"	18 Daar is een wat onverskillig woorde uitspreek soos swaardsteke, maar die tong van die wyse is genesing.	",
"	19 ’n lip van Waarheid sal vir ewig gevestig word, maar ’n valse tong vir ’n oomblik.	",
"	20 Bedrog is in die hart van die wat besoedeling bewerk; maar die wat Vrede aanraai, het Vreugde.	",
"	21 Geen enkele ramp tref die regverdige nie, maar die besoedelde is vervul met besoedeling.	",
"	22 Valse lippe is vir JaHWeH ’n gruwel, maar Hy het ’n welbehae in die wat in Getrouheid handel.	",
"	23 ’n Skrander adamiet verberg sy Kennis, maar die hart van die dwase roep [hulle] sotheid uit.	",
"	24 Die hand van die vlytiges sal heers, maar traagheid lei tot dwangarbeid.	",
"	25 Bekommernis in die hart van ’n mens druk dit neer, maar ’n suiwer woord vrolik dit op.	",
"	26 Die regverdige vind sy weg uit, maar die weg van die besoedelde laat hulle dwaal.	",
"	27 Hy wat traag is, jaag sy wild nie op nie, maar vlyt is ’n kosbare skat vir ’n adamiet.	",
"	28 Op die Weg van Geregtigheid is lewe, en [in] die rigting van dié pad is geen dood.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '13',
content: [
		
"	1 ’N WYSE seun luister na die Tug van die Vader, maar ’n spotter hoor nie na berisping nie.	",
"	2 Van die vrug van ‘n man se mond eet hy die suiwere, maar die siel van die verraaiers is vals.	",
"	3 Wie sy mond bewaak, bewaar sy siel; wie sy lippe wyd oopmaak, vir hom is daar ondergang.	",
"	4 Die siel van die luiaard begeer, en daar is niks nie, maar die siel van die vlytiges word versadig.	",
"	5 Die regverdige haat leuentaal, maar die besoedelde maak gehaat en handel skandelik.	",
"	6 Geregtigheid bewaar die opregte van wandel, maar besoedeling bring die oortreder tot ’n val.	",
"	7 Daar is een wat hom ryk hou, en hy het glad niks nie; een wat hom arm hou, en hy het baie goed.	",
"	8 Die losprys vir die siel van ’n man is sy rykdom, maar die arme hoor geen dreigement nie.	",
"	9 Die Lig in die regverdige brand vrolik, maar die lamp in die besoedelde gaan dood.	",
"	10 Hoogmoed gee net getwis af; maar by die wat hulle laat inlig, is Wysheid.	",
"	11 Goed wat uit niks verkry is, word minder; maar hy wat met die hand bymekaarmaak, kry altyd meer.	",
"	12 ’n Uitgestelde hoop maak die hart siek; maar ’n wens wat uitkom, is die Boom van die Lewe.	",
"	13 Wie die Woord verag, moet dit ontgeld; maar hy wat die Gebod Vrees, ontvang vergelding.	",
"	14 Die Wet van die wyse is ’n Fontein van die lewe, om die strikke van die Dood te ontwyk.	",
"	15 ’n Suiwer Verstand verskaf Guns, maar die weg van die verraaiers is permanent.	",
"	16 Elke skrandere handel met Kennis, maar die dwaas strooi sotheid rond.	",
"	17 ’n besoedelde boodskapper val in die besoedeling, maar ’n betroubare gesant is genesend.	",
"	18 Armoede en skande is vir hom wat die Tug verwerp; maar hy wat Teregwysing in ag neem, word geëer.	",
"	19 ’n Vervulde wens is soet vir die siel, maar om af te wyk van besoedeling, is ’n gruwel vir die dwase.	",
"	20 Gaan met die wyse om, dan word jy wys; maar hy wat met dwase verkeer, versleg.	",
"	21 Die besoedeling agtervolg die oortreders, maar Hy sal die regverdiges tot Suiwerheid herstel.	",
"	22 ’n Suiwere laat sy kindskinders erwe, maar die vermoë van die oortreder word vir die regverdige weggebêre.	",
"	23 Die braakland van die armes [lewer] oorvloedig spys op, maar daar is wat deur Reg verlore gaan.	",
"	24 Wie sy roede terughou, haat sy seun; maar hy wat hom liefhet, besoek hom met Tugtiging.	",
"	25 Die regverdige eet totdat sy siel versadig is; maar die maag van die besoedelde ly gebrek.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '14',
content: [
		
"	1 DIE Wysheid van die Vroue bou die huis, maar die sotheid breek hom met eie hande af.	",
"	2 Wie in sy opregtheid wandel, vrees JaHWeH; maar hy wat verkeerd is in sy weë, verag HOM.	",
"	3 In die mond van die ligsinnige is ’n lat vir sy snobisme, maar die lippe van die wyse bewaar hulle.	",
"	4 Waar geen beeste is nie, is die krip leeg, maar deur die krag van die os is die inkomste baie.	",
"	5 ’n Betroubare getuie lieg nie, maar ’n valse getuie strooi leuens uit.	",
"	6 Die spotter soek Wysheid, en Sy is nie daar nie; maar vir die verstandige is Kennis maklik.	",
"	7 Gaan weg voor ’n dwase man, want jy het daar niks gemerk van die lippe van Kennis nie.	",
"	8 Die Wysheid van die skrandere is om Haar Weg te verstaan, maar die sotheid van die dwase is bedrog.	",
"	9 ‘n Dwase spot met die oortreding, maar tussen die opregtes is daar Vreugde.	",
"	10 Die hart ken [die] bitterheid van sy siel, en in sy blydskap kan ’n verbasterde hom nie inmeng nie.	",
"	11 Die huis van die besoedelde word verdelg, maar die Tent van die opregtes bot.	",
"	12 Daar is ’n weg wat vir ’n mens reg lyk, maar die einde daarvan is weë van die Dood.	",
"	13 Ook onder gelag kan die hart pyn ly, en die einde van so ’n blydskap is bekommernis.	",
"	14 Uit sy eie wandel word die verkeerde van hart versadig, maar die suiwer man uit syne.	",
"	15 Die eenvoudige glo elke woord, maar die skrandere let op sy voetstappe.	",
"	16 Die wyse vrees en wyk af van besoedeling, maar die dwaas bruis op en is vol selfvertroue.	",
"	17 Wie kortgebonde is, begaan sotheid; en ’n slinkse man word gehaat.	",
"	18 Die eenvoudiges verkry sotheid as ’n erfenis, maar die skranderes word met Kennis gekroon.	",
"	19 Die besoedeling moet buig voor die suiwerheid, en die besoedelde by die Poorte van die regverdige.	",
"	20 Die arme word selfs deur sy volksgenote gehaat, maar die vriende van die ryke is talryk.	",
"	21 Wie sy naaste verag, oortree; maar hy wat medelye het met die ellendiges, hy is geseënd.	",
"	22 Verdwaal hulle nie wat besoedeling bewerk nie? Maar Medelye en Waarheid is vir die wat suiwerheid bewerk.	",
"	23 In enige moeitevolle arbeid is voordeel, maar praatjies is net tot gebrek.	",
"	24 Die kroon van die wyse is hulle rykdom, die sotheid van die dwase bly sotheid.	",
"	25 ’n Getuie in Waarheid red siele, maar hy wat leuens uitblaas, bedrieg.	",
"	26 In die Vrees van JaHWeH lê ’n sterk sekerheid, ook vir die kinders van ’n sodanige sal daar ’n toevlug wees.	",
"	27 Die Vrees van JaHWeH is ’n Fontein van die Lewe, om van die strikke van die Dood af te wyk.	",
"	28 In die menigte van die volk lê die versiering van die koning, maar in die gebrek aan ‘n gemeenskap, die einde van die vors.	",
"	29 Die lankmoedige is groot van Verstand, maar die opvlieënde van gees behaal sotheid.	",
"	30 ’n Rustige hart is die lewe vir die vlees, maar hartstog ’n verrotting vir die gebeente.	",
"	31 Wie die geringe verdruk, versmaad sy Maker, maar hy wat hom oor die behoeftige ontferm, eer Hom.	",
"	32 In sy besoedeling word die besoedelde omgestoot, maar die regverdige vind ’n toevlug by sy dood.	",
"	33 Wysheid rus in die hart van die verstandige, word selfs rugbaar te midde van die dwase.	",
"	34 Geregtigheid verhoog ’n nasie, maar ongehoorsaamheid is ’n skandvlek vir die gemeenskappe.	",
"	35 Die welbehae van die koning is vir ’n verstandige dienaar, maar een wat skande maak, is ’n voorwerp van sy grimmigheid.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '15',
content: [
		
"	1 ‘N SAGTE antwoord keer die grimmigheid af, maar 'n krenkende woord laat die toorn opkom.	",
"	2 Die tong van die wyse getuig van grondige Kennis, maar die mond van die dwase laat sotheid uitborrel.	",
"	3 Op elke plek is die Oë van JaHWeH, en Hulle beskou opmerksaam die besoedeldes en die suiweres.	",
"	4 Sagtheid van tong is ’n Boom van die Lewe, maar valsheid in haar is verbreking in die gees.	",
"	5 Die sot verag die tug van sy Vader, maar hy wat op Teregwysing ag gee, word wys.	",
"	6 In die huis van die regverdige is ’n groot skat, maar in die inkomste van die besoedelde is verwarring.	",
"	7 Die lippe van die wyse strooi Kennis uit, maar die hart van die dwase is nie reg nie.	",
"	8 Die slagdier van die besoedelde is vir JaHWeH ’n gruwel, maar die gebed van die opregtes is Hom welgevallig.	",
"	9 Die wandel van die besoedelde is vir JaHWeH ’n gruwel, maar hom wat Geregtigheid najaag, het Hy lief.	",
"	10 Tugtiging is gruwelik vir hom wat die pad verlaat; hy wat Teregwysing haat, sal sterwe.	",
"	11 die Doderyk/Sheol en Abáddon lê voor die Aangesig van JaHWeH, hoeveel te meer die harte van die seuns van adam!	",
"	12 Die spotter hou nie daarvan dat ’n mens hom bestraf nie, hy gaan nie na die wyse toe nie.	",
"	13 ’n Vrolike hart maak die aangesig bly, maar by verdriet van die hart is die gees neerslagtig.	",
"	14 Die hart van die verstandige soek na Kennis, maar die mond van die dwase gaan met sotheid om.	",
"	15 Al die dae van die bedrukte [van hart] is besoedel, maar die suiwere van hart vier voortdurend fees.	",
"	16 Liewer ’n bietjie in die Vrees van JaHWeH, as ’n groot skat en onrus daarby.	",
"	17 Suiwerder is liefde met ’n porsie groente, as ’n vetgevoerde bees en haat daarby.	",
"	18 ’n Driftige man verwek twis, maar die lankmoedige laat die geskil bedaar.	",
"	19 Die weg van die luiaard is soos ’n heining van dorings, maar die Weg van die opregtes is reggemaak.	",
"	20 ’n Wyse seun verbly sy Vader, maar ’n dwase adamiet verag sy Moeder.	",
"	21 Sotheid is ’n vreugde vir die verstandelose, maar ’n man van Verstand wandel reguit.	",
"	22 Planne misluk sonder beraad-slaging, maar deur die veelheid van Raadgewers kom dit tot stand.	",
"	23 ’n Man het blydskap in die antwoord van sy mond, en hoe suiwer is [die regte] woord op sy tyd!	",
"	24 Die Weg van die lewe gaan vir die verstandige na bowe, sodat hy die Doderyk/Sheol daaronder ontwyk.	",
"	25 JaHWeH ruk die huis van die trotsaards om, maar die grenslyn van die weduwee stel Hy vas.	",
"	26 Die gedagtes van die besoedelde is vir JaHWeH ’n gruwel, maar die woorde van ‘n suiwere is aangenaam.	",
"	27 Wie onregverdige wins maak, bring sy huis in beroering; maar hy wat geskenke haat, sal lewe.	",
"	28 Die hart van die regverdige dink ná om te antwoord, maar die mond van die besoedelde laat besoedeling uitborrel.	",
"	29 JaHWeH is ver van die besoedelde, maar die gebed van die regverdiges hoor Hy.	",
"	30 Stralende oë verbly die hart; ’n suiwer nuus maak die gebeente vet.	",
"	31 Die oor wat na die Teregwysing tot die lewe luister, sal onder die wyse vertoef.	",
"	32 Hy wat die Tug verwerp, ag sy siel gering; maar hy wat na die Teregwysing luister, verkry Verstand.	",
"	33 Die Vrees van JaHWeH is die Tug van die Wysheid, en nederigheid gaan die eer vooraf.	",
		

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '16',
content: [
		
"	1 DIE planne van die hart is van die adamiet, maar die antwoord van die tong kom van JaHWeH.	",
"	2 Al die weë van ’n man is suiwer in sy oë, maar die Geeste van JaHWeH toets.	",
"	3 Laat jou werke aan JaHWeH oor, dan sal jou planne uitgevoer word.	",
"	4 Alles het JaHWeH gemaak vir Sy doel, ja, ook die Besoedelde vir die dag van besoedeling.	",
"	5 Elke hoogmoedige van hart is vir JaHWeH ’n gruwel; sekerlik, hy sal nie ongestraf bly nie.	",
"	6 Deur Medelye en Waarheid word die skuld versoen, en deur die Vrees van JaHWeH wyk ’n [persoon] af van besoedeling.	",
"	7 As JaHWeH behae het in die weë van ’n man, dan laat Hy selfs sy vyande met hom vrede hou. [Psalm 1]	",
"	8 Suiwerder is ’n bietjie deur Geregtigheid, as ’n menigte van inkomste sonder Reg.	",
"	9 Die hart van die adamiet dink sy weg uit, maar JaHWeH rig sy voetstappe.	",
"	10 Die beslissing is op die lippe van die koning; in die Regspraak handel sy mond nie ontrou nie.	",
"	11 ’n weegtoestel en weegskaal van Reg kom van JaHWeH, al die weegstene in die sak is Sy werk.	",
"	12 Dit is ’n gruwel vir konings om besoedeling voort te bring, want die troon word deur Geregtigheid bevestig.	",
"	13 Die konings het behae in regverdige lippe, en hulle het hom lief wat Geregtigheid spreek.	",
"	14 Die Grimmigheid van die Koning is boodskappers van die dood, maar ’n wyse man bring dit tot bedaring.	",
"	15 In die Lig van die Koning is lewe, en Sy Vreugde is die wolk van laat reëns. [JôWEl 2:23]	",
"	16 Hoeveel beter is dit om Wysheid te verkry as goud, en verkiesliker om Verstand te verwerf as silwer.	",
"	17 Die gemaakte Weg van die opregtes is om van besoedeling af te wyk; hy wat op sy wandel ag gee, bewaar sy siel.	",
"	18 Trotsheid kom voor die verbreking, en ‘n hoogmoedige gees kom voor die val.	",
"	19 Dit is beter om nederig van gees te wees saam met die ootmoediges, as om buit te verdeel met die trotsaards.	",
"	20 Wie ag gee op die Woord, sal Suiwerheid vind; en hy wat op JaHWeH vertrou, is geseënd.	",
"	21 ’n Wyse van hart word verstandig genoem, en soetheid van lippe vermeerder die lering.	",
"	22 ’n Fontein van die lewe is die Verstand vir sy meester, maar die tugtiging van die sotte is sotheid.	",
"	23 Die hart van die wyse maak sy mond verstandig en vermeerder die lering op sy lippe.	",
"	24 Vriendelike woorde is soos ’n heuningkoek: soet vir die siel en ’n genesing vir die gebeente.	",
"	25 Daar is ’n weg wat vir ’n mens reg lyk, maar die einde daarvan is weë van die Dood.	",
"	26 Die siel van die werkende man arbei vir hom, want sy mond jaag hom aan.	",
"	27 ’n Man van Belijaal grawe besoedeling uit, en sy lippe is brandende vuur.	",
"	28 ’n Man van valse streke saai tweedrag, en ’n kwaadstoker skei vriende van mekaar.	",
"	29 ’n Man van geweld verlei sy volksgenote en lei hom op ’n weg wat nie suiwer is nie.	",
"	30 Hy wat sy oë toemaak om valsheid te bedink, wat sy lippe vasknyp, het die besoedeling alreeds gepleeg.	",
"	31 Grysheid is ’n sierlike kroon; dit word gevind op die Weg van Geregtigheid. [Psalm 18:30]	",
"	32 Die lankmoedige is suiwerder as ’n dappere; en hy wat sy gees beheers, as een wat ’n stad inneem.	",
"	33 In die skoot word die lot gewerp, maar elke Regspraak daarvan kom van JaHWeH.	",
		

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '17',
content: [
		
"	1 BETER is ’n stuk droë brood en rus, as ’n huis vol slagdiere met getwis in haar.	",
"	2 ’n Verstandige dienaar sal heers oor ’n seun wat skande maak, en onder die broers sal hy die erfenis verdeel.	",
"	3 Die smeltkroes is vir die silwer en die oond vir die goud, maar JaHWeH toets die harte.	",
"	4 Die afbreker gee ag op wettelose lippe, ’n leuenaar gee gehoor aan ’n tong wat verderflikheid saai.	",
"	5 Hy wat die arme bespot, versmaad sy Maker; hy wat bly is oor ’n ongeluk, sal nie ongestraf bly nie.	",
"	6 Kindskinders is ’n kroon vir grysaards, en vir die kinders is hulle vader ’n eer.	",
"	7 Aanmatigende taal pas nie by ’n dwaas nie, hoeveel minder leuentaal by ’n edele!	",
"	8 Kosbare edelgesteentes is die omkoopgeskenk in die oë van sy besitter; oral waar hy heengaan, sal hy slaag.	",
"	9 Wie ’n oortreding bedek, soek liefde; maar hy wat ’n saak weer ophaal, skei vriende van mekaar. [Lukas 6:37]	",
"	10 ’n Berisping gaan by ’n verstandige dieper in as om ’n dwaas honderd maal te slaan.	",
"	11 Die besoedelde wil net rebelleer, daarom word ’n wrede boodskapper teen hom uitgestuur.	",
"	12 Laat ’n beer wat van kleintjies beroof is, ’n mens ontmoet, eerder as ’n dwaas in sy sotheid.	",
"	13 Hy wat besoedel vir suiwer vergelde, die besoedeling sal uit sy huis nie wyk nie.	",
"	14 Die begin van ’n onenigheid is soos water wat jy laat deurbreek; daarom, laat die twis vaar voordat dit losbreek.	",
"	15 Hy wat die besoedelde regverdig verklaar en die regverdige besoedeld verklaar, beide is vir JaHWeH ’n gruwel.	",
"	16 Waarom tog is daar geld in die hand van ’n dwaas om Wysheid te koop terwyl hy geen Verstand het nie? [Handelinge 8:20]	",
"	17 Die vriend het altyd lief, en die broer word gebore met die oog op die nood.	",
"	18 Dit is ’n verstandelose adamiet wat sy handslag gee om borg te staan vir sy vriend.	",
"	19 Wie twis liefhet, het oortreding lief; hy wat sy deur hoog maak, soek verbreking.	",
"	20 Wie ‘n verdraaide hart het, vind die suiwere nie; en hy wat verkeerd is met sy tong, val in die besoedeling.	",
"	21 Hy wat ’n dwaas verwek, vir hom sal dit ’n bekommernis word; en die vader van die dwaas sal nie bly wees nie.	",
"	22 ’n Vrolike hart bevorder die genesing, maar ’n verslae gees laat die gebeente uitdroog.	",
"	23 Die besoedelde neem ’n omkoopgeskenk aan wat uit die boesem kom, om die Paaie van die Reg te buig.	",
"	24 Die verstandige hou die Wysheid voor oë, maar die oë van die dwaas is by die Einde van die Aarde.	",
"	25 ’n Dwase seun is ’n verdriet vir sy vader en bitter smart vir haar wat hom gebaar het.	",
"	26 Is dit alreeds nie goed om die regverdige te beboet nie - om edeles te slaan is onbetaamlik.	",
"	27 Wie sy woorde inhou, besit Kennis; en hy wat kalm is van gees, is ’n man van Verstand.	",
"	28 Selfs ’n sot sal as hy swyg, vir wys gereken word; as hy sy lippe toehou, vir verstandig.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '18',
content: [
		
"	1 DEUR sy eie begeerte skei ‘n man homself af en bestry alle bewyse van die Wysheid.	",
"	2 Die dwaas het geen behae in verstandigheid nie, maar net daarin dat sy hart openbaar word.	",
"	3 As die besoedelde kom, kom ook veragting; en saam met die skande, versmading.	",
"	4 Die woorde van ’n man se mond is diep waters, ’n stroom wat bruis, ’n Fontein van Wysheid.	",
"	5 Om vir die besoedelde te verhef, om die regverdige in die Reg weg te stoot, is nie suiwer nie.	",
"	6 Die lippe van die dwaas kom met getwis, en sy mond roep na slae.	",
"	7 Die mond van die dwaas is sy ondergang en sy lippe ’n strik vir sy siel.	",
"	8 Die woorde van die kwaadstoker is soos lekkernye, en dit gly af na die kamers van die binneste.	",
"	9 Alreeds hy wat hom slap hou in sy werk, hy is ’n broer van ’n verwoester.	",
"	10 Die Naam van JaHWeH is ’n sterk Toring; die regverdige hardloop daarin en word beskut. [Hooglied van Salomo 4:4, Profeet Miga 4:8]	",
"	11 Die besittings van die ryke is sy versterkte stad en soos ’n steil muur in sy verbeelding.	",
"	12 Voor die verbreking is die mens se hart hoogmoedig, maar nederigheid gaan die eer vooraf.	",
"	13 Hy wat antwoord gee voordat hy gehoor het, vir hom sal dit ’n sotheid en ’n skande wees.	",
"	14 Die gees van ’n man ondersteun hom in sy krankheid; maar ’n verslae gees - wie kan dit opbeur?	",
"	15 Die hart van die verstandige verwerf Kennis, en die oor van die wyse soek na Kennis.	",
"	16 Die geskenk van ‘n adamiet maak vir hom ruimte en bring hom in die teenwoordigheid van die aansien-likes.	",
"	17 Hy wat die eerste in sy regsaak is, het reg; maar sy naaste kom en ondersoek hom terdeë.	",
"	18 Die lot laat die geskille ophou en maak sterkes uitmekaar.	",
"	19 ’n Broer teen wie oortree is, is erger as ’n sterk stad; en geskille is soos die grendel van ’n paleis.	",
"	20 Van die vrug van iemand se mond word sy maag versadig; hy word versadig van die opbrengs van sy lippe.	",
"	21 Dood en lewe is in die mag van die tong; en elkeen wat haar graag gebruik, sal haar vrug eet. [Brief van Jakobus 1:26; 3]	",
"	22 Wie ’n vrou gevind het, het suiwerheid gevind en ’n welgevalle van JaHWeH verkry.	",
"	23 Die arme spreek smekinge, maar die ryke antwoord harde dinge.	",
"	24 ’n Man met baie vriende word geruïneer, maar daar is ’n vriend wat sterker aanhang as ’n broer.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '19',
content: [
	
"	1 SUIWERDER is ‘n arme wat in sy rasegtheid wandel, as die verdraaide se lippe, en daarby ’n dwaas.	",
"	2 Selfs sonder Kennis is ‘n siel nie suiwer nie; en hy wat haastig is met die voete, trap mis.	",
"	3 ’n Adamiet se sotheid bederwe sy weg, en sy hart is vertoorn op JaHWeH.	",
"	4 Goed bring baie vriende aan, maar die arme word deur sy vriend verlaat.	",
"	5 ’n Valse getuie bly nie ongestraf nie, en hy wat leuens uitstrooi, sal nie vrykom nie.	",
"	6 Baie soek die guns van die edele, en die man van geskenke het ’n hoop vriende.	",
"	7 Al die broers van die arme haat hom; hoeveel te meer hou sy vriende hulle ver van hom af! Hy jaag agter [hulle aan] met woorde - weg is hulle!	",
"	8 Wie Verstand verkry, het sy siel lief; hy wat Insig bewaar, sal suiwerheid vind.	",
"	9 ’n Valse getuie bly nie ongestraf nie, en hy wat leuens uitstrooi, kom om.	",
"	10 Weelde pas nie vir ’n dwaas nie, hoeveel minder vir ’n kneg om oor vorste te heers!	",
"	11 Die verstand van ’n adamiet maak hom lankmoedig, en dit is vir hom ’n eer om die oortreding te vergewe.	",
"	12 Die grimmigheid van ’n koning is soos die gebrom van ’n jong leeu, maar sy Vreugde is soos Dou op die plante.	",
"	13 ’n Dwase seun is ’n ramp vir sy vader, en die gekyf van ’n vrou is ’n aanhoudende gedrup.	",
"	14 Huis en goed is ’n erfenis van die vaders, maar ’n verstandige vrou is van JaHWeH.	",
"	15 Luiheid laat in ’n diep slaap val, en ‘n trae siel, moet honger ly.	",
"	16 Wie die Gebooie hou, bewaar sy siel; hy wat Haar Weë nie ag nie, sal sterwe.	",
"	17 Wie hom ontferm oor die arme, leen aan JaHWeH; en Hy sal hom sy weldaad vergelde.	",
"	18 Tugtig jou seun, want daar is hoop; maar laat jou siel nie opkom om hom dood te maak nie.	",
"	19 Hy wat groot van woede is, sal die straf dra; want as jy wil red, dan maak jy dit nog erger.	",
"	20 Luister na Raad en neem Tug aan, sodat jy in die vervolg wys kan wees.	",
"	21 Baie planne is in ’n man se hart, maar die Raad van JaHWeH, dié sal bestaan.	",
"	22 Die kostelike besit van ’n adamiet is sy medelye; en ‘n arm man is suiwerder as ’n leuenagtige.	",
"	23 Die Vrees van JaHWeH [is tot] die lewe; en [hy wat dit het] sal tevrede vernag, sonder om deur besoedeling besoek te word.	",
"	24 Steek die luiaard sy hand in die skottel, dan bring hy haar nie eens na sy mond terug nie.	",
"	25 Slaan jy die spotter, dan word die eenvoudige bedagsaam; maar bestraf jy die verstandige, dan sal hy Kennis verkry.	",
"	26 Hy wat sy vader geweld aandoen [en] sy moeder wegjaag, is ’n seun wat skande maak en skandelik handel.	",
"	27 Hou op, my seun, om na Tug te luister, terwyl jy [tog] afdwaal van die woorde van Kennis.	",
"	28 Die getuienis van Belijaal spot met die Reg, en die mond van die besoedelde verslind onreg.	",
"	29 Vir die spotters staan strafgerigte klaar en slae vir die rug van die dwase.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '20',
content: [
		
"	1 DIE wyn spot, en sterk drank lawaai, en elkeen wat daardeur bedwelmd raak, is nie wys nie.	",
"	2 Die dreiging van die koning is soos die gebrom van ’n jong leeu; wie hom vertoorn, verbeur sy siel.	",
"	3 Dit is ’n eer vir ’n man om van twis weg te bly, maar elke sot breek los.	",
"	4 In die herfs ploeg die luiaard nie; en verlang hy iets in die oestyd, dan is daar niks nie.	",
"	5 Die Raad in die hart van ’n man mag diep waters wees, ’n man van Verstand sal dit tog uitskep.	",
"	6 Baie adamiete roem op hulle eie medelye, maar wie vind ’n betroubare man?	",
"	7 Wie in sy rasegtheid wandel as ’n regverdige - geseënd is sy kinders ná hom.	",
"	8 ’n Koning wat op die Troon van oordeel sit, wan met Sy oë alles uit wat besoedel is.	",
"	9 Wie kan sê: Ek het my hart suiwer gehou, ek is skoongewas van my oortredinge?	",
"	10 Twee soorte gewig, twee soorte maat - hulle altwee is vir JaHWeH ’n gruwel.	",
"	11 Die seun laat hom alreeds aan sy handelinge ken, of sy handelwyse suiwer en of dit reg is.	",
"	12 ’n Oor wat hoor, en ’n oog wat sien - JaHWeH het hulle altwee gemaak.	",
"	13 Moenie die slaap liefhê, sodat jy arm word nie; maak jou oë oop, dat jy jou met brood kan versadig.	",
"	14 besoedel, besoedel! sê die koper; maar as hy wegloop, beroem hy hom.	",
"	15 Daar is goud en ’n menigte robyne, maar ’n kosbare sieraad is die lippe van Kennis.	",
"	16 Neem sy kleed weg, want hy het vir ’n verbasterde borg gestaan, en neem hom as pand vir die uitlander.	",
"	17 Soet is vir ’n mens die brood van bedrog, maar daarna word sy mond vol gruisklippertjies.	",
"	18 Planne kom deur beraadslaging tot stand; voer dan oorlog met suiwer oorleg.	",
"	19 Wie met kwaadsprekery omgaan, maak ’n geheim openbaar; laat jou dus nie in met een wat sy lippe laat oopstaan nie.	",
"	20 Wie sy vader of sy moeder vloek, sy lamp sal in die donkerste Duisternis uitgedoof word.	",
"	21 ’n Besit wat by die begin haastig bymekaar geskraap is - die einde daarvan sal tog nie geseënd wees nie.	",
"	22 Moenie sê: Ek wil die besoedeling vergelde nie! Wag op JaHWeH, dat Hy jou help.	",
"	23 Twee soorte gewig is vir JaHWeH ’n gruwel, en ’n valse weegskaal is nie suiwer nie.	",
"	24 Die voetstappe van ’n vegter hang van JaHWeH af: hoe sou ’n adamiet dan Sy Weg verstaan?	",
"	25 Dit is vir die adamiet ’n strik wanneer hy Apartheid praat en dit dan na sy Geloftes wil heroorweeg !	",
"	26 ’n Wyse koning wan die besoedelde uit en laat die dorswiel oor hulle draai.	",
"	27 Die gees van die adamiet is ’n lamp van JaHWeH, sy deursoek al die kamers van die binneste.	",
"	28 Medelye en Waarheid behoed die Koning, en deur Medelye stut Hy Sy Troon.	",
"	29 Die sieraad van die jongmanne is hulle krag, en die versiersel van grysaards is grys hare.	",
"	30 Die sweer van ‘n wond suiwer die besoedeling uit soos ‘n uitslag die binneste van die liggaam.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '21',
content: [
		
"	1 DIE koning se hart is in die Hand van JaHWeH soos waterstrome: Hy lei haar waarheen Hy wil.	",
"	2 Elke weg van ’n man is reg in sy oë, maar JaHWeH toets die harte.	",
"	3 Om Geregtigheid en Reg te doen, is vir JaHWeH verkiesliker as ’n slagdier.	",
"	4 Hoogheid van oë en trotsheid van hart - die ploegwerk van die besoedelde is ‘n oortreding.	",
"	5 Die planne van die vlytige is net tot voordeel, maar elkeen wat oorhaastig is, [kom] net tot gebrek.	",
"	6 Die verwerwing van skatte deur ’n valse tong is nietigheid wat rondgedryf word deur hulle wat na die Dood soek.	",
"	7 Die gewelddadigheid van die besoedelde sleep hulle weg, want hulle weier om Reg te doen.	",
"	8 Gekronkeld is die weg van ’n skuldige man; maar die opregte - sy handeling is reguit.	",
"	9 Dit is beter om op die hoek van ’n dak te woon as [by] ’n twisgierige vrou in ’n gemeenskaplike huis.	",
"	10 Die siel van die besoedelde begeer die besoedeling; sy naaste vind in sy oë geen meegevoel nie.	",
"	11 As ’n spotter gestraf word, word die eenvoudige bedagsaam; en as ’n wyse onderrig word, neem hy self Kennis aan.	",
"	12 Die regverdige let op die huis van die besoedelde; maar Hy ruineer die besoedelde  in sy besoedeling.	",
"	13 Wie sy oor toestop vir die geskreeu van die arme, hy sal self ook roep en nie verhoor word nie.	",
"	14 ’n Geskenk in die geheim bring die woede tot bedaring en ’n omkoopgeskenk in die skoot die heftige woede.	",
"	15 Vreugde is dit vir die regverdige om Reg te doen, maar ’n verskrikking vir die bewerkers van Ongeregtigheid.	",
"	16 ’n Adamiet wat afdwaal van die Weg van Verstand, sal in die vergadering van die geeste rus.	",
"	17 Wie van vrolikheid hou, is ’n man van gebrek; hy wat van wyn en olie hou, sal nie ryk word nie.	",
"	18 Die besoedelde is ’n losprys vir die regverdige, en die verraaier vir die opregtes.	",
"	19 Dit is beter om in ’n woeste deel van die Aarde te woon as [by] ’n twisgierige en ergelike vrou.	",
"	20 ’n Kosbare skat en olie is in die woning van die regverdige, maar ’n dwase adamiet bring dit deur.	",
"	21 Wie Geregtigheid en Medelye najaag, sal die Lewe, Geregtigheid en Eer vind.	",
"	22 Die wyse beklim die stad van die dapperes en gooi die vesting neer waarop dit vertrou.	",
"	23 Hy wat sy mond en sy tong bewaar, bewaar sy siel van benoudhede.	",
"	24 ’n Hoogmoedige, ’n trotsaard word ’n spotter genoem, een wat in oormaat van hoogmoedigheid handel.	",
"	25 Die begeerte van die luiaard sal hom doodmaak, want sy hande weier om te werk;	",
"	26 die hele dag deur word daar dringend begeer, maar die regverdige gee en hou nie terug nie.	",
"	27 Die slagdier van die besoedelde is ’n gruwel; hoeveel te meer as hulle dit met bloedvermenging bring.	",
"	28 ’n Leuenagtige getuie kom om; maar ’n man wat [goed] luister, spreek vir altyd.	",
"	29 Die besoedelde trek ’n onbeskaamde gesig, maar die opregte gee aan sy weë die regte rigting.	",
"	30 Daar is geen Wysheid, en daar is geen Verstand, en daar is geen Raad teenoor JaHWeH nie.	",
"	31 Die perd word reggemaak vir die dag van die geveg, maar die oorwinning is deur JaHWeH.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '22',
content: [
		
"	1 ‘n NAAM is verkiesliker as groot rykdom, Guns suiwerder as silwer en as goud.	",
"	2 Rykes en armes ontmoet mekaar, JaHWeH het hulle almal gemaak.	",
"	3 ’n Verstandige sien die besoedeling en verberg hom, maar die dwaas gaan verder en word gestraf.	",
"	4 Die loon van nederigheid en die Vrees van JaHWeH, is rykdom, eer en lewe.	",
"	5 Dorings, vangnette lê op die pad van die verbasteringsvoorstaander; hy wat sy siel wil bewaar, bly ver weg daarvandaan. [Génesis 3:18; Markus 4:18]	",
"	6 Leer die seun volgens die Mond die Weg; dan sal hy, ook as hy oud word, van Haar nie afwyk nie. [Psalm 18:30]	",
"	7 Die ryke heers oor die armes, en hy wat leen, is ’n slaaf van die man wat uitleen.	",
"	8 Wie wetsverbreking saai, sal hartseer maai; met die stok van sy woede sal hy vernietig word.	",
"	9 Wie ‘n suiwer oog het, hy word geseën, omdat hy van sy brood aan die arme gee.	",
"	10 Dryf die spotter weg, dan gaan die twis weg; en die stryery en die geskimp hou op.	",
"	11 Hy wat suiwerheid van hart liefhet, wie se lippe aangenaam is - die koning is sy vriend.	",
"	12 Die Oë van JaHWeH bewaar Kennis; daarom verdraai Hy die woorde van die verraaier.	",
"	13 Die luiaard sê: Daar is ’n leeu buitekant; ek kan in die middel van die strate vermoor word!	",
"	14 Die mond van verbasterde vroue is ’n misterieuse kuil; hy op wie JaHWeH vertoornd is, sal daarin val.	",
"	15 As die sotheid vassit in die hart van die seun, die tugroede sal haar daaruit verwyder.	",
"	16 Wie die arme verdruk, bevoordeel hom; hy wat aan die ryke gee, verarm hom net.	",
"	17 Gee gehoor en luister na die woorde van die wyse manne, en let op My Kennis.	",
"	18 Want Sy is lieflik as jy Haar in jou binneste bewaar; mag hulle tesame gereed lê op jou lippe.	",
"	19 Dat jou vertroue op JaHWeH mag wees, daarom onderrig Ek jou vandag, ja, vir jou.	",
"	20 Het Ek jou nie kernagtige spreuke voorgeskrywe met Raad en met Kennis,	",
"	21 om jou bekend te maak Waarheid, betroubare woorde, sodat jy woorde van Waarheid kan antwoord aan die wat jou stuur nie?	",
"	22 Beroof die arme nie, omdat hy arm is, en verbrysel die ellendige nie in die poort nie.	",
"	23 Want JaHWeH sal hulle saak verdedig en hulle berowers van die siel berowe.	",
"	24 Verkeer nie met ’n driftige man nie, en met ’n opvlieënde man moet jy nie omgaan nie,	",
"	25 sodat jy nie gewoond raak aan sy paaie en ’n strik vir jouself span nie.	",
"	26 Wees nie onder die wat die [hand]palm klap, onder die wat vir skulde borg staan nie.	",
"	27 As jy nie het om te betaal nie, waarom sal hulle jou bed onder jou uit neem?	",
"	28 Die ou grenslyne wat jou vaders gemaak het, moet jy nie verlê nie.	",
"	29 Sien jy ’n man wat vaardig is in sy werk - hy kan voor konings staan, hy hoef nie voor geringes te staan nie.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '23',
content: [
		
"	1 SIT jy aan om saam met ’n vors te eet, let dan net op wat vóór jou is,	",
"	2 en sit ’n mes op jou keel as jou siel jou eienaar is.	",
"	3 Moenie sy lekker ete begeer nie, want dit is brood van bedrieglikhede.	",
"	4 Vermoei jou nie om ryk te word nie, laat staan jou slimheid.	",
"	5 Sou jy jou oë daarop laat afvlieg? Maar weg is dit! want skielik maak dit vir hom vlerke en vlieg soos die arend na die Hemele toe!	",
"	6 Eet nie die brood van een wat ‘n besoedelde oog het nie, en begeer nie sy lekker ete nie.	",
"	7 Want soos hy in sy siel bereken, so is hy; eet en drink, sê hy vir jou, maar sy hart is nie met jou nie.	",
"	8 Jou stukkie wat jy geëet het, sal jy uitspuug; en dan het jy jou vriendelike woorde verspil.	",
"	9 Spreek nie voor die ore van ’n dwaas nie, want hy sal die verstandigheid van jou woorde verag.	",
"	10 Verlê die ou grenslyne nie, en kom nie op die landerye van die wese nie.	",
"	11 Want hulle Verlosser is sterk, Hy sal hulle saak teen jou verdedig.	",
"	12 Bring jou hart na die Tug en jou oor na woorde van Kennis.	",
"	13 Hou die Tug nie terug van die seun nie; as jy hom met die roede slaan, sal hy nie sterwe nie.	",
"	14 Jy sal hom wel met die roede slaan, maar sy siel van die Doderyk/Sheol red.	",
"	15 My seun, as jou hart wys word, dan sal My Hart hom ook verheug.	",
"	16 En My niere sal jubel as jou lippe spreek wat Reg is.	",
"	17 Laat jou hart die oortreders nie beny nie, maar wandel die hele dag in die Vrees van JaHWeH.	",
"	18 Waarlik, daar is ’n toekoms, en jou hoop sal nie verydel word nie.	",
"	19 Hoor, My seun, en word wys, en rig jou hart reguit op die Weg.	",
"	20 Wees nie onder die wynsuipers nie, onder die wat as vrate hulle hart ophaal.	",
"	21 Want ’n drinker en ’n vraat sal arm word, en slaperigheid laat stukkende klere dra.	",
"	22 Luister na jou vader wat jou verwek het, en verag jou moeder nie as sy oud geword het nie.	",
"	23 Koop Waarheid en verkoop Haar nie, [ook] Wysheid en Tug en Verstand.	",
"	24 Die vader van ’n regverdige juig baie; en as iemand ’n wyse verwek het, dan is hy bly oor hom.	",
"	25 Laat jou vader en jou moeder bly wees, en laat sy juig wat jou gebaar het.	",
"	26 My seun, gee My jou hart, en laat jou oë ’n welgevalle hê in My Weë.	",
"	27 Want ontug is ’n diep kuil, en ’n volksvreemde vrou is ’n nou put.	",
"	28 Sy lê ‘n lokval om te roof en vermeerder die verraaiers onder die adamiete.	",
"	29 By wie is Ag! ; by wie is Wee my! ; by wie is getwis; by wie is geklaag; by wie is wonde sonder oorsaak; by wie is dofheid van oë?	",
"	30 By die wat láát opbly by die wyn, by die wat ingaan om gemengde drank te proe.	",
"	31 Kyk nie na die wyn as dit rooierig lyk, wanneer dit sy uiterlike voorkoms gee in die beker, en glad na binne gly nie:	",
"	32 op die end byt dit soos ’n slang en spuug gif uit soos ’n adder.	",
"	33 Jou oë sal na verbasterde vroue kyk en jou hart sal skandelike dinge uiter;	",
"	34 en jy sal wees soos een wat in die hart van die see lê en soos een wat op die top van die mas lê.	",
"	35 Hulle het my geslaan, [sê jy dan], ek het geen pyn gevoel nie; hulle het my neergeslaan, ek het dit nie gemerk nie!	",
"	36 Wanneer sal ek wakker word? Dan sal ek dit weer opnuut soek.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '24',
content: [
	
"	1 WEES nie afgunstig op die besoedelde sterfling nie, en begeer nie om met hulle saam te wees nie.	",
"	2 Want hulle hart bedink verwoesting, en hulle lippe spreek moeite.	",
"	3 Deur Wysheid word ’n Huis gebou, en deur Verstand word hy bevestig;	",
"	4 en deur Kennis word die kamers gevul met allerhande kosbare en lieflike goed.	",
"	5 ’n Wyse krygsman is sterk, en ’n man van Kennis ontwikkel Krag.	",
"	6 Want deur suiwer oorleg kan jy voorspoedig oorlog voer, en die oorwinning is deur die menigte van raadgewers.	",
"	7 Die Wysheid is vir die sot te hoog; in die Poort maak hy sy mond nie oop nie.	",
"	8 Hy wat hom voorneem om kwaad te doen, word ’n skelm genoem.	",
"	9 Bloedvermenging is dwaas en ‘n oortreding, en die spotter is ’n gruwel vir die adamiet.	",
"	10 Gedra jy jou slap in die dag van benoudheid, dan skiet jou krag te kort.	",
"	11 Red die wat na die Dood gesleep word, en die wat na die slagbank wankel, hou [hulle] tog terug!	",
"	12 As jy sê: Kyk, ons het dit nie geweet nie! - sal Hy wat die harte toets, dit nie merk nie? En Hy wat let op jou siel, Hy kom dit te wete. En Hy vergeld die adamiet na sy werk.	",
"	13 Eet heuning, My seun, want dit is suiwer, en heuningstroop is soet teen jou verhemelte.	",
"	14 Erken dat die Wysheid só is vir jou siel; as jy [Haar] vind, dan is daar ’n toekoms, en jou hoop sal nie verydel word nie.	",
"	15 Loer nie, o besoedelde, op die woning van die regverdige, verwoes sy verblyfplek nie.	",
"	16 Want sewe maal val die regverdige en staan weer op, maar die besoedelde struikel in die besoedeling.	",
"	17 As jou vyand val, verheug jou nie; en as hy struikel, laat jou hart nie juig nie,	",
"	18 dat JaHWeH dit nie sien en dit miskien verkeerd is in Sy Oë en Hy Sy Toorn van hom afwend nie.	",
"	19 Vererg jou nie oor die besoedeling nie, wees nie afgunstig op die besoedelde nie.	",
"	20 Want die besoedeldes het geen toekoms nie, die lamp van die besoedelde gaan dood.	",
"	21 My seun, vrees JaHWeH en die Koning, laat jou nie in met oproerige mense nie.	",
"	22 Want skielik sal hulle ongeluk opkom, en die uitgang van hulle jare, wie weet dit?	",
"	23 Ook hierdie [spreuke] is van die wyse manne afkomstig. Om partydig te wees in Regspraak, is nie suiwer nie.	",
"	24 Hy wat vir die besoedelde sê: Jy [is] regverdig! - die volke sal hom vervloek, die gemeenskappe sal hom verwens.	",
"	25 Maar met die wat onpartydig straf, gaan dit goed; en oor hulle kom die seën van suiwerheid.	",
"	26 Hy wat regte antwoorde gee, soen die lippe.	",
"	27 Maak jou werk buitekant reg, en bring dit vir jou op die landerye in orde; daarna moet jy dan jou huis bou.	",
"	28 Wees nie sonder oorsaak getuie teen jou naaste nie; want mag jy met jou lippe mislei?	",
"	29 Moenie sê nie: Soos hy aan my gedoen het, so sal ek aan hom doen - ek sal die man vergelde na sy werk.	",
"	30 Ek het by die landerye van ’n lui man verbygeloop en langs die Wingerd van ’n adamiet sonder Verstand,	",
"	31 en kyk, Sy was heeltemal toegegroei van die dorings, Haar oppervlakte was oordek met brandnetels en Haar klipmuur omgegooi.	",
"	32 En ek het Haar aanskou, ja, daarop gelet, gekyk, [en] lering aangeneem:	",
"	33 Nog ’n bietjie slaap, nog ’n bietjie sluimer, nog ’n bietjie hande vou om uit te rus;	",
"	34 dan kom jou armoede aangeloop en jou gebrek soos ’n gewapende man.	",
		

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '25',
content: [
		
"	1 DIT is ook spreuke van Salomo, wat die manne van GizkiJaH, die koning van JeHûWdah, versamel het.	",
"	2 Dit is die Eer van Elohim om ’n saak te verberg, maar die eer van konings om ’n saak na te speur.	",
"	3 Die hoogte van die Hemele en die Afgrond van die Aarde en die hart van die konings is ondeurgrondelik.	",
"	4 Verwyder jy die skuim uit die silwer, dan sal daar vir die silwersmid ’n voorwerp uitkom;	",
"	5 verwyder die besoedelde voor die Koning weg, dan sal Sy Troon deur Geregtigheid bevestig word.	",
"	6 Pronk nie voor die Koning nie, en staan nie op die plek van die grotes nie.	",
"	7 Want dit is beter dat vir jou gesê word: Kom op hierheen! - as dat jy verneder word voor ’n edele wat jou oë gesien het. [Lukas 14:8]	",
"	8 Gaan nie haastig uit om te twis nie; anders, wat sal jy ten slotte doen as jou naaste jou in die skande steek?	",
"	9 Verdedig jou saak teen jou naaste, maar openbaar ’n ander se geheim nie,	",
"	10 sodat een wat dit hoor, jou nie beskimp en jou slegte gerug nie ophou nie.	",
"	11 Goue appels op versierde silwerborde, [so] is ’n woord op sy tyd gespreek.	",
"	12 ’n Wyse bestraffer by ’n oor wat luister, is ’n goue ring en ’n goue sieraad.	",
"	13 Soos die verkoeling van sneeu op ’n oesdag, is ’n betroubare boodskapper vir sy senders; want hy verkwik die siel van sy meester.	",
"	14 ’n Man wat hom beroem op ’n geskenk wat hy tog nie gee nie, is soos dampe en wind waar geen reënbui by is nie.	",
"	15 Deur lankmoedigheid word ’n vors oorgehaal, en ’n sagte tong verbreek die gebeente.	",
"	16 Het jy heuning gevind, eet tot jy genoeg het, sodat jy daar nie sat van word en dit uitspuug nie.	",
"	17 Sit jou voet selde in jou vriend se huis, sodat hy nie van jou genoeg kry en jou haat nie.	",
"	18 ’n Knopkierie en ’n swaard en ’n skerp pyl, so is ’n man wat teen sy naaste as valse getuie optree.	",
"	19 ’n Slegte tand en ’n voet wat swik, so is die vertroue op ’n verraaier in die dag van benoudheid.	",
"	20 Soos een wat ’n kleed uittrek op ’n koue dag, soos asyn op loog, so is een wat liedere sing vir ’n besoedelde hart.	",
"	21 As jou teëstander honger het, gee hom brood om te eet; en as hy dors het, gee hom water om te drink.	",
"	22 Want jy hoop gloeiende kole op sy hoof, en JaHWeH sal jou dit vergelde.	",
"	23 Die noordewind bring ’n reënbui voort, en die tong wat agteraf praat - kwaai gesigte.	",
"	24 Om te woon op die hoek van ’n dak, is beter as [by] ’n twisgierige vrou en ’n gemeenskaplike huis.	",
"	25 Koue water op ’n vermoeide siel, so is goeie nuus uit ’n ver deel van die Aarde.	",
"	26 ’n Troebel fontein en ’n vuil bron, so is die regverdige wat wankel voor die besoedelde.	",
"	27 Om baie heuning te eet, is nie goed nie, maar om swaar sake na te speur, is ’n eer.	",
"	28 ’n Afgebreekte stad sonder muur, so is ’n man wat nie oor sy gees kan heers nie.	",
		

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '26',
content: [
		
"	1 SOOS sneeu in die somer en soos reën in die oestyd, so pas eer nie by ’n dwaas nie.	",
"	2 Soos die voëltjie wegfladder, soos die swaweltjie wegvlieg, so is ’n vervloeking sonder oorsaak: dit kom nie uit nie.	",
"	3 ’n Sweep is vir die perd, ’n toom vir die esel en ’n roede vir die rug van die dwase.	",
"	4 Antwoord ’n dwaas nie na sy sotheid nie, sodat jy ook nie net soos hy word nie.	",
"	5 Antwoord ’n dwaas na sy sotheid, sodat hy nie wys is in sy eie oë nie.	",
"	6 Hy kap sy voete af, hy ly onreg, wat ’n boodskap stuur deur middel van ’n dwaas.	",
"	7 Soos die bene van ’n lamme slap afhang, so is ’n spreuk in die mond van die dwase.	",
"	8 Soos een wat ’n klip in ’n slinger vasbind, so is hy wat eer gee aan ’n dwaas.	",
"	9 Soos ’n doring wat in die hand van ’n dronkaard gesteek het, so is ’n spreuk in die mond van die dwase.	",
"	10 Soos ’n skutter wat alles in gevaar bring, is hy wat ’n dwaas huur, sowel as hy wat verbygangers huur.	",
"	11 Soos ’n hond wat na sy uitbraaksel teruggaan, is ’n dwaas wat sy sotheid weer ophaal. [JeshaJaH 28:8; 2 Petrus 2:22]	",
"	12 Het jy ’n man gesien wat wys is in sy eie oë? Daar is meer hoop vir ’n dwaas as vir hom.	",
"	13 Die luiaard sê: Daar is ’n leeu op die pad, ’n leeu op die pleine.	",
"	14 ’n Deur draai rond op haar skarniere, so die luiaard op sy bed.	",
"	15 Het die luiaard sy hand in die skottel gesteek, hy is te moeg om haar na sy mond terug te bring.	",
"	16 Die luiaard is wyser in sy eie oë as sewe wat verstandig antwoord.	",
"	17 Hy wat ’n verbylopende hond aan die ore gryp, is een wat hom vererg oor ’n twis wat hom nie aangaan nie.	",
"	18 Soos een wat onverskillig vuurpyle, dodelike pyle afskiet,	",
"	19 so is die man wat sy naaste bedrieg en sê: Ek speel somaar.	",
"	20 Deur gebrek aan hout gaan die vuur dood, en as daar geen kwaadstoker is nie, bedaar die twis.	",
"	21 [Soos] kole die gloed en hout die vuur laat opvlam, so is ’n twisgierige man om ’n twis aan te hits.	",
"	22 Die woorde van ’n kwaadstoker is soos lekkernye, en dit gly af na die kamers van die binneste.	",
"	23 Silwerskuim waarmee ’n potskerf oorgetrek is - so is gloeiende lippe en ’n besoedelde hart.	",
"	24 Die hater word herken deur sy lippe, maar in sy binneste koester hy bedrog.	",
"	25 As hy sy stem lieflik maak, vertrou hom nie; want sewe gruwels is in sy hart.	",
"	26 Al verberg die haat homself in bedrog, sy besoedeling word in die vergadering openbaar.	",
"	27 Wie ’n kuil grawe, sal in haar val; en hy wat ’n klip rol, hy sal na hom terugkom.	",
"	28 ’n Valse tong haat die wat hy verbrysel het, en ’n gladde mond bewerk ondergang.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '27',
content: [
		
"	1 BEROEM jou nie op die dag van môre nie, want jy weet nie wat die dag sal bring nie.	",
"	2 Laat ’n verbasterde grootpraat en nie jou eie mond nie; ’n uitlander, en nie jou eie lippe nie.	",
"	3 Swaar is ’n klip, en die sand het gewig; maar die ergernis oor ’n sot is swaarder as altwee.	",
"	4 Woede is wreed, en toorn kook oor; maar wie kan voor jaloersheid standhou?	",
"	5 Openlike teregwysing is beter as verborge liefde.	",
"	6 Die wonde deur een wat liefhet, is opreg bedoel, maar die soene deur ’n teëstander is oorvloedig.	",
"	7 ’n Versadigde siel vertrap die heuningstroop, maar vir ’n hongerige siel is alles wat bitter is, soet.	",
"	8 Soos ’n voël wat ver van haar nes af rondvlieg, so is ’n man wat ver van sy tuisplek af rondswerwe.	",
"	9 Olie en reukwerk verbly die hart, net so die aangenaamheid van ’n vriend vanweë die sielsraad.	",
"	10 Moenie jou vriend en die vriend van jou vader verlaat nie, en kom nie in die huis van jou broer op die dag van jou teëspoed nie. ’n Buurman wat naby is, is beter as ’n broer wat ver is.	",
"	11 Wees wys, My seun, en verbly My Hart, sodat Ek hom wat My smaad, kan antwoord gee.	",
"	12 As ’n verstandige die besoedeling sien, verberg hy hom; [maar] die dwaas gaan verder, word gestraf.	",
"	13 Neem sy kleed weg, want hy het vir ’n verbasterde borg gestaan; en neem hom as pand vir ’n uitlander.	",
"	14 Wie vroeg in die môre sy naaste met ’n harde stem vloek, dit sal hom as ’n belastering aangereken word.	",
"	15 ’n Aanhoudende gedrup op die dag van ’n stortreën en ’n twisgierige vrou is net eenders.	",
"	16 Wie haar wil teëhou, hou wind teë, en sy regterhand ontmoet olie.	",
"	17 Yster slyp yster, so slyp die een mens die persoon van die ander.	",
"	18 Wie ’n Vyeboom oppas, sal Haar vrugte eet; en hy wat vir sy meester sorg, sal geëer word.	",
"	19 Soos [in] die water aangesig teenoor aangesig is, so is die hart van die adamiet teenoor die adamiet.	",
"	20 die Doderyk/Sheol en Abáddon word nie versadig nie; so word die oë van so ’n adamiet nie versadig nie.	",
"	21 Die smeltkroes is vir die silwer en die oond vir die goud, so is ’n man volgens die roem wat hy geniet.	",
"	22 Al stamp jy die sot in ’n stampblok tussen graankorrels met ’n stamper, sy sotheid sal nie van hom wyk nie.	",
"	23 Gee noukeurig ag op die voorkoms van jou skape, rig jou aandag op die troppe vee;	",
"	24 want rykdom is nie vir ewig nie - of sal separatisme wees van geslag tot geslag?	",
"	25 As die gras verdwyn en die jong gras verskyn en die bossies van die berge bymekaar gemaak word,	",
"	26 dan is daar lammers vir jou kleding en bokke as ’n koopprys vir die landerye,	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '28',
content: [
		
"	1 DIE besoedelde vlug sonder dat daar ’n vervolger is, maar die regverdiges voel hulle veilig soos ’n jong leeu.	",
"	2 Deur die oortreding van die Aarde word haar vorste baie, maar deur ’n verstandige adamiet met Kennis is die Reg duursaam.	",
"	3 ’n Sterk man wat arm is en die armes verdruk, is soos ’n reën wat wegspoel en geen brood bring nie.	",
"	4 Die wat die Wet verlaat, hulle prys die besoedelde; maar die wat die Wet onderhou, word vererg oor hulle.	",
"	5 ‘n Besoedelde persoon verstaan die Reg nie, maar die wat JaHWeH soek, verstaan alles.	",
"	6 Die arme wat in sy rasegtheid wandel, is suiwerder as die verbasteringsvoorstaander wat twee paaie wil loop en daarby ryk is.	",
"	7 Wie die Wet bewaar, is ’n verstandige seun; maar hy wat met deurbringers omgaan, steek sy vader in die skande.	",
"	8 Wie sy goed vermeerder deur rente en deur woeker, maak bymekaar vir een wat hom oor die armes sal ontferm.	",
"	9 Wie sy oor wegdraai om nie na die Wet te luister nie, selfs sy gebed is ’n gruwel. [Psalm 141:2; JeshaJaH 1:15]	",
"	10 Wie die opregtes laat verdwaal op ’n besoedelde weg, sal self in sy eie kuil val; maar die rassuiweres sal die suiwere besit.	",
"	11 ’n Ryk man is wys in sy eie oë; maar ’n arme wat verstandig is, ondersoek hom.	",
"	12 As die regverdiges juig, is daar groot sierlikheid; maar as die besoedelde opkom, word die adamiete verberg.	",
"	13 Hy wat sy oortredinge bedek, sal nie voorspoedig wees nie; maar hy wat dit bely en laat staan, sal Barmhartigheid vind.	",
"	14 Geseënd is die adamiet wat voortdurend Vrees; maar hy wat sy hart verhard, sal in besoedeling verval.	",
"	15 ’n Leeu wat brom, en ’n beer wat hongerig is, so is ’n besoedelde wat oor ’n arm volk heers.	",
"	16 ’n Vors wat gebrek aan Verstand het, is wel ryk aan afpersinge, [maar] die wat onregverdige wins haat, sal die dae verleng.	",
"	17 ’n Adamiet wat wreedheid pleeg teen die bloed van ’n siel, sal vlug tot by ‘n put; laat niemand hom vashou nie.	",
"	18 Wie rassuiwer wandel, sal gehelp word; maar hy wat verward is, wat die twee paaie betref, sal meteens val.	",
"	19 Wie sy  Adamah [die adamiet se Aarde] bewerk, het volop brood; maar hy wat nietighede najaag, het armoede volop.	",
"	20 ’n Betroubare man is ryk aan seëninge; maar hy wat haastig is om ryk te word, sal nie ongestraf bly nie.	",
"	21 Om partydig te wees, is nie suiwer nie, want ook vir ’n stuk brood kan ’n sterk man ’n oortreding begaan.	",
"	22 Hy wat oorhaastig is om ryk te word, het ‘n besoedelde oog, en hy weet nie dat gebrek oor hom sal kom nie.	",
"	23 Hy wat ’n adamiet teregwys, sal agterna meer Guns vind as hy wat vlei.	",
"	24 Wie sy vader of sy moeder berowe, en sê: Dit is geen oortreding nie! - hy is ’n bondgenoot van ’n man wat verderflik handel.	",
"	25 Die trotse van siel verwek twis; maar hy wat op JaHWeH vertrou, word verkwik.	",
"	26 Wie op sy eie hart vertrou, hy is ’n dwaas; maar hy wat in Wysheid wandel, word gered.	",
"	27 Wie aan die arme gee, sal nie gebrek ly nie; maar hy wat sy oë toemaak, word swaar vervloek.	",
"	28 As die besoedelde opkom, verberg die adamiet homself; maar as hulle omkom, word die regverdiges baie.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '29',
content: [
		
"	1 ’N MAN wat baie tereggewys is, en sy nek verhard, sal onvoorsiens verbreek word sonder dat daar genesing is.	",
"	2 As die regverdiges talryk word, is die volk bly; maar as die besoedelde heers, sug die volk.	",
"	3 ’n Man wat die Wysheid liefhet, verbly sy Vader; maar hy wat verbaster, vernietig sy erfenis.	",
"	4 ’n Koning hou deur Reg die Aarde in stand, maar ’n man wat belastings afpers, verwoes haar.	",
"	5 ’n Sterk man wat sy vriend vlei, sprei ’n net uit voor sy voetstappe.	",
"	6 In die oortreding van ’n besoedelde persoon is ’n strik, maar die regverdige sal jubel en bly wees.	",
"	7 Die regverdige ken die Reg van die armes, [maar] die besoedelde verkry geen Kennis nie.	",
"	8 Manne wat spot, bring ’n stad in oproer, maar die wyse bring die toorn tot bedaring.	",
"	9 Het ’n wyse man met ’n sot ’n regsaak, dan gaan die sot te kere en lag, sonder bedaring.	",
"	10 Manne van bloed haat die opregtes, en hulle soek die siel van die rassuiwere.	",
"	11 ’n Dwaas laat al sy gees uitvaar, maar ’n wyse bring haar eindelik tot bedaring.	",
"	12 ’n Vors wat luister na ’n leuenagtige woord, sy dienaars is besoedeldes.	",
"	13 Die arme en die man wat verdruk, ontmoet mekaar, JaHWeH verlig altwee se oë.	",
"	14 ’n Koning wat aan die armes Reg in Waarheid verskaf, Sy Troon sal vir Ewig bevestig wees.	",
"	15 Die roede en teregwysing gee Wysheid; maar ’n seun wat aan homself oorgelaat word, steek sy moeder in die skande.	",
"	16 As die besoedelde vermeerder, vermeerder die oortreding; maar die regverdiges aanskou met welgevalle hulle ondergang.	",
"	17 Tugtig jou seun, dan sal hy jou rus gee en aan jou siel vreugde verskaf.	",
"	18 As daar geen openbaring is nie, word die volk bandeloos; maar hy wat die Wet onderhou, geseënd is hy.	",
"	19 Met woorde laat ’n slaaf hom nie waarsku nie; want hy verstaan dit wel, maar hy steur hom daar nie aan nie.	",
"	20 Het jy ’n man gesien wat haastig is in sy woorde? Vir ’n dwaas is daar meer hoop as vir hom.	",
"	21 As ’n mens sy slaaf van jongs af verwen, word hy op die end ondankbaar.	",
"	22 ’n Opvlieënde man verwek twis, en ’n driftige man is ryk aan oortreding.	",
"	23 Die trotsheid van ’n adamiet verneder hom, maar die nederige van gees sal eer verkry.	",
"	24 Hy wat saam met ’n dief deel, haat sy eie siel; hy hoor die beswering, maar openbaar niks nie.	",
"	25 Die vrees vir die adamiet span ’n strik; maar hy wat op JaHWeH vertrou, sal beskut word.	",
"	26 Daar is baie wat die aangesig van die heerser soek, maar die Reg van ’n mens kom van JaHWeH.	",
"	27 ’n Man van onreg is vir die regverdiges ’n gruwel, en vir die besoedelde is die opregte van wandel ’n gruwel.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '30',
content: [
		
"	1 DIE woorde van Agur, die seun van Jake; die las: Die uitspraak van ‘n vegter aan IthiEl - selfs IthiEl en Ukal:	",
"	2 Ja, ek is dommer as 'n mens, en ek het geen Insig van ‘n adamiet nie.	",
"	3 En ek het nie die Wysheid geleer nie, ek het geen Kennis van Apartheid nie.	",
"	4 Wie het na die Hemele opgeklim en neergedaal? Wie het die Gees in SY vuiste versamel? Wie het die waters in ’n kleed saamgebind? Wie het al die eindes van die Aarde vasgestel? Hoe is SY Naam? En hoe is die Naam van SY Seun - as jy dit weet? [Boekrol van Henog 62:1]	",
"	5 Die Woord van Elowahh is gelouter; Hy is ’n Skild vir die wat by Hom skuil. [Psalm 18:30]	",
"	6 Voeg by Sy Woorde niks by nie, sodat Hy van jou nie rekenskap vorder en jy as ’n leuenaar openbaar word nie.	",
"	7 Twee dinge vra ek van U; onthou dit nie aan my voordat ek sterf nie:	",
"	8 Hou valsheid en leuentaal ver van my af; gee my nie armoede of rykdom nie, laat my geniet die Brood wat vir my bestem is;	",
"	9 dat ek nie, as ek oorversadig geword het, U verloën nie, en sê: Wie is JaHWeH? En dat ek nie, as ek arm geword het, steel en die Naam van my Elohey vergryp nie.	",
"	10 Belaster nie ’n slaaf by sy meester nie, sodat hy jou nie vloek en jy daarvoor moet boet nie.	",
"	11 Daar is ’n geslag wat sy vader vervloek en sy moeder nie seën nie,	",
"	12 ’n geslag wat suiwer is in sy eie oë en tog van sy vuiligheid nie gewas is nie,	",
"	13 ’n geslag - hoe trots is sy oë, en hoe hoog is sy ooglede opgetrek! -	",
"	14 ’n geslag waarvan die tande swaarde is, waarvan die gebit messe is, om die ellendiges uit die Aarde te verteer en die behoeftiges onder die adamiete uit.	",
"	15 Die Bloedsuier het twee dogters: Gee, gee! Hierdie drie word nooit versadig nie; vier sê: nooit genoeg nie! -	",
"	16 die Doderyk/Sheol en die Toegesluite moederskoot, die Aarde wat nie genoeg water kry en die vuur wat sê: nooit genoeg nie! [Wysheid van Salomo 4:1; 2 Nikodémus 4:1]	",
"	17 ’n Oog wat met die Vader spot en die gehoorsaamheid aan die Moeder verag - die kraaie van die dal sal haar uitpik, en die kuikens van die arend sal haar verslind.	",
"	18 Drie is hulle wat vir my te ongelooflik is, ja, vier wat ek nie begryp nie:	",
"	19 die weg van die arend in die lug, die weg van ’n slang oor ’n rots, die weg van ’n skip in die hart van die see, en die weg van ’n krygsman by ’n maagd.	",
"	20 So is die weg van ’n vrou wat vermeng; sy eet en vee haar mond af en sê: Ek het niks verkeerd gedoen nie.	",
"	21 Onder drie bewe die Aarde, en onder vier kan sy hulle nie uithou nie:	",
"	22 onder ’n slaaf as hy koning word, en ’n dwaas as hy volop brood het;	",
"	23 onder ’n nie-geliefde as sy [tog] ’n man kry, en ’n slavin as sy haar meesteres uit die besitting verdrywe.	",
"	24 Vier is hulle wat klein is op die Aarde, maar hulle is uitermate wys:	",
"	25 die miere is nie ’n sterk volk nie, en tog berei hulle hul voedsel in die somer;	",
"	26 die klipdassies is nie ’n magtige volk nie, en tog maak hulle hul huis in die rots;	",
"	27 die sprinkane het geen koning nie, en tog trek die hele swerm in goeie orde uit;	",
"	28 die geitjie kan jy met die hande gryp, en tog is hy in die konings se paleise.	",
"	29 Drie is hulle wat statig wegstap, ja, vier wat statig wegloop:	",
"	30 die leeu, die dappere onder die diere, wat vir niks omdraai nie;	",
"	31 die dier met gespierde heupe, of die bok, en ’n koning met die troepemag by hom.	",
"	32 As jy dwaas was deur jou te verhef, of as jy [vooraf] nagedink het - die hand op die mond!	",
"	33 Want drukking van melk bring botter voort, en drukking van die neus bring bloed voort, en drukking van die toorn bring twis voort.	",

]
},
{
book: 'Spreuke_Van_Salomo',
chapter: '31',
content: [
		
"	1 DIE woorde van LémuEl(Salomo), die koning, die Teregwysing, waarmee sy Moeder hom vermaan het:	",
"	2 Wat, My seun, ja wat, seun van My skoot, ja wat, seun van My Geloftes?	",
"	3 Gee jou krag nie aan vroue of jou omgang aan die wat konings uitroei nie.	",
"	4 Die konings, o LémuEl, die konings moet nie wyn drink nie, en die vorste moet nie sterk drank begeer nie;	",
"	5 anders drink hy en vergeet die Insettinge en verdraai die Reg van al die ellendiges.	",
"	6 Gee sterk drank aan hom wat wil ondergaan, en wyn aan die wat bitter van siel is.	",
"	7 Laat hy drink en sy armoede vergeet en aan sy moeite nie meer dink nie.	",
"	8 Maak jou mond oop vir die stomme, vir die regsaak van almal wat wegkwyn.	",
"	9 Maak jou mond oop, oordeel regverdig, en verskaf Reg aan die ellendige en die behoeftige.	",
"	10 [ a Alef.] Wie sal ’n Deugsame Vrou vind? want Haar waarde is ver bo robyne. [Rut 3:11]	",
"	11 [ B; Bet.] Die hart van Haar Man vertrou op Haar, en aan wins sal dit hom nie ontbreek nie.	",
"	12 [ GÒ Ghimel.] Sy beloon Hom met suiwerheid, en nie besoedeling nie, al die dae van Haar lewe.	",
"	13 [ D Dalet.] Sy sorg vir wol en katoen(vlas), en Sy werk met gewillige handpalms.[Wysheid van Sirah 24:21-22; JeshaJaH 19:9]	",
"	14 [ h Hé.] Sy is soos die skepe van ’n handelaar - van ver af bring Sy Haar Brood in. [Wysheid van Sirah 24:21]	",
"	15 [ w” Waw.] En Sy staan op as dit nog nag is en gee voedsel aan Haar huisgesin en die bestemde deel aan Haar Diensmeisies. [Spreuke 9:3]	",
"	16 [ z Zajin.] Sy dink na oor ’n stuk grond en koop haar, van die vrug van Haar handpalms plant Sy ’n Wingerd. [Deuteronómium 2:9; Exodus 23:31]	",
"	17 [ j Get.] Sy omgord Haar lendene met Krag en hou Haar arms stewig.	",
"	18 [ f Tet.] Sy voel dat Haar opbrengs suiwer is, in die nag gaan Haar lamp nie dood nie.	",
"	19 [y Jod.] Sy steek Haar hande uit na die spinstok, en Haar handpalms hou die spoel vas.	",
"	20 [ k Kaf.] Sy brei Haar handpalm uit na die ellendige, en Sy steek Haar hande uit na die behoeftige.	",
"	21 [ l Lamed.] Sy is nie bevrees vir Haar huisgesin vanweë die sneeu nie, want Haar hele huisgesin dra skarlaken stof.	",
"	22 [ m’ Mem.] Sy maak vir Haar dekens, Haar kleding is van fyn linne en purper.	",
"	23 [ n Noen.] Haar Man is bekend in die Poorte as Hy saam met die oudstes van die Aarde sit.	",
"	24 [ s Samek.] Sy maak hemde en verkoop dit, en gordels lewer Sy aan die handelaars.	",
"	25 [ [ Ajin.] Sterkte en Eer is Haar kleed, en Sy lag oor die dag wat kom.	",
"	26 [ Pi Pé.] Haar mond maak Sy oop met Wysheid, en die Wet van Medelye is op Haar tong.	",
"	27 [ xo Tzadé.] Opmerksaam gaan Sy die werksaamhede van Haar Huis na, en die brood van luiheid eet Sy nie.	",
"	28 [ q Kof.] Haar seuns tree op en noem Haar geseënd, Haar Man [ook], en Hy prys Haar:	",
"	29 [ r’ Resj.] Baie Dogters het hulle knap gedra, maar U oortref hulle almal.	",
"	30 [ V, Sjin.] Die bevalligheid is bedrog, en die skoonheid is nietigheid; ’n Vrou wat JaHWeH vrees, Sy moet geprys word.	",
"	31 [ T Taw.] Gee vir Haar van die vrug van Haar hande, en laat Haar werke Haar prys in die Poorte.	",

]
}
];
