const wyshied_van_salomoChapters = [

{
book: 'Wyshied_Van_Salomo',
chapter: '1',
content: [


"	1 HET die Geregtigheid lief, julle wat die Aarde regeer; dink aan JaHWeH in regskapenheid, en soek HOM met ‘n ongeveinsde hart.	",
"	2 Want HY laat HOM vind deur wie HOM nie beproef nie; HY openbaar HOM aan wie HOM nie wantrou nie.	",
"	3 Bose gedagtes trek af van JaHWeH; en as SY Leërmag op die proef gestel word, beskaam dit die onverstandiges.	",
"	4 Die Wysheid sal nie ingaan in ‘n bedrieglike siel nie, en Sy woon nie in ‘n liggaam wat deur wetsverbreking beswaar is nie.	",
"	5 Want die Aparte Gees van Tug ontwyk veinsery; Sy vlug vir onbesonne gedagtes en word beskaam as die Ongeregtigheid naderby kom.	",
"	6 Want die Wysheid is ‘n Gees wat die adamiet liefhet, maar Sy laat ‘n lasteraar nie ongestraf vir [die woorde van] sy lippe nie, omdat El die Getuie is van sy niere en die waaragtige Verspieder van sy hart en die Toehoorder van sy tong.	",
"	7 Die Gees van JaHWeH het die heelal vol gemaak, en HY wat alles saamhou, weet wat daar gesê word.	",
"	8 Daarom bly niemand verborge wat wetsverbreking voorstaan nie en gaan die strafoordeel nie by hom verby nie.	",
"	9 Want daar sal ‘n verhoor wees van die wettelose se oorleg, en die klank van sy woorde kom by JaHWeH om te straf vir sy ongeregtigheid.	",
"	10 Die Oor van die Jaloerse hoor alles, en die geluid van ‘n gemor bly nie verborge nie. [Exodus 20:5]	",
"	11 Waak julle daarom teen nuttelose gemor en vrywaar julle tong teen lastertaal, omdat ook ‘n heimlike woord nie sonder meer aangaan nie en ‘n mond wat lieg, dodelik is vir die siel.	",
"	12 Soek nie die Dood deur ‘n verkeerde lewenspad nie, en lok die rampe nie uit deur die werke van julle hande nie.	",
"	13 Want Elohim het nie die Dood gemaak nie, en Hy verheug Hom nie oor die ondergang van die lewendes nie.	",
"	14 Omdat Hy alles geskep het om te wees; en die geslagte van die Aarde is geneeslik en daar is geen vergif in hulle nie, terwyl die Doderyk/Sheol se mag ook nie uitstrek oor die Aarde nie.	",
"	15 Want die Geregtigheid is onsterflik.	",
	
]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '2',
content: [
		
"	1 WANT hulle oordeel verkeerd en sê vir mekaar: Ons lewe is kort en vol sorge; daar is geen genesing as ‘n mens se einde gekom het nie, en dit is nie bekend dat iemand uit die Doderyk/Sheol kan red nie.	",
"	2 By toeval is ons gebore, en later sal dit wees of ons nooit bestaan het nie; want rook is die asem in ons neus, en ons denke is die vonk van ons hartklop.	",
"	3 As dit geblus is, vergaan die liggaam tot stof en die gees vervlieg soos yl lug.	",
"	4 Ook ons naam word mettertyd vergeet en niemand dink nog aan wat ons gedoen het nie; ons lewe gaan verby soos die skaduwee van ‘n wolk, en dit word versprei soos ‘n newel wat verdryf word deur die son se strale en deur sy warmte tot neerslag word.	",
"	5 Want ons lewe is soos die verbygaan van ‘n skaduwee, en ons einde kan nie herroep word nie, omdat dit verseël is en niemand kom terug nie.	",
"	6 Kom dan, laat ons die goeie wat daar is, geniet; laat ons van die wêreld soos die jeug ‘n haastige gebruik maak.	",
"	7 Laat ons volop neem van die kosbare wyn en mirre, en laat geen lentebloeisel ons ontgaan nie.	",
"	8 Laat ons kranse van rose op ons hoof sit, voordat hulle verlep is.	",
"	9 Laat niemand van ons agterbly in ons uitbundigheid nie, en laat ons orals die spore agterlaat van ons vrolikheid, want dit is ons aandeel en ons erfgoed.	",
"	10 Laat ons die behoeftige vrome verdruk, laat ons geen weduwees spaar nie en die hoogbejaarde hare van die grysaard nie ontsien nie.	",
"	11 Laat ons mag die maatstaf van Reg wees, want wat swak is, bewys sy eie nutteloosheid.	",
"	12 Laat ons ‘n lokval opstel vir die regverdige, omdat hy ons tot las is en hom teen ons optrede verset; hy verwyt ons dat ons die Wet oortree en hy beskuldig ons dat ons oortree teen die Tug.	",
"	13 Hy beroem hom op sy kennis van JaHWeH, en hy noem homself ‘n seun van Elohim.	",
"	14 Hy is vir ons ‘n aanklag teen ons opvattinge, en dit is selfs hinderlik om hom te sien;	",
"	15 want sy lewenswyse verskil van ander, en sy paaie is volkome anders.	",
"	16 Hy reken dat ons namaaksels is; en hy bly ver van ons paaie soos van vuilgoed. Hy prys die uiterstes van die wetsgetroues, en hy beroem hom daarop dat Elohim sy Vader is.	",
"	17 Laat ons sien of sy woorde waar is; laat ons die omstandighede van sy einde ondersoek.	",
"	18 Want as die rassuiwere ‘n seun van Elohim is, sal Hy hom beskerm en verlos uit die hand van sy teenstanders.	",
"	19 Laat ons hom op die proef stel deur smaad en mishandeling, sodat ons sy sagmoedigheid kan sien en sy geduld kan toets.	",
"	20 Laat ons hom veroordeel tot ‘n eerlose dood, want volgens sy woorde word hy beskerm.	",
"	21 So is hulle gedagtes, en [tog] dwaal hulle, want hulle besoedeling het hulle blind gemaak.	",
"	22 Hulle het geen wete van Elohim se geheimenisse nie, hulle verwag geen beloning vir vroomheid nie en hulle oordeel vleklose siele nie werd om geëer te word nie.	",
"	23 Elohim het die adamiet geskep vir onsterflikheid, en HY het hom gemaak as ‘n beeld van SY eie, ewige Wese;	",
"	24 maar deur die naywer van die duiwel het Dood in die wêreld gekom, en die wat haar toebehoort, sal haar soek.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '3',
content: [
	
"	1 DIE siele van die regverdiges is in die Hand van Elohim, en geen kwelling sal hulle tref nie. [Wysheid van Salomo 5:15, 16]	",
"	2 In die oë van die dwases het hulle die skyn of hulle sterf, en hulle einde word as ‘n ramp beskou;	",
"	3 hulle heengaan van ons word as ‘n vernietiging gesien, maar hulle is in vrede.	",
"	4 Want vir die mense lyk dit of hulle gepynig word, en tog is hulle vol hoop op die onsterflikheid.	",
"	5 Terwyl hulle in ‘n geringe mate getugtig word, sal hulle groot weldade ontvang; want Elohim stel hulle op die proef en vind dat hulle Hom werd is.	",
"	6 Soos goud in die smeltoond beproef Hy hulle, maar Hy neem hulle aan soos die ryp vrug van ‘n aanbieding.	",
"	7 En in die tyd van hulle oordeel sal hulle skitter; hulle sal sprankel soos vonke in ‘n stoppelland.	",
"	8 Hulle sal nasies oordeel en volke regeer, en JaHWeH sal hulle Koning wees tot in ewigheid.	",
"	9 Die wat in Hom glo, sal die Waarheid ken; en die wat op Hom vertrou, sal in Sy liefde bly, omdat Sy Guns en Ontferming vir die uitverkorenes is.	",
"	10 Maar die oortreders word gestraf ooreenkomstig hulle denke - hulle wat die wetsgetroue minag en JaHWeH verlaat.	",
"	11 Want vervloek is diegene wat Wysheid en Tug minag: hulle hoop is ydel, hulle moeite is vergeefs, en hulle werke is nutteloos.	",
"	12 Hulle vroue is onbedagsaam en hulle kinders gee las; vervloek is hulle saadlyn.	",
"	13 Geseënd daarom die onvrugbare vrou wat haar suiwerheid bewaar het, sy wat geen omgang van oortreding ken nie; sy sal die vrugte pluk as die siele geoordeel word.	",
"	14 Geseënd ook die ontmande wat sy hand nie laat oortree nie, hy wat geen oortreding teen JaHWeH begeer nie, want hy sal ‘n uitgesoekte geskenk ontvang vir sy trou; hy sal ‘n kosbare aandeel hê in die Huis van JaHWeH.	",
"	15 Want eervol is die vrug van suiwer werke, en onverganklik is die wortel van bedagsaamheid.	",
"	16 Maar die kinders van vermenging bly onvolwasse, en die kroos van ‘n onwettige vermenging gaan tot niet.	",
"	17 En wanneer hulle lank lewe, word hulle tog soos niks geag, en eindelik is hulle ouderdom eerloos.	",
"	18 Wanneer hulle vroegtydig sterwe, het hulle geen hoop nie, en geen vertroosting op die dag van die oordeel nie.	",
"	19 Want rampsalig is die einde van ‘n besoedelde saadlyn.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '4',
content: [
		
"	1 BETER is kinderloosheid wat gepaard gaan met Suiwerheid: Sy bly onsterflik in die herinnering, omdat Sy erken word by Elohim en by die adamiet. [Spreuke 30:15-16]	",
"	2 As Sy aanwesig is, word Sy nagevolg; as Sy heengegaan het, word Sy gemis. Sy word bekroon en Sy seëvier, omdat Sy oorwin het deur te streef na ‘n onbesoedelde beloning.	",
"	3 Daarom sal ‘n groot getal kinders vir die besoedeldes nie voordelig wees nie: van basterlote gaan die wortel nie diep nie, en hulle sit nie op ‘n stewige grondslag nie.	",
"	4 Want ook al bot hulle ‘n tydlank uit in takke, hulle word geskud deur die wind omdat hulle wankelrig staan, en hulle word deur die krag van die stormwinde ontwortel.	",
"	5 Die bastertakke word rondom gebreek, en hulle vrug is nikswerd, hulle is te besoedel om te eet en vir niks bruikbaar nie.	",
"	6 Want kinders wat uit vermenging gebore word, is in die oordeel die getuies teen hulle ouers se misdaad. [Openbaring van Petrus 1:26]	",
"	7 Maar as ‘n regverdige voortydig sterf, sal hy verkwik word:	",
"	8 want die ouderdom is nie eervol vanweë die lang lewensduur nie, en dit word ook nie gemeet na die getal van die jare nie;	",
"	9 maar grys hare beteken vir die adamiet verstandigheid, en ouderdom ‘n vleklose lewe.	",
"	10 Omdat hy aan sy Elohey welgevallig was, is hy bemin; en omdat hy tussen oortreders geleef het, is hy weggeneem.	",
"	11 Hy is weggeruk, sodat besoedeling nie sy verstand sou verander nie, en sodat listige bedrog nie sy gees sou mislei nie;	",
"	12 want die betowering van die besoedeling verduister die suiwer dinge, en die bedwelming van die begeerte bederf ‘n onskuldige gees.	",
"	13 Hy het jonk gesterf en tog die volheid van baie jare bereik:	",
"	14 want sy siel was welgevallig aan JaHWeH; daarom het Hy haar spoedig weggeneem uit die midde van die kwaad. Maar die mense wat dit gesien het, het dit nie begryp nie en hulle het dit ook nie oorweeg nie:	",
"	15 Sy Guns en Ontferming is vir Sy uitverkorenes, en Sy beskerming is vir Sy apartes.	",
"	16 Die regverdige wat gesterf het, veroordeel die oortreders wat leef; en sy jeug wat vroeg geëindig het, is [’n veroordeling van] die bose se hoë ouderdom.	",
"	17 Want hulle sien wel die einde van ‘n wyse, maar hulle verstaan nie JaHWeH se planne met hom nie, en ook nie waarom Hy hom in veiligheid gebring het nie.	",
"	18 Hulle sien en het slegs minagting, maar JaHWeH lag oor hulle.	",
"	19 Want later word hulle ‘n lyk sonder eer en vir ewig ‘n bespotting onder die dooies. Hy laat hulle neerstort sonder geluid en ruk hulle los van hulle grondslag; tot die einde [van die Aarde] verwilder Hy hulle, en hulle sal in pyne wees, terwyl hulle gedagtenis in die niet versink.	",
"	20 Met vrees sal hulle verskyn vir die afrekening van hulle ongeregtigheid, en hulle eie misdade sal teen hulle, hulle skuld bewys.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '5',
content: [
		
"	1 DAN sal die regverdige met groot vertroue voor die aangesig staan van die wat hom verdruk het en wat sy sorge geminag het.	",
"	2 Terwyl hulle kyk, sal hulle oorval word deur ‘n geweldige vrees, en hulle sal oorstelp wees oor die onverwagsheid van die redding.	",
"	3 En hulle wat te laat tot ander insigte gekom het en wat sug vanweë die benoudheid van hulle gees, sal vir mekaar sê:	",
"	4 Dit was nou die man met wie ons vroeër gespot het en wat ons in ons dwaasheid vir ‘n toonbeeld van veragting gehou het; ons het sy lewe as ‘n dwaasheid beskou en sy einde as eerloos.	",
"	5 Hoe word hy [nou] onder die seuns van Elohim gereken, en is sy aandeel met die apartes!	",
"	6 Ons het dus wel afgedwaal van die Weg van die Waarheid, en die Lig van Geregtigheid het nie vir ons geskyn nie, terwyl die son nie vir ons opgegaan het nie.	",
"	7 Ons het ons moeg gemaak op die paaie van Ongeregtigheid en verderf, en ons het deur ongebaande wildernisse getrek, maar die Weg van JaHWeH het ons nie geken nie. [Psalm 18:30]	",
"	8 Wat het die hoogmoed ons gehelp? En wat het rykdom en grootpraat ons gebring?	",
"	9 Al daardie dinge het verbygegaan soos ‘n skaduwee, en soos ‘n tyding wat verbyjaag.	",
"	10 Soos ‘n skip wat deur die golwende water vaar, sonder dat ‘n mens ‘n spoor van sy deurgaan, of die pad van sy kiel in die golwe kan vind.	",
"	11 Of soos ‘n voël wat deur die lug vlieg. Niks word van hom gevind as teken van sy vlug nie, as alleen die yl lug wat deur die slag van sy vlerke gegésel word, wat op sy deurtog gesny word deur die krag van sy snel-bewegende vlerke; maar daarna word daar geen enkele aanduiding van sy vlug gevind nie.	",
"	12 Of wanneer ‘n pyl na ‘n doel geskiet word: die lug word deursny maar dit word weer ongedaan gemaak, sodat van die deurtog niks meer gesien word nie.	",
"	13 So is ons gebore en het ons gesterwe, en ons het niks om as teken van ons deug te wys nie, maar wel het ons onsself in besoedeling verbruik.	",
"	14 Die hoop van die wettelose is soos stof wat deur die wind weggedra word; en soos ligte skuim wat deur die stormwind versprei word; en soos rook wat deur die wind verstrooi word; dit trek verby soos die herinnering aan ‘n gas van een dag.	",
"	15 Maar die wetsgetroue sal leef tot in ewigheid; by JaHWeH is hulle beloning, en die Hoogste El dra sorg vir hulle.	",
"	16 Daarom sal hulle ‘n glansryke koningskroon en ‘n pragtige voorhoofsband ontvang uit die Hand van JaHWeH; want Hy sal hulle beskerm met Sy Regterhand en hulle beveilig met Sy Arm. [Exodus 28:36; Wysheid van Salomo 3:1]	",
"	17 Hy sal Sy Ywer neem as ‘n pantser, en Hy sal die skepping bewapen om die vyande af te weer.	",
"	18 Hy sal Geregtigheid aantrek as ‘n borswapen en Sy onfeilbare oordeel opsit as ‘n helm.	",
"	19 Hy sal Sy Apartheid neem as ‘n onoorwinlike skild,	",
"	20 en Sy strenge Toorn sal Hy skerpmaak tot ‘n swaard; en die heelal sal saam met Hom stry teen die dwase.	",
"	21 Die goedgemikte pyle van die bliksems sal trek, en soos uit ‘n goedgespanne boog van wolke tref hulle die doel.	",
"	22 Uit die steenslinger van Sy Grimmigheid sal die swaar haelstene gegooi word; die water van die see sal oor hulle breek, en die riviere sal met onstuimigheid saamvloei.	",
"	23 ‘n Magtige Gees sal teen hulle opsteek en hulle uit mekaar jaag soos ‘n orkaan; Ongeregtigheid sal die Adamah [die adamiet se Aarde] tot ‘n woesteny maak, en die misdadigheid sal die trone van die vorste omverwerp.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '6',
content: [
		
"	1 HOOR dan, konings, en gee ag; leer julle, wat die eindes van die Aarde beheers!	",
"	2 Luister, julle wat mag besit oor die skares en wat trots is op julle menigtes van volke.	",
"	3 Want die mag is aan julle deur JaHWeH gegee, en julle heerskappy deur die Hoogste El, wat julle werke sal ondersoek en julle planne sal navors.	",
"	4 Want ofskoon julle die plaasvervangers van Sy Koningskap is, het julle tog nie met Reg geoordeel nie, nie die Wet nagekom nie en nie ooreenkomstig die Wil van Elohim gehandel nie.	",
"	5 Skrikwekkend en spoedig sal Hy teen julle optree, omdat oor die owerstes streng geoordeel word.	",
"	6 Want die onaansienlike word verontskuldig in ontferming, maar die magtiges word gestraf met Mag.	",
"	7 En Hy wat Meester van almal is, sal Sy Aangesig nie verberg nie en geen vrees hê vir grootheid nie; klein en groot het Hy gemaak, en vir almal dra Hy gelyktydig sorg.	",
"	8 Maar vir die magtiges wag ‘n kragtige ondersoek.	",
"	9 Vir julle is dus my woorde, regeerders! Sodat julle Wysheid leer en nie tot val kom nie.	",
"	10 Want die wat die Aparthede in Apartheid onderhou, word self apart; en die wat dit geleer het, sal die regte antwoorde vind.	",
"	11 Wees julle daarom gretig om my woorde te hoor, begeer daarna, en julle sal leiding ontvang.	",
"	12 Wysheid gee Lig en Sy kan nie gedoof word nie. Sy word gemaklik gesien deur die wat Haar liefhet, en Sy word gevind deur wie Haar soek.	",
"	13 Sy voorkom die wat na Haar verlang deur self eerste te verskyn.	",
"	14 En diegene wat vir Haar vroeg opstaan, sal geen moeite hê nie, want hy sal Haar vind omdat Sy by sy deur sit.	",
"	15 Dit is uiters verstandig om oor Haar na te dink; en wie homself ter wille van Haar geen slaap gun nie, is spoedig sonder sorge. [Psalm 132:4]	",
"	16 Want Sy gaan rond en soek hulle wat Haar werd is; en Sy vertoon Haar met minsaamheid aan hulle op hulle paaie, en kom hulle selfs tegemoet in elke gedagte.	",
"	17 Sy begin as ‘n opregte verlange na Tug, en die sorg vir die Tug is liefde;	",
"	18 en liefde is om Haar Wet te onderhou; en die navolging van die Wet is ‘n waarborg vir onsterflikheid; [Deuteronómium 30:13; Wysheid van Sirah 15:1-3; Spreuke van Salomo 6:20]	",
"	19 en onsterflikheid maak dat ‘n adamiet naby Elohim is.	",
"	20 Die verlange na Wysheid lei daarom na die koningskap. [Openbaring 1:6]	",
"	21 As julle behae skep in trone en septers, vorste van die volke, het dan die Wysheid lief, sodat julle kan koning wees in lengte van dae. [2 Ezra 2:43]	",
		
		
"	22 EK sal julle meedeel wie die Wysheid is en hoe Sy ontstaan het. Ek sal Haar geheime nie vir julle verborge hou nie, maar Haar spore volg vanaf die begin van Haar ontstaan, en ek sal Haar Kennis aan die lig bring en in geen enkele opsig die Waarheid verbygaan nie.	",
"	23 Ek sal nie saamgaan met die naywer wat verteer nie, want die Wysheid woon daarmee nie saam nie.	",
"	24 ‘n Menigte wyse manne is die redding van die wêreld, en ‘n verstandige koning is die welsyn van sy volk.	",
"	25 Laat julle daarom lei deur my woorde: hulle sal julle help.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '7',
content: [
		
"	1 OOK ek is sterflik en ‘n adamiet soos die ander, ‘n afstammeling van die eerste wat uit stof gemaak is; en in die skoot van my moeder het ek vlees geword,	",
"	2 in die tyd van tien maande in bloed gestrem uit die saad van ‘n man en die lus van saamlê.	",
"	3 Toe ek gebore is, het ook ek die gemeenskaplike lug ingeasem, en ek het tereggekom op die Aarde wat vir almal dieselfde is; en my eerste geluid was dieselfde gehuil as van al die ander.	",
"	4 In doeke is ek met sorg gevoed,	",
"	5 want geen enkele koning het by sy geboorte ‘n ander begin.	",
"	6 Op dieselfde wyse kom almal in die lewe en verlaat hulle dit.	",
"	7 Daarom het ek gebid, en my is Insig gegee; ek het geroep, en die Gees van Wysheid het vir my gekom.	",
"	8 Ek het Haar hoër geag as septers en trone; en rykdom het ek as niks beskou in vergelyking met Haar.	",
"	9 Ook edelgesteente het ek nie met Haar gelykgestel nie, want al die goud is in vergelyking met Haar net ‘n bietjie stof, en al die silwer is teenoor Haar soos slyk.	",
"	10 Ek het Haar meer liefgehad as gesondheid en skoonheid, en ek het Haar besit verkies bo die Lig, omdat die glans wat Sy versprei nie gedoof kan word nie.	",
"	11 Maar saam met Haar het tegelyk al die suiwer dinge my deel geword, want onmeetlik is die rykdom in Haar hande.	",
"	12 Ek het al die dinge geniet, omdat Sy die Wysheid is wat hulle gebring het, sonder dat ek geweet het dat Sy in Haar die Moeder is. [Boekrol van Henog 84:3]	",
"	13 In opregtheid het ek Haar leer ken, en sonder afguns deel ek Haar mee; ek hou Haar rykdom nie verborge nie.	",
"	14 Want Sy is vir die adamiete ‘n onuitputlike skat; en hulle wat Haar verwerf het, is aangeneem in vriendskap met Elohim, omdat hulle ‘n band gevorm het deur die geskenke van die Tug.	",
"	15 Mag Elohim Haar aan my gee om ooreenkomstig my kennis te spreek, en om ooreenkomstig die waarde van die gawes te dink, omdat HY die Gids van die Wysheid is en HY die wyses teregwys.	",
"	16 Want in SY Hand is onsself en ons woorde, al ons oorleg en bedrewenheid.	",
"	17 Want dit is HY wat my ‘n betroubare Kennis gegee het van die dinge, sodat ek die bou van die heelal kan deursien en die Krag van die elemente,	",
"	18 die begin en die einde en die middel van die tye, die veranderinge van die sonstilstande en die afwisseling van die jaargetye,	",
"	19 die kringloop van die jaar en die stand van die Sterre,	",
"	20 die natuur van al wat leef en die geaardheid van die diere; die kragte van die Geeste en die gedagtes van die adamiete; die soorte van die plante en die kragte van die wortels;	",
"	21 al die dinge wat verborge of sigbaar is, het ek leer ken, want die Wysheid wat alles gemaak het, het my geleer.	",
		
		
"	22 WANT die Gees wat in Haar is, is Verstandig, apartgestel, enig, veelsydig, fyn, vaardig, deurdringend, suiwer, helder, onkwetsbaar, bedag op die suiwere, skerp,	",
"	23 vry, mild, lief vir die adamiet, standvastig, betroubaar, sonder sorge, in staat om alles te doen en te oorsien, terwyl Sy deurdring tot alle geeste wat verstandig, suiwer en fyn is.	",
"	24 Want die Wysheid is beweegliker as alles wat beweeg, en Sy deurdring en deurtrek alles vanweë Haar suiwerheid.	",
"	25 Sy is die asemtog van Krag van die Elohim en die uitstraling van suiwer Glansrykheid van die Almagtige; daarom kan niks wat besoedel is aan Haar raak nie. [Odes van Salomo 30:5; Wysheid van Sirah 24:3]	",
"	26 Sy is die weerskyn van die ewige Lig en ‘n onbevlekte spieël van die Krag van Elohim en ‘n beeld van Sy Suiwerheid.	",
"	27 Ofskoon Sy slegs Een is, vermag Sy alles; en terwyl Sy in Haarself bly, maak Sy alles nuut; en gedurende al die geslagte gaan Sy binne-in siele van apartes en maak hulle vriende van Elohim en profete.	",
"	28 Want Elohim het niemand lief as alleen diegene wat saam met die Wysheid woon nie.	",
"	29 Want Sy is fraaier as die son en die stelsel van Sterre; en in vergelyking met die Lig word Sy eerste gevind,	",
"	30 omdat na die Lig weer die Nag volg, maar die Besoedeling oorwin nie die Wysheid nie.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '8',
content: [
		
"	1 WANT Sy reik deur Haar krag van die een eind tot die ander, en dit is Sy wat alle dinge gunstig reël.	",
"	2 VANAF my jeug het ek Haar liefgehad en gesoek, en ek het pogings aangewend om Haar vir myself as bruid te neem; ek het verlief geraak op Haar skoonheid.	",
"	3 Sy beroem Haar op Haar afkoms omdat Sy met Elohim leef, en HY wat Meester van alles is, het Haar lief.	",
"	4 Want Sy is ‘n ingewyde in die Kennis van Elohim, en Sy staan by HOM in SY werke. [Openbaring van Henog 11:40, 41]	",
"	5 As rykdom ‘n begerenswaardige besit in die lewe is, wat is dan ryker as die Wysheid wat alles werk?	",
"	6 As die besonnenheid ‘n werk onderneem, wie is dan onder al die werkers wat leef, die bekwaamste?	",
"	7 En wanneer iemand Geregtigheid liefhet - Haar hele bekommernis is die deugde, want Sy onderrig die matigheid en die verstandigheid, die regverdigheid en die sterkte, wat vir die adamiete die nuttigste in hulle lewe is.	",
"	8 As iemand strewe na ‘n veelsydige ervaring, Sy leen die verlede en voorsien die toekoms; Sy verstaan die sin van woorde en die oplossing van raaisels, Sy besit voorkennis van aanwysinge en voortekens, ewenas die afloop van tye en tydperke.	",
"	9 Daarom het ek geoordeel om Haar as lewensgesellin te neem, want ek weet dat Sy vir my ‘n suiwer Raadgeefster sal wees en ‘n Trooster in sorge en smart.	",
"	10 Deur Haar sal ek roem verwerf by die volksmenigte en Eer by die oudstes, ofskoon ek jonk is.	",
"	11 My oordele sal skerpsinnig gevind word, en in die oë van die vorste sal ek bewondering vind.	",
"	12 As ek swyg, sal hulle vir my wag; as ek spreek, sal hulle luister; as ek langer spreek, sal hulle die hand op hulle mond lê.	",
"	13 Deur Haar sal ek onsterflikheid besit, en ek sal ‘n ewige herinnering aan myself by hulle agterlaat.	",
"	14 Ek sal volke bestuur, en nasies sal aan my onderwerp word.	",
"	15 Gevreesde heersers wat van my hoor, sal angs kry; maar vir my volk sal ek goed wees en dapper in die oorlog.	",
"	16 As ek in my huis binnegaan, sal ek by Haar rus vind; want die omgang met Haar veroorsaak geen bitterheid nie en verkeer met Haar bring geen verdriet nie, maar Vreugde en Blydskap.	",
"	17 Hierdie dinge het ek oorweeg vir myself en in My Hart oorpeins: dat daar onsterflikheid geleë is in die saamlewe met die Wysheid,	",
"	18 en edele verkwikking in Haar vriendskap, onuitputlike rykdom in die werk van Haar hande, insig in ‘n innige omgang met Haar, roem in die deelneem aan Haar gesprekke. Daarom het ek rondgegaan om te soek hoe ek Haar vir myself sou kon neem.	",
"	19 Ek was ‘n kind gewees met ‘n fraai gestalte, en ek het ‘n voortreflike siel gekry;	",
"	20 of liewer: omdat ek voortreflik was, het ek in ‘n liggaam sonder gebreke gekom.	",
"	21 Maar ek het geweet dat ek Haar nie sou gekry het nie, as Elohim my Haar nie sou gegee het nie; en Sy was reeds wys om te erken in wie se Guns Sy is - en ek het my tot JaHWeH gewend en HOM gebid; en uit my hele hart het ek gesê:	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '9',
content: [
		
"	1 Elohey van ons Vaders en JaHWeH van Ontferming, wat alles gemaak het deur U Woord, [Openb van Henog 11:40]	",
"	2 en wat deur U Wysheid die adamiet gemaak het, sodat hy sou heers oor die skepsels wat U gevorm het,	",
"	3 en sodat hy die wêreld in Apartheid en regverdigheid sou bestuur, en sou beoordeel met ‘n regverdige gees;	",
"	4 gee U my die Wysheid wat op U Troon sit, en wys U my nie af as een van U kinders nie.	",
"	5 Want ek is U dienskneg en die seun van U Diensmaagd, ‘n adamiet wat swak is en kort leef, en wat nog swakker is in die kennis van U oordeel en U Gebooie;	",
"	6 omdat selfs as iemand die rassuiwerste is onder die seuns van die Adam, hy tog sonder U Wysheid niks werd geag word.	",
"	7 U het my verkies as U volk se koning en as regter oor U seuns en dogters;	",
"	8 U het my gesê om ‘n Huis te bou op die berg van U Apartheid, en ‘n altaar in die Stad van U inwoning, as ‘n afbeelding van die woontent van Apartheid wat U vanaf die begin voorberei het.	",
"	9 By U is die Wysheid wat U werke ken, wat teenwoordig was toe U die heelal maak, wat weet wat behaaglik is in U Oë, en wat met Reg is volgens U Gebooie. [Spreuke 8:22; 9:9]	",
"	10 Stuur U Haar vanuit die Hemele van Apartheid en stuur U Haar vanaf die Troon van U Glansrykheid, sodat Sy met my kan wees en saamwerk, en ek kan weet wat aan U welgevallig is.	",
"	11 Want Sy weet en begryp alles, en Sy sal my in my werke lei met oorleg en my bewaar in Haar Glansrykheid. [Openbaring van Henog 11:41]	",
"	12 Dan sal my werke aangenaam wees, en ek sal U volk regverdig regeer en die troon van my vader werd wees.	",
"	13 Want watter adamiet kan die Raadsbesluite van Elohim ken? Wie kan bedink wat JaHWeH wil?	",
"	14 Want die gedagtes van die sterflinge is onseker, en ons oorweginge is nie vas nie,	",
"	15 omdat die siel beswaar word deur ‘n sterflike liggaam, en die gees wat veel dink, neergedruk word deur die aardse tent.	",
"	16 Ons vermoed maar nouliks die dinge van die Aarde, en met moeite ontdek ons dinge wat voor die hand lê; wie sal dan die dinge van die Hemele kan opspoor?	",
"	17 Wie kan U Wil ken, as U Self nie die Wysheid gee en U Gees van Apartheid van omhoog stuur nie?	",
"	18 Só word die paaie van die adamiete op Aarde reggemaak, en leer hulle wat U behaag, en word hulle gered deur die Wysheid.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '10',
content: [
		
"	1 SY het die eersgeskape vader van die wêreld beskerm toe hy die enigste skepsel was, en Sy het hom uitgelei uit sy val [Génesis 3:23; Boekrol van die Opregte 1:12]	",
"	2 en hom die mag gegee om oor alles te heers. [Génesis 1:28]	",
"	3 Maar die wetsverbreker het Haar in sy toorn verlaat, en hy het te gronde gegaan deur die woede wat sy broer gedood het. [Génesis 4:8]	",
"	4 Vanweë hom is die Aarde oorstroom, maar deur die Wysheid gered, wat die regverdige geloods het op nietige hout. [Boekrol van Henog 67:2]	",
"	5 Nadat die nasies verstrooi is vanweë die algemeenheid van oortreding, het Sy die regverdige [uit]geken en hom sonder smet vir Elohim bewaar; en Sy het hom in sy krag beskerm teen sy liefde vir sy seun.	",
"	6 Sy het die regverdige gered uit die ondergang van die besoedeldes, toe hy wegvlug van die vuur wat op die vyf stede geval het;	",
"	7 daarvan bestaan nog altyd as getuie van oortreding: ‘n rokende puinhoop, plante wat vrug dra op verkeerde tye, en ‘n soutpilaar wat daar staan aan ‘n ongelowige gees.	",
"	8 Want die wat afwyk van die Weg van die Wysheid het nie alleen gestruikel deurdat hulle die suiwer dinge nie meer ken nie, maar hulle het ook aan die wêreld ‘n gedagtenis nagelaat van die dwaasheid, sodat hulle nie kan geheim hou waarin hulle oortree het nie.	",
"	9 Maar die Wysheid het Haar volgelinge uit die kwelling gered. [Psalm 22:4]	",
"	10 Sy het die regverdige wat vir die toorn van sy broer gevlug het op regte Paaie gelei, Sy het hom die koninkryk van Elohim gewys en hom die Kennis van die Aparthede gegee, en Sy het hom in sy arbeid laat voortgaan en sy inspanning vrugbaar gemaak.	",
"	11 Sy het hom bygestaan teen die hebsug van sy verdrukkers en hom ryk gemaak.	",
"	12 Sy het hom ook beskerm teen sy vyande en hom beveilig teen sy belaers; Sy het ‘n sware stryd in sy voordeel beslis om hom te laat weet dat vroomheid alles in mag oortref.	",
"	13 Die regverdige wat verkoop is, het Sy nie aan sy lot oorgelaat nie, maar Sy het hom ontruk aan oortreding:	",
"	14 Sy het met hom afgeklim in die gevangenis en hom in Sy boeie nie verlaat nie, totdat Sy hom die Septer van die koningskap gebring het en gesag oor sy oorheersers. Sy het bewys dat sy aanklaers onwaarheid spreek en hom ewige roem gegee.	",
"	15 ‘n Apartgestelde volk en ‘n suiwer saadlyn het Sy verlos uit ‘n nasie van verdrukkers. [Psalm 77:20]	",
"	16 Sy het ingegaan in die siel van JaHWeH se dienskneg en aan skrikwekkende konings teenstand gebied deur wonders en tekens.	",
"	17 Sy het die apartes die beloning gegee vir hulle inspanning en hulle gelei op ‘n wonderlike weg; bedags was Sy vir hulle ‘n beskerming gewees en snags ‘n lig soos van Sterre.	",
"	18 Sy het hulle deur die Riet See [Skelf See] gebring en hulle deur baie water gelei,	",
"	19 maar hulle vyande het Sy oorstroom en hulle uit die diepte van die afgrond weer laat uitspoel.	",
"	20 So het die regverdiges die besoedeldes gebuit, en het hulle die Naam van U Apartheid besing, JaHWeH, en eensgesind U verdedigende Hand geloof. [Exodus 24:11]	",
"	21 Want die Wysheid het die monde oopgemaak van die wat stom was, en Sy het die tonge van kindertjies verstaanbaar gemaak.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '11',
content: [
		
"	1 SY het hulle werke gerig deur die hand van ‘n profeet van Apartheid:	",
"	2 Hulle het deur ‘n onbewoonde wildernis getrek en op eensame plekke hulle tente opgeslaan.	",
"	3 Hulle het weerstand gebied teen hulle vyande en hulle verweer teen hulle teenstanders.	",
"	4 Hulle het dorstig geword en na U geroep; en aan hulle is water gegee uit ‘n Hoë Rots en verkwikking uit harde Steen.	",
"	5 Want waarmee hulle vyande gestraf is, daarmee is hulle tydens hulle trek geseën.	",
		
		
"	6 DIE Fontein van die rivier wat altyd stroom, is deur bloed besoedel en het troebel geword as straf vir die bevel om die kinders te dood;	",
"	7 daarteenoor het U aan hulle onverwags ryklik water gegee.	",
"	8 Deur hulle dors het U gewys hoe U destyds die vyande gestraf het.	",
"	9 Want ofskoon hulle met ontferming tereggewys is, is hulle nietemin op die proef gestel om te kan weet hoe die besoedeldes gepynig word wat in toorn geoordeel is.	",
"	10 U het hulle op die proef gestel soos ‘n Vader wat waarsku, maar die ander het U opgeëis soos ‘n streng Koning wat ‘n vonnis vel. [JeshaJaH 11]	",
"	11 En die wat nie daarby was nie, is op dieselfde wyse gemartel as die wat wel teenwoordig was,	",
"	12 want ‘n dubbele smart het hulle getref: hulle het ook nog gesug by die herinnering aan die verlede,	",
"	13 want omdat hulle verneem het dat hulle eie kwelling vir die ander voordelig was, het hulle JaHWeH erken.	",
"	14 Diegene immers wat hulle met spot afgewys het toe hy te vondeling gelê is, het hulle na afloop van die gebeurtenisse bewonder, nadat hulle anders as die regverdiges deur dors gekwel is.	",
"	15 Teenoor die onbedagsame oorweginge van hulle ongeregtigheid waardeur hulle afgedwaal het en redelose slange/nagashim en alledaagse ongediertes vereer het, het U aan hulle ‘n menigte redelose wesens as straf gestuur,	",
"	16 sodat hulle sou leer dat iemand gestraf word met die dinge waardeur hy oortree het.	",
"	17 Want vir U Almagtige Hand wat ook die heelal uit vormlose stof geskep het, was dit nie onmoontlik om vir hulle ‘n menigte bere of onverskrokke leeus te stuur nie, [Openbaring van Henog 11:40; 2 Ezra 8:7]	",
"	18 of nuutgeskape en ongekende woedende wesens, wat ‘n vurige asem uitblaas, of krakende rook uitstoot, of geweldige vonke uit hulle oë laat uitstraal;	",
"	19 nie alleen hulle geweld sou hulle dan uitgeroei het nie, maar ook die vreeswekkende aanblik kon hulle reeds laat sterf het.	",
"	20 Afgesien van hierdie dinge, kon hulle geval het deur die krag van een windvlaag, wanneer hulle agtervolg word deur U wraak of gewan word deur die Gees van U Krag. Maar U het alles gereël deur maat en getal en gewig.	",
		
		
"	21 VIR U is dit moontlik om orals U groot Mag te ontplooi, wie sal dan weerstand bied aan die Krag van U Arm!	",
"	22 Teenoor U is die heelal soos die deurslaan van ‘n weegskaal en soos ‘n doudruppel wat in die oggend uitsak op die Aarde.	",
"	23 Vanweë U Almag is U barmhartig jeens almal, en U sien verby die oortredinge van die adamiete, sodat hulle mag bekeer;	",
"	24 want U het alles lief wat daar is, en U het geen afkeer van iets wat U gemaak het nie: U sou dit nie gemaak het nie, as U dit nie liefhet nie. [Wysheid van Sirah 15:11; Maleagi 1:3]	",
"	25 Hoe sal iets ook al bly bestaan, as U dit nie wil nie? Hoe sal dit bewaar word, as U dit nie roep nie?	",
"	26 U spaar alles omdat dit van U is, JaHWeH, wat die lewe liefhet.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '12',
content: [
	
"	1 U onsterflike Gees is in alle dinge.	",
"	2 Daarom tugtig U die oortreders ook bietjie vir bietjie; U waarsku hulle deur hulle te herinner aan die dinge waarin hulle oortree het, sodat hulle besoedeling sal laat staan en trou bly aan U, JaHWeH!	",
"	3 Die wat vroeër op U Adamah[adamiet se Aarde] van Apartheid gewoon het,	",
"	4 het U gehaat vanweë hulle gruwel-dade van toorkuns, en besoedelde plegtighede:	",
"	5 meedoënloos het hulle kinders vermoor, en hulle het menslike ingewande geëet en die vlees en bloed genuttig.	",
"	6 U het besluit om die ingewydes uit die midde van hulle fees [te neem], en om die ouers wat met eie hand die hulpelose siele gedood het deur die hand van ons vaders uit te roei,	",
"	7 sodat die Aarde wat U van almal die hoogste ag, ‘n waardige bevolking sou ontvang van die kinders van Elohim.	",
"	8 Maar U het ook hulle, omdat hulle mense was, ontsien en vir hulle as voorlopers van U leërmag, perdebye gestuur om hulle langsaam uit te roei.	",
"	9 Ofskoon U nie onmagtig was om die oortreders in die stryd oor te lewer in die hande van die regverdiges, of hulle deur vreeswekkende wesens of ‘n streng bevel ineens uit te roei nie,	",
"	10 het U kortstondigheid verwerp en hulle die geleentheid gegee om te besin; ook al het U goed geweet dat hulle ‘n besoedelde saadlyn was en dat die besoedeling vir hulle aangebore was, sodat hulle gesindheid in ewigheid nie sou verander nie,	",
"	11 Want hulle saad was vervloek vanaf die begin; en dit is nie uit ontsag vir een of ander persoon dat U hulle uitstel verleen het van [die straf] vir hulle besoedeling nie.	",
"	12 Want wie sal sê: Wat het U gedoen? Of wie sal hom verset teen U oordeel? Wie sal U beskuldig van die nasies se ondergang, as U hulle self geskep het. Wie sal teen U optree as die verdediger van die oortredinge van die adamiet?	",
"	13 Daar is immers nie ‘n Elohim buiten U nie, wat vir almal sorg dra, sodat U bewys dat U nie onregverdig oordeel nie.	",
"	14 Geen koning of vors sal U kan teëstaan oor die wat U gestraf het nie.	",
"	15 Omdat U regverdig is, bestuur U alles met regverdigheid; U ag dit in stryd met U Mag om iemand te veroordeel wat nie verdien om gestraf te word nie.	",
"	16 Want U Mag is die beginsel van die regverdigheid; en die feit dat U oor alles gesag het, is oorsaak dat U alles ontsien.	",
"	17 U toon U Krag as die volheid van U Mag in twyfel getrek word, en U straf die vermetelheid van hulle wat dit ken.	",
"	18 Ofskoon U heers in mag, oordeel U tog met mate en bestuur U ons met ‘n groot toegewendheid; want U besit die vermoë wanneer U ook al wil.	",
"	19 Deur so te handel, het U U volk onderrig dat dit ‘n wetsgetroue se plig is om mensliewend te wees; en U het by U kinders die goeie verwagting gewek dat U ná die wetsverbreking bekering gee.	",
"	20 Want as U die vyande van U kinders en die wat die dood verdien het, met ‘n dergelike aandag en toegewendheid straf dat U hulle die tyd en geleentheid gee om hulle af te wend van Besoedeling,	",
"	21 met watter omsigtigheid sal U dan U kinders oordeel, omdat U aan hulle vaders onder Eed en Verbond beloftes van Suiwerheid gegee het.	",
"	22 Terwyl U ons ‘n opvoeding gee, gésel U ons vyande duisendmaal, sodat ons aan U Suiwerheid sal dink wanneer ons self oordeel, en ons op ontferming sal hoop wanneer ons self geoordeel word.	",
"	23 Daarom het U ook die besoedeldes wat hulle lewe in dwaasheid deurbring, gekwel deur hulle eie gruwels.	",
"	24 Want in groot mate het hulle gedwaal op hulle doolweë, sodat hulle die veragtelikstes onder die lewende wesens as hulle heersers aangeneem het, en hulleself mislei soos onnosele kinders.	",
"	25 Daarom het U oor hulle - soos oor dom kinders ‘n straf gebring wat hulle verspot maak.	",
"	26 Maar die wat nie gewaarsku word deur ‘n straf wat belaglik maak nie, sal besoek word met ‘n oordeel wat Elohim werd is.	",
"	27 Want deur daardie dinge wat hulle verag het, is hulle voor gestraf en wat hulle as elohim beskou het, het hulle, toe hulle daaroor gestraf word, Hom gesien van Wie hulle vroeër beweer het dat hulle Hom nie ken nie; so het hulle Hom as die ware Elohim erken. Daarom het ook die volheid van die veroordeling oor hulle gekom.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '13',
content: [
		
"	1 AL die mense wat omtrent Elohim onwetend is, is van nature dwaas; so ook die wat uit die suiwer dinge wat hulle waarneem, nie vermag om in te sien dat Hy bestaan nie; en ook die wat wel aandag het vir die werk, maar tog nie die Maker daarvan erken nie.	",
"	2 Maar vuur of wind of die dun lug of die Sterre rondom of die geweldige water of die hemelligte beskou hulle as gode wat heers oor die wêreld.	",
"	3 As hulle daardie dinge as gode aanvaar omdat hulle daarvan die goedheid geniet, dan moes hulle tog geweet het hoeveel verkiesliker die Meester daarvan is, want Hy wat die oorsprong van skoonheid is, het hulle gemaak.	",
"	4 En as hulle die krag en werking bewonder, dan sou hulle daaruit moes begryp het hoeveel magtiger Hy is wat die dinge tot stand gebring het.	",
"	5 Want uit die grootheid en goedheid van die skepsels kan die oorsprong daarvan deur vergelyking gesien word.	",
"	6 Tog tref hulle daaroor minder verwyt; want ofskoon hulle dwaal, soek hulle Elohim en wil hulle Hom vind.	",
"	7 Hulle is besig met Sy werke en vors dit na, maar hulle word mislei deur die skyn, omdat die dinge wat hulle sien, mooi is.	",
"	8 Daarteenoor staan dat hulle nie van alle skuld vrygepleit kan word nie:	",
"	9 want as hulle in so ‘n mate in kennis gevorder het, dat hulle in staat was om die loop van die tye te bepaal, waarom het hulle dan nie eerder die Meester daarvan ontdek nie?	",
"	10 Inderdaad ellendig is daarom die wat hulle verwagtinge in dooie dinge gestel het - dit is hulle wat die werke van adamitiese hande gode noem: goud en silwer, kunswerke en afbeeldinge van lewende wesens, of nuttelose steen wat ‘n outydse handewerk is.	",
"	11 As een of ander ervare houtwerker ‘n boom afgesaag het, skil hy die hele bas rondom noukeurig af, bewerk dit op die beplande wyse, en maak ‘n bruikbare meubel om die lewe gerieflik te maak;	",
"	12 die stukke wat van sy werk afval, gebruik hy om sy voedsel te berei waarmee hy sy maag vul;	",
"	13 dit wat dan nog daarvan afval en heeltemal onbruikbaar is, ‘n krom stuk hout waarin kwaste gegroei het, sny hy uit vir tydkorting en gee daaraan ‘n vorm met die kennis van sy ervaring; hy boots dan die beeld van ‘n sterfling na,	",
"	14 of hy laat dit lyk soos een of ander gewone dier; hy besmeer dit met menie en maak met seegras ‘n blosende velkleur; en elke vlek wat daarin is, smeer hy toe.	",
"	15 Dan maak hy daarvoor ‘n passende woning, en hang dit aan die muur waar hy dit vasmaak met ‘n spyker.	",
"	16 Hy sorg daarvoor dat dit nie gaan val nie, omdat hy weet dat die maaksel nie homself kan help nie; want dit is ‘n beeld en dit moet gehelp word.	",
"	17 Maar as hy nou bid vir sy besittings en sy huwelike en sy kinders, dan skaam hy hom nie om met die lewelose ding te praat nie: vir sy gesondheid doen hy beroep op iets wat swak is,	",
"	18 vir sy lewe vereer hy iets wat dood is, om hulp smeek hy iets wat die minste ervaring het, om ‘n voorspoedige reis bid hy iets wat nie kan loop nie,	",
"	19 om wins en sy besigheid en voorspoed by sy arbeid, vra hy iets wat die onhandigste in handewerk is.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '14',
content: [
		
"	1 ‘n ANDER weer, wat voornemens is om ‘n seereis te maak en wat deur die woeste golwe wil vaar, roep ‘n stuk hout aan wat swakker is as die skip wat hom vervoer.	",
"	2 Want die [vaartuig] is deur die winssug beplan en met vakkundigheid gebou.	",
"	3 Tog is dit U Voorsienigheid, VADER, wat haar bestuur, omdat U die Weg oor die see gegee het en ‘n veilige pad deur die golwe.	",
"	4 U wys dat U in staat is om uit alle gevare te red, selfs wanneer iemand sonder bedrewenheid in die see gaan.	",
"	5 Maar omdat U nie wil dat die werke van U Wysheid ongebruik bly nie, daarom vertrou die mense hulle siele toe aan ‘n nietige stuk hout, en vaar hulle behoue op ‘n vlot deur die branding.	",
"	6 Ook vroeër, toe die trotse reuse verdelg is, het die hoop van die wêreld op ‘n vaartuig ontkom en het die saad van ‘n geslag bewaar gebly vir die wêreld, omdat sy [die Ark] bestuur is deur U Hand.	",
"	7 Geseën is die hout waardeur Geregtigheid plaasgevind het!	",
"	8 Maar vervloek is daardie handemaaksel - die maaksel en sy maker: hy, omdat hy hom gemaak het, en die verganklike maaksel, omdat hulle gode genoem word!	",
"	9 Terselfdertyd verdien hulle om deur Elohim gehaat te word - die wettelose en sy ongeregtigheid;	",
"	10 en die maaksel sal saam met sy maker gestraf word.	",
"	11 Daarom sal daar ook ‘n gerig wees oor die gode van die nasies, omdat hulle onder die skepsels van Elohim tot ‘n gruwel geword het, en tot ‘n ergernis vir die siele van die mense, en ‘n valstrik vir die voete van die dwase	",
"	12 want die gedagte aan afbeeldings was die begin van die verbastering; die uitvinding daarvan was die bederf van die lewe.	",
"	13 Want hulle het nie vanaf die begin bestaan nie, en hulle sal ook nie tot in ewigheid bly bestaan nie:	",
"	14 hulle het immers deur die ydele waan van sterflinge in die wêreld gekom, en daarom is ‘n spoedige einde vir hulle vasgestel.	",
"	15 Want ‘n vader wat verteer is deur die onverwagte verdriet oor ‘n kind wat vroeg gesterf het, het ‘n beeld [van hom] gemaak; en diegene wat vroeër as mens gesterf het, het hy nou as gode gaan vereer; en vir sy diensbares het hy plegtighede en dienste ingestel.	",
"	16 Mettertyd het hierdie wettelose gewoonte toe sterker geword en is onderhou soos ‘n wet.	",
"	17 Ook is die standbeelde vereer op bevel van vorste: omdat die mense so ver gewoon het dat hulle die [vorste] nie in hulle aanwesigheid kon huldig nie, het hulle, op ‘n afstand ‘n voorstelling van hulle voorkoms gevorm en ‘n sigbare standbeeld gemaak van die vereerde koning, sodat hulle die afwesige persoon met ywer kon vlei asof hy teenwoordig was.	",
"	18 En die eersug van die kunstenaar het die wat [die koning] nie geken het nie beweeg tot uitbreiding van die verering;	",
"	19 want miskien met die bedoeling om die vors te behaag, het hy hom ingespan om deur sy kuns die gelykenis nog mooier te maak,	",
"	20 en die menigte wat aangetrek is deur die bekoorlikheid van die werkstuk, het diegene wat hulle kort tevore as mens geëer het, nou as gode vereer.	",
"	21 Dit het vir die lewe ‘n valstrik geword, omdat die mense as gevolg van omstandighede, of om ‘n vors te vlei, die onmededeelbare Naam aan steen of hout maaksels gegee het.	",
"	22 Ook was dit vir hulle nie genoeg om slegs te dwaal omtrent die Kennis van Elohim nie, maar hulle het ook in ‘n groot stryd gelewe vanweë hulle onkunde en tog daardie ellende as die Vrede begroet.	",
"	23 Want hulle vermoor en offer hulle kinders, hulle hou geheime dienste, hulle vier in raserny feeste met ongewone gebruike,	",
"	24 hulle eerbiedig nóg die lewe nog die suiwerheid van die huwelik; die een vermoor die ander op listige wyse of besorg hom verdriet deur vermenging.	",
"	25 En alles gebeur deurmekaar: bloedvermenging en moord, diefstal en listige bedrog, verkragting, ontrou, oproer, meineed,	",
"	26 verontrusting van eensames, ondank vir weldade, verpesting van siele, verwisseling van geslag, losbandigheid in die huwelike, vermenging en uitspattighede.	",
"	27 Want die diens van eerlose heersers is die begin en oorsaak en einde van al die kwaad,	",
"	28 dat die feesvieringe tot raserny lei, dat profete onwaarheid voorspel, dat hulle sleg lewe, dat hulle maklik meineed pleeg;	",
"	29 want omdat hulle in siellose idole glo, verwag die meinediges nie dat hulle gestraf sal word nie.	",
"	30 Tweevoudig is daarom die verdiende straf wat hulle sal tref: omdat hulle deur idole te vereer, kwaad gedink het van Elohim; en omdat hulle meineed gepleeg het vanweë hulle minagting van die Wet.	",
"	31 Want ook al besit die dinge waarby gesweer word geen mag nie, tog volg die straf altyd na die oortreding van die wetsverbrekers.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '15',
content: [
		
"	1 MAAR U, onse Elohim, is suiwer en getrou; U is vol Medelye en U bestuur die heelal met Ontferming.	",
"	2 Want wanneer ons oortree, is ons nog U eiendom en erken ons U Mag; maar ons sal nie oortree nie, omdat ons weet dat ons as U besit beskou word.	",
"	3 Volkome Geregtigheid is dit om U te ken; die wortel van die onsterflikheid is om U Mag te besef.	",
"	4 Geen bedrieglike versinsel van sterflinge het ons laat afdwaal nie, en ook nie die nuttelose inspanning van skilders nie,	",
"	5 waarvan die sien by die dwase begeerte opwek, sodat verlang word na die lewelose gestalte van ‘n dooie afbeelding.	",
"	6 Minnaars van besoedeling en werd om op dergelike dinge te hoop, is die wat dit maak en bemin en vereer!	",
"	7 ‘n Pottebakker byvoorbeeld, knie met inspanning die sagte klei en boetseer allerlei dinge vir ons gebruik; sonder onderskeid maak hy uit dieselfde klei die vaatwerk wat vir ‘n eersame gebruik dienstig is, en die teendeel; maar of dit nou vir die een of die ander doel gebruik word, dit beslis die pottebakker.	",
"	8 Maar met besoedelde inspanning boetseer hy uit dieselfde klei ‘n ydele idool, terwyl hy kort tevore self uit die Aarde gemaak is en oor ‘n kort tydjie weer daarheen teruggaan waaruit hy geneem is, wanneer die siel wat hy geleen het, weer opgeëis word.	",
"	9 Hy vergeet dat hy ooit sal beswyk en dat sy lewensduur kort is; tog wedywer hy met goud- en silwersmede en boots hy die bronswerkers na; hy ag dit selfs ‘n eer dat hy namaaksels kan boetseer.	",
"	10 Sy hart is as, en sy hoop is nietiger as Aarde, en sy lewe verdien minder agting as die klei,	",
"	11 want hy misken Diegene wat hom boetseer het en in hom ‘n werksame gees ingeblaas het, en wat ‘n lewende siel in hom geplant het.	",
"	12 Maar hulle laat dit voorkom dat ons lewe ‘n spel is, en dat die bestaan ‘n winsgewende volksfees is, want hulle meen dat uit alles wins gemaak moet word, selfs uit besoedeling.	",
"	13 Tog weet hy beter as almal dat hy oortree, wanneer hy uit die stof van die Aarde breekbare vate en afbeeldings vervaardig.	",
"	14 Baie dwaas is hulle almal en ellendiger as ‘n kind, daardie vyande van U volk en sy verdrukkers.	",
"	15 Want hulle beskou al die huisidole van die nasies as gode, ofskoon hulle nie hulle oë kan gebruik om te sien nie, hulle neuse nie om lug in te asem nie, hulle ore nie om te hoor nie, die vingers van hulle hande nie om te voel nie, en hulle voete is onbruikbaar om te loop.	",
"	16 Want hulle is gemaak deur ‘n adamiet; iemand wat sy eie siel slegs geleen het, het hulle gevorm. En nie een adamiet kan ‘n god maak wat selfs aan homself gelyk is nie.	",
"	17 Omdat hy sterflik is, maak hy met misdadige hande slegs ‘n lewelose ding: self is hy dus meer as die dinge wat hy vereer, omdat hy self leef en daardie dinge nie.	",
"	18 Hulle vereer ook die afskuwelikste wesens, wat vanweë hulle domheid minder geag word as die ander;	",
"	19 en wat nie so is dat ‘n mens daarvan hou nie, soos dit by die sien van diere wel gebeur; maar dit is wesens waaraan Elohim se lof en Sy seën verbygaan.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '16',
content: [
		
"	1 DAAROM is hulle juis deur middel van diere gestraf, en is hulle gekwel deur swerms ongedierte.	",
"	2 Maar teenoor hulle straf staan dat U U volk goedgedoen het, omdat U aan hulle die kwartel as voedsel gegee het wat ‘n ongewone smaak vir hulle gretige honger was. [Númeri 11:32]	",
"	3 Sodat die ander, ondanks hulle verlange na voedsel, tog vanweë die afstootlikheid van die ongedierte wat oor hulle gekom het, hulle natuurlike eetlus verloor het, terwyl hierdie na ‘n kort tydjie van gebrek selfs ‘n onbekende smaak gekry het.	",
"	4 Want oor die verdrukkers moes ‘n onvermydelike gebrek kom, maar vir hierdie moes alleen gewys word hoe hulle vyande gekwel is.	",
"	5 En toe die grimmige woede van die diere oor hulle kom en hulle deur die byt van giftige slange/nagashim gedood is, het U Toorn nie tot die einde aangehou nie. [Númeri 21:6]	",
"	6 Tot waarskuwing is hulle ‘n kort tydjie verontrus, maar hulle het ‘n Teken van redding besit, om hulle aan die Gebod van U Wet te herinner.	",
"	7 Want wie hom daarheen gewend het, is nie gered deur dit wat hy sien nie, maar deur U, die Redder van almal.	",
"	8 Daardeur het U ook vir ons vyande bewys dat dit U is wat van alle kwaad verlos;	",
"	9 want die ander het gesterf deur die byt van sprinkane en steekvlieë, en vir hulle lewe is geen geneesmiddel gevind nie, omdat hulle werd was om deur derglike [diere] getugtig te word.	",
"	10 Maar die tande van die giftige slange/nagashim kon nie U kinders oorwin nie, omdat U Ontferming daarteen te hulp gekom het en hulle genees het.	",
"	11 Want om hulle aan U Woorde te herinner, is hulle gepik en terstond gered, sodat hulle nie tot diepe vergetelheid sou verval en U weldadigheid sou ontbeer nie.	",
"	12 Want nie kruie of pleister het hulle gesond gemaak nie, maar U Woord, JaHWeH, wat almal genees.	",
"	13 U besit die mag oor lewe en dood; U lei na die poorte van die Doderyk/Sheol en bring [daarvandaan] terug.	",
"	14 Die adamiet daarenteen kan in sy besoedeling wel doodmaak, maar hy kan nie die siel wat heengegaan het, laat terugkeer nie; ook kan hy nie ‘n siel wat ‘n prooi [van die Doderyk/Sheol] geword het, verlos nie.	",
		
		
"	15 DIT is onmoontlik om U Hand te ontvlug:	",
"	16 Die besoedeldes het geweier om U te erken, en hulle is gegesel deur die Krag van U Arm. Deur ongewone reëns en onverbiddelike hael- en onweersbuie is hulle agtervolg, en deur Vuur is hulle verteer.	",
"	17 En die wonderlikste is, dat in die water wat alles uitblus, die Vuur nog feller gebrand het, want in die skepping is Hy die Beskermer van die regverdiges.	",
"	18 Op een tyd is dan die vlamme beteuel, om nie die ongedierte te verbrand wat losgelaat is teen die besoedeldes nie, sodat hulle as hulle dit sien, sou begryp dat hulle deur die Oordeel van Elohim agtervolg word;	",
"	19 en op ‘n ander tyd het die Vuur in die midde van die water bo sy eie krag gebrand, om die gewasse van ‘n Aarde wat oortree het, te verniel.	",
"	20 Daarteenoor staan dat U vir U volk die voedsel van Boodskappers gestuur het; U het onverpoos uit die Hemele toebereide brood aan hulle verskaf, wat alle bevrediging gegee het en wat ooreenkomstig elkeen se smaak was. [Númeri 11:8]	",
"	21 Want U Hulp het U Suiwerheid jeens U kinders geopenbaar, omdat hy voldoen het aan die behoefte van diegene wat hom nuttig, en omdat hy verander het in wat iemand wou hê.	",
"	22 Na die Vuur het sneeu en ys oorgebly en nie gesmelt nie, sodat hulle sou begryp dat die Vuur, wat in die hael opvlam en deur reënbuie trek, die oes van die vyande verniel het.	",
"	23 Maar aan die ander kant ook dat dit Sy eie Krag vergeet het, sodat die regverdiges voedsel sou hê.	",
"	24 Want die skepsel is onderdanig aan U wat hom gemaak het, en Hy span Hom in om die wetsverbrekers te straf, terwyl Hy Homself inhou om die wat op U vertrou, goed aan te doen.	",
"	25 Daarom het Hy diep gegrawe vir alles, en het Hy opgekom met U gawe wat aan almal voedsel verskaf ooreenkomstig die verlange van die wat dit nodig het;	",
"	26 sodat die kinders wat U liefhet, JaHWeH, kan leer dat nie die verskillende gewasse die adamiet voed nie, maar dat U Woord die bewaar wat op U vertrou.	",
"	27 Want ofskoon daardie [voedsel] nie verteer is deur die Vuur nie, het dit tog volkome gesmelt wanneer dit deur ‘n vlugtige straal van die son verwarm is.	",
"	28 So moes dan wel ingesien word dat die adamiet U behoort te dank voor die son [opgekom] het, en dat hy U behoort te ontmoet by die dagbreek.	",
"	29 Want die hoop van die ondankbares smelt soos ryp in die winter en stroom weg soos water wat nie gebruik word nie.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '17',
content: [
		
"	1 GROOT is U oordele en onuitspreeklik! Daarom het die ongeleerde adamiete afgedwaal.	",
"	2 Want die oortreders het gemeen om die volk van Apartheid te onderdruk, maar hulle is deur die Duisternis gebind en deur ‘n lang Nag vasgevang; onder hulle eie dakke opgesluit, het hulle gelê, terwyl hulle verstoke was van die ewige Voorsienigheid.	",
"	3 Hulle het gedink dat hulle met hulle geheime oortredinge verborge is onder ‘n donker sluier van vergetelheid, maar hulle is deur skrikbeelde verontrus en in verbystering uitmekaar gejaag.	",
"	4 Die skuilplek wat hulle verberg het, het hulle nie teen vrees gevrywaar nie, angswekkende galmgeluide het rondom hulle weerklink, terwyl sombere spookbeelde met droewige gesigte opgedoem het.	",
"	5 Geen vuur het genoeg krag besit om lig te gee nie, en selfs die Sterre met hulle helder glans het nagelaat om die vyandige nag te verlig.	",
"	6 Net een vreeswekkende Vuur, wat vanself ontstaan, het nou en dan vir hulle opgevlam; en hulle het opgeskrik, maar as daardie Lig nie langer sigbaar was nie, het die dinge wat hulle gesien het nog erger gelyk.	",
"	7 Die spotterny van hulle toorkuns het platgelê, en smadelik is die grootpraat oor hulle kennis beskaam;	",
"	8 want die wat belowe om angs en vrees uit ‘n siek gees uit te dryf, was self siek vanweë ‘n belaglike bangheid.	",
"	9 Want wanneer daar niks angswekkends was om hulle te verskrik nie, is hulle verwilder deur die beweginge van die ongedierte en die gesis van slange/nagashim, sodat hulle bevrees was en selfs nie na die lug wou kyk wat niemand kan ontwyk nie.	",
"	10 Besoedeling is immers laf en word veroordeel deur haar eie getuienis; altyd veronderstel sy gevare, omdat sy deur die eie gewete gekwel word.	",
"	11 Vrees is dan ook niks anders as die prysgee van die hulpmiddels van verstandige oorleg nie;	",
"	12 en as die vrees inwendig nog minder groot is, dan word die kwelling erger gevoel, omdat die oorsaak van die kwelling nie geken word nie.	",
"	13 Maar ander wat in hierdie waarlik ondraaglike nag, wat uit die boesem van die ondraaglike hel gekom het, gelê en slaap het,	",
"	14 is deur monsteragtige droom-beelde opgejaag of deur vertwyfeling verlam; en ‘n skielike en onverwagte angs het hulle oorval.	",
"	15 So het elkeen neergesink op die plek waar hy toe was; en elkeen is vasgevang en toegesluit in ‘n gevangenis sonder grendel.	",
"	16 Want of iemand nou al ‘n landbouer was of ‘n veeboer of ‘n eensame landarbeider, hy is oorval en moes in ‘n gevangenis bly, waaruit geen ontsnapping moontlik is nie, omdat dieselfde boeie van die Duisternis almal vasgekluister het.	",
"	17 En of dit nou al die geruis van die wind was, of die lieflike sing van voëls op blaarryke takke, of die klotsing van kragtig stromende water, of die verontrustende geraas van klippe wat val,	",
"	18 of die onsigbare bewegings van springende diere, of die geluid van roofdiere wat skreeu, of die weergalm wat terugkaats van die holkranse, dit het hulle van skrik verlam.	",
"	19 Want die hele Adamah[adamiet se Aarde] het gestraal in ‘n helder Lig en het ongehinder aangegaan met haar besighede;	",
"	20 maar alleen op hulle het die swaar Nag toegesak, ‘n beeld van die Duisternis wat hulle eenmaal sal opneem, en tog is hulle meer gepla deur hulleself as deur die donkerte.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '18',
content: [
		
"	1 MAAR vir U apartes was die Lig volop; en toe die ander hulle wel hoor, maar nie sien nie, het hulle hulle geseënd geprys, dat hulle nie net so gekwel word nie;	",
"	2 en hulle was dankbaar dat die veronregtes [hulle] nie kwaad doen nie, en hulle het verskoning gevra vir hulle vyandigheid.	",
"	3 Daarteenoor het U ‘n Vuurkolom gegee as gids vir die onbekende reis, ‘n onskadelike son vir die roemvolle trek.	",
"	4 Want die ander het verdien om van die Lig beroof te word en om deur die Donkerte vasgehou te word, omdat hulle U kinders in boeie vasgehou het, terwyl deur hulle die onverganklike Lig van die Wet aan die wêreld gegee word.	",
		
		
"	5 OMDAT hulle besluit het om die kinders van die apartes te vermoor - maar tog is een seuntjie as vondeling gelê en gered - het U hulle as straf van ‘n menigte kinders beroof en hulle tegelyk in die onstuimige water verdelg.	",
"	6 Daardie nag is vantevore aan ons vaders bekendgemaak, sodat hulle in veiligheid sou weet op watter Eed hulle vertrou het, en goeie moed sou hou.	",
"	7 So is deur U volk gewag op die Verlossing van die regverdiges en die ondergang van die vyande.	",
"	8 Want deur die straf wat U oor die teëstanders gebring het, het U ons geroep en verhoog.	",
"	9 Terwyl immers die regverdige kinders van Apartheid in die geheim geslag het, het hulle eensgesind hierdie Wet van Apartheid vasgestel, sodat die apartgesteldes gelyktydig voorspoed en gevare sou deel; en soos voorheen die lofprysinge van die vaders aangehef.	",
"	10 Maar as ‘n wanklank het in haar die geroep van die vyande geklink, en het die jammerklag oor die betreurde kinders deurgedring.	",
"	11 Deur dieselfde straf is dienskneg en gebieder getref, en het onderdaan en koning dieselfde smart gely;	",
"	12 want gelyktydig het almal deur ‘n gelyknamige dood ontelbare dooies gehad; en die lewendes was nie genoeg om te begrawe nie, toe hulle mees geliefde kroos deur een slag verdelg is.	",
"	13 En die wat vanweë hulle toorkunste by alles ongelowig gebly het, het by die dood van hulle eersgeborenes beken dat daardie volk die kind van Elohim is.	",
"	14 Want terwyl alles diep in rus was, en die nag in die midde van sy baan aangekom het,	",
"	15 het U Almagtige Woord soos ‘n grimmige Krygsman van U Koningstroon in die Hemele, in die midde van die Aarde van bederf gespring, en Hy het U onherroeplike oordeel gedra soos ‘n skerp swaard.	",
"	16 Daar het Hy gaan staan en orals die dood gesaai; en terwyl Hy oor die Aarde stap, het Hy tot aan die Hemele gereik.	",
"	17 Toe het op dieselfde oomblik vreeslike droombeelde hulle verontrus, en onverwagte angste het hulle oorval.	",
"	18 Hier het die een halfdood neergeval, daar die ander, terwyl hulle nog die oorsaak van hulle sterwe meedeel:	",
"	19 dat die drome wat hulle ontstel het, Hy aan hulle voorspel het, sodat hulle nie sou omkom nie sonder om te weet waarom die ramp hulle tref.	",
"	20 Ook aan die regverdiges egter het die beproewing van die dood geraak, en ‘n slagting is in die wildernis onder die menigte aangerig. Maar die Toorn het nie lank aangehou nie,	",
"	21 want ‘n onberispelike man het in die bres getree, wat as wapen van sy dienswerk die gebed en die versoenende reukwerk aanwend; hy het hom teenoor die Toorn gestel en ‘n einde gemaak aan die plaag en gewys dat hy U dienskneg is.	",
"	22 Hy het die Toorn nie deur liggaamskrag of deur wapengeweld oorwin nie, maar deur sy woord het hy die Wreker bedwing, toe hy aan die Eed en die Verbond van die vaders herinner.	",
"	23 Want toe die lyke reeds in hope opmekaar lê, het hy tussenin gaan staan en die Toorn afgeweer, terwyl hy die pad na die lewendes toe versper het.	",
"	24 Die hele wêreld was immers op sy skouerkleed, die roem van die VADER was op vier rye stene uitgesny en U Glansrykheid op die tulband van sy hoof.	",
"	25 Daarvoor het die Verdelger gewyk en daarvoor het Hy ontsag gehad; en alleen die beproewing van die gramskap was al voldoende.	",

]
},
{
book: 'Wyshied_Van_Salomo',
chapter: '19',
content: [
		
"	1 MAAR teen die besoedeldes het die Toorn sonder Ontferming tot die einde gewoed, omdat Hy hulle en hulle toekoms vantevore geken het:	",
"	2 dat hulle sou toestaan om weg te trek, en hulle later selfs met spoed sou wegstuur, maar dan van plan sou verander en hulle agtervolg.	",
"	3 Want hulle was selfs nog besig met roubedryf en het nog geweeklaag by die dooies se grafte, toe hulle in hulle dwaasheid anders besluit, en die as vlugtelinge gaan agtervolg, wat hulle gesmeek het om te trek.	",
"	4 Die verdiende noodlot het hulle dan ook tot hierdie uiterste gedryf en dit het hulle die herinnering laat verloor aan wat hulle oorgekom het, sodat hulle die straf wat na die kwellinge nog oorgebly het, volledig sou ondergaan.	",
"	5 En terwyl U volk ‘n onverwagte deurtog gekry het, het die ander ‘n ongewone dood gevind.	",
"	6 Die hele skepping, wat onderdanig is aan U Bevele, is dan ook opnuut hervorm in haar natuur, sodat U kinders ongedeerd bewaar sou bly.	",
"	7 Die Wolkkolom het die laer oorskadu, en ‘n adamiet kon droë grond sien opkom uit die water wat vroeër daar was: ‘n pad sonder moeilikhede uit die Riet See [Skelf See], en ‘n vlakte met jong plante uit die geweldige vloed. [Exodus 14:16]	",
"	8 Daardeur het die hele volk getrek, en onder U beskerming het hulle vol verbasing U wonders aanskou.	",
"	9 Want hulle was soos perde wat na die weiveld gebring word, of soos skape wat rondspring; en hulle het U geloof, JaHWeH, wat hulle gered het.	",
"	10 Hulle het dan ook teruggedink aan die gebeurtenisse in die Aarde waar hulle bywoners was: hoe in plaas van lewende wesens die Aarde muskiete voortgebring het; hoe in plaas van waterdiere die rivier ‘n menigte paddas opgebring het.	",
"	11 Later het hulle ‘n onbekende ontstaan van voëls aanskou, toe hulle deur lus gedryf is en om smaaklike voedsel gevra het;	",
"	12 want vir hulle bevrediging het die kwartels uit die see opgestyg.	",
"	13 Oor die oortreders het strawwe gekom, maar nie sonder die voorafgaande tekens van die geweld van die bliksems nie; en tereg het hulle vir hulle misdade gely, omdat hulle ‘n baie besoedelde haat teen vreemdelinge gekoester het.	",
"	14 Want terwyl die ander geen persone opneem wat hulle nie ken nie, het hulle die vreemdelinge wat hulle weldoeners was, tot slawe gemaak.	",
"	15 En nie dit alleen nie, maar vir die ander is daar nog verskoning, omdat hulle die vreemdelinge [reeds] met vyandigheid ontvang het,	",
"	16 terwyl hulle die vreemdelinge eers met feestelikhede ontvang het en aan hulle dieselfde regte meegedeel het, maar hulle daarna deur inspannende arbeid afgemat het.	",
"	17 Daarom is hulle met blindheid geslaan, soos daardie ander by die deur van die regverdige, toe hulle in diepe duisternis gehul is, en elkeen die toegang na sy eie deur gesoek het.	",
"	18 So het die elemente hulle telkens weer anders vertoon, soos by ‘n siter die tone van die ritme die geaardheid verander, ook al behou hulle dieselfde klank; en dit blyk duidelik uit ‘n noukeurige beskouing van die feite:	",
"	19 Landdiere is verander in waterdiere, en diere wat swem, het op die Aarde gekom;	",
"	20 die Vuur het in die water in krag gegroei, en die water het sy geaardheid om te blus, vergeet;	",
"	21 aan die ander kant het die vlamme die vleis nie verteer van nietige diere wat in haar rondgeloop het nie, en ook nie die hemelse voedsel laat smelt nie, terwyl dit so goed soos ys kan smelt.	",
"	22 In alles, JaHWeH, het U daarom U volk grootgemaak en verhoog; U het niks oorgesien nie, maar bystand verleen op die regte tyd en plek.	",

]
}
];
